#!/usr/bin/env python3
"""
Generate an m2c context file giving every callee its REAL argument count.

    scripts/gen_context.py rel_duel_eng      # -> build/ctx/rel_duel_eng.h
    scripts/gen_context.py --all

WHY THIS EXISTS. m2c decides how many arguments a call passes by looking at the
call site, and it only reliably sees $a0-$a3. Arguments five to eight travel in
$t0-$t3 under this EABI, and a tail-call trampoline sets some of them and then
`j`s to the callee without ever touching the rest, so nothing at the call site
reveals them. The result is a draft that calls the function with too few
arguments and therefore compiles to too FEW instructions:

    target:  lui $t0, %hi(func_000CD7DC) / addiu $a2, 0x1E / addiu $a3, 3
             j func_000C2DA8 / addiu $t0, $t0, %lo(...)
    m2c:     func_000C2DA8(0x1E, 3);          <- two of five arguments

That is the dominant SIZE MISMATCH in the automated pass: on a sample of 40
unmatched small rel_duel_eng functions, 21 were size mismatches and most were
SHORTER than the target.

Telling m2c the real prototype fixes it at the source. Arity is derived the same
way scripts/eboot_signatures.py derives it for the engine: a register READ
BEFORE IT IS WRITTEN is an incoming argument, propagated backwards across tail
calls to a fixed point, because a trampoline passes arguments through without
ever reading them.

Engine imports (ehsys_*) get their arity from nids/ehsys_signatures.csv, which
was measured from the engine's own disassembled bodies.
"""
import argparse
import csv
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ARG_REGS = ["$a0", "$a1", "$a2", "$a3", "$t0", "$t1", "$t2", "$t3"]

WRITES = re.compile(
    r"^(addiu|addu|addi|add|and|andi|or|ori|xor|xori|nor|sll|srl|sra|sllv|srlv|srav|"
    r"slt|slti|sltu|sltiu|sub|subu|mul|movn|movz|lui|li|move|"
    r"lb|lbu|lh|lhu|lw|lwl|lwr|lwc1|mfhi|mflo|mfc1|neg|negu|not|seb|seh|"
    r"max|min|ext|ins|clz|clo|rotr)$")
INSN = re.compile(r"\s*/\* [0-9A-F]+ ([0-9A-F]+) [0-9A-F]{8} \*/\s+(\S+)\s*(.*)")


def parse(module):
    """{func: (argc_local, written_args, tail_target_name, returns)}"""
    path = os.path.join(ROOT, "asm", module, "text.s")
    out, cur, written, argc, warg, tail, ret = {}, None, set(), 0, set(), None, 0
    for line in open(path, errors="replace"):
        g = re.match(r"glabel (func_[0-9A-F]+)", line)
        if g:
            cur, written, argc, warg, tail, ret = g.group(1), set(), 0, set(), None, 0
            continue
        if line.startswith("endlabel") and cur:
            out[cur] = (argc, warg, tail, ret)
            cur = None
            continue
        m = INSN.match(line)
        if not m or cur is None:
            continue
        mnem, ops = m.group(2), m.group(3).strip()
        toks = re.findall(r"\$\w+", ops)
        w = bool(WRITES.match(mnem)) and bool(toks)
        for r in toks[(1 if w else 0):]:
            if r in ARG_REGS and r not in written:
                argc = max(argc, ARG_REGS.index(r) + 1)
        if w:
            written.add(toks[0])
            if toks[0] in ARG_REGS:
                warg.add(toks[0])
            if toks[0] == "$v0":
                ret = 1
        if mnem == "j" and ops.startswith("func_"):
            tail = ops.strip()
    return out


def solve(facts):
    """Propagate arity backwards over tail calls to a fixed point."""
    argc = {k: v[0] for k, v in facts.items()}
    for _ in range(50):
        changed = False
        for fn, (_, warg, tail, _) in facts.items():
            if tail not in argc:
                continue
            for i in range(argc[tail]):
                if ARG_REGS[i] not in warg and argc[fn] < i + 1:
                    argc[fn] = i + 1
                    changed = True
        if not changed:
            break
    return argc


def engine_sigs():
    out = {}
    p = os.path.join(ROOT, "nids/ehsys_signatures.csv")
    if os.path.exists(p):
        for r in csv.DictReader(open(p)):
            out["ehsys_" + r["nid"][2:]] = (int(r["argc"]), int(r["returns"]))
    return out


def emit(module):
    facts = parse(module)
    argc = solve(facts)
    lines = ["/* generated by scripts/gen_context.py - do not edit */",
             "typedef signed char s8;", "typedef unsigned char u8;",
             "typedef short s16;", "typedef unsigned short u16;",
             "typedef int s32;", "typedef unsigned int u32;",
             "typedef float f32;", "typedef double f64;"]
    for fn in sorted(facts):
        n = argc[fn]
        ret = "s32" if facts[fn][3] else "void"
        args = ", ".join(["s32"] * n) or "void"
        lines.append(f"{ret} {fn}({args});")
    for name, (n, ret) in sorted(engine_sigs().items()):
        args = ", ".join(["s32"] * n) or "void"
        lines.append(f"{'s32' if ret else 'void'} {name}({args});")
    dst = os.path.join(ROOT, "build/ctx", module + ".h")
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    open(dst, "w").write("\n".join(lines) + "\n")
    return len(facts), dst


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("modules", nargs="*")
    ap.add_argument("--all", action="store_true")
    a = ap.parse_args()
    mods = a.modules
    if a.all:
        mods = sorted(d for d in os.listdir(os.path.join(ROOT, "asm"))
                      if os.path.exists(os.path.join(ROOT, "asm", d, "text.s")))
    for m in mods:
        n, dst = emit(m)
        print(f"{m}: {n} prototypes -> {dst}")


if __name__ == "__main__":
    main()
