#!/usr/bin/env python3
"""
First-pass survey of one gmodule PRX: generate a section-accurate splat config,
split it, and write docs/modules/<name>.md summarising what the module is and
where the cheap matching targets are.

Usage:
    scripts/module_survey.py rel_gallery            # config + split + doc
    scripts/module_survey.py rel_gallery --no-split # regenerate the doc only

Everything it emits is derived mechanically from the PRX (readelf section
table, the disassembly splat produces, and the printable strings in .data), so
it can be re-run at any time; the hand-written analysis in src/*.c is never
touched.

Section layout handling mirrors config/rel_movie_viewer.yaml: `header` is its
own top-level segment (splat's linker-script generator groups bin subsegments
inside a code segment into the DATA block, which would emit them after .text),
.text and .sceStub.text stay in ONE contiguous code segment starting at file
0x54 / vram 0x0 so that func_XXXXXXXX names are "byte offset from the start of
the code segment", and everything after the last SHF_ALLOC section is one
`elf_meta` blob (section header table, .rel.*, .shstrtab, .comment).
"""
import os
import re
import subprocess
import sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GMODULE = os.path.join(ROOT, "iso_extracted/PSP_GAME/USRDIR/gmodule")

# sections merged into a single named bin blob, in file order
BIN_GROUPS = [
    ("lib_tables", (".lib.ent.top", ".lib.ent", ".lib.ent.btm",
                    ".lib.stub.top", ".lib.stub", ".lib.stub.btm")),
    ("module_info", (".rodata.sceModuleInfo", ".rodata.sceResident")),
    ("sceNid", (".rodata.sceNid",)),
    ("sceVstub", (".rodata.sceVstub",)),
    ("data", (".data",)),
]


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True, **kw).stdout


def read_sections(prx):
    """[(name, type, addr, off, size)] in file order, from readelf -SW."""
    out = sh(f"readelf -SW {prx}")
    secs = []
    for line in out.splitlines():
        m = re.match(r"\s*\[\s*\d+\]\s+(\S+)\s+(\S+)\s+([0-9a-f]+)\s+([0-9a-f]+)\s+([0-9a-f]+)", line)
        if m and m.group(1) != "NULL":
            name, typ, addr, off, size = m.groups()
            secs.append((name, typ, int(addr, 16), int(off, 16), int(size, 16)))
    return secs


def alloc_sections(secs):
    """Loaded sections with real file bytes, in file order."""
    return sorted([s for s in secs if s[1] == "PROGBITS" and s[4] > 0 and
                   not s[0].startswith(".rel") and s[0] != ".comment" and s[0] != ".shstrtab"],
                  key=lambda s: s[3])


def gen_config(name, prx, secs):
    alloc = alloc_sections(secs)
    by_name = {s[0]: s for s in alloc}
    text = by_name[".text"]
    stub = by_name.get(".sceStub.text")
    size = os.path.getsize(prx)
    sha1 = sh(f"sha1sum {prx}").split()[0]

    # bin blobs: every alloc section after the code, grouped
    tail = [s for s in alloc if s[0] not in (".text", ".sceStub.text")]
    blobs = []
    for group, members in BIN_GROUPS:
        hits = [s for s in tail if s[0] in members]
        if hits:
            blobs.append((min(h[3] for h in hits), group, hits))
    for s in tail:  # anything the groups above did not claim
        if not any(s[0] in members for _, members in BIN_GROUPS):
            blobs.append((s[3], s[0].strip(".").replace(".", "_"), [s]))
    blobs.sort()

    last_alloc_end = max(s[3] + s[4] for s in alloc)

    lines = [
        f"# splat config for {name}.prx — full file coverage.",
        "#",
        "# Generated by scripts/module_survey.py; see config/rel_movie_viewer.yaml",
        "# for the hand-written original this mirrors, including the two gotchas",
        "# encoded here: `header` must be its own top-level segment (splat groups",
        "# bin subsegments of a code segment into the DATA block, i.e. after .text),",
        "# and .text + .sceStub.text must stay in ONE contiguous code segment based",
        "# at file 0x54 / vram 0x0 so func_XXXXXXXX names are offsets from the start",
        "# of the code segment.",
        "#",
        "# Section layout (`readelf -SW`, file offsets):",
    ]
    for s in alloc:
        lines.append(f"#   0x{s[3]:06X}-0x{s[3]+s[4]:06X}  {s[0]:<24} (0x{s[4]:X})")
    lines += [
        f"#   0x{last_alloc_end:06X}-0x{size:06X}  section header table + .rel.* + .shstrtab + .comment",
        "#",
        f"# Ranges sum to 0x{size:X} == {size} == the file's exact size.",
        "",
        f"name: {name}",
        f"sha1: {sha1}",
        "options:",
        "  platform: psp",
        f"  basename: {name}",
        "  base_path: ..",
        f"  target_path: iso_extracted/PSP_GAME/USRDIR/gmodule/{name}.prx",
        f"  asm_path: asm/{name}",
        f"  ld_script_path: build/{name}.ld",
        "  compiler: GCC          # placeholder to drive the disassembler; the game uses MWCC (see docs/06)",
        "  find_file_boundaries: True",
        '  section_order: [".text", ".data", ".rodata", ".bss"]',
        "",
        "segments:",
        f"  - [0x0, bin, header]   # ELF header + program headers, file 0x0-0x{text[3]:X}",
        f"  - name: {name}",
        "    type: code",
        f"    start: 0x{text[3]:X}",
        f"    vram: 0x{text[2]:X}",
        "    subsegments:",
        f"      - [0x{text[3]:X}, asm, text]          # vram 0x{text[2]:X}-0x{text[2]+text[4]:X}: the code to decompile",
    ]
    if stub:
        lines.append(
            f"      - [0x{stub[3]:X}, asm, sceStub_text]  # vram 0x{stub[2]:X}-0x{stub[2]+stub[4]:X}: import-stub trampolines"
        )
    for off, group, hits in blobs:
        names = " + ".join(h[0] for h in hits)
        lines.append(f"      - [0x{off:X}, bin, {group}]   # {names}")
    lines += [
        f"      - [0x{last_alloc_end:X}, bin, elf_meta]   # section header table + .rel.* + .shstrtab + .comment",
        f"  - [0x{size:X}]   # sentinel: total file size",
        "",
    ]
    path = os.path.join(ROOT, "config", f"{name}.yaml")
    open(path, "w").write("\n".join(lines))
    return path, size, sha1, alloc


def run_splat(name):
    """splat is run from config/ because the configs use base_path: .. — it
    rewrites include/include_asm.h's include paths as a side effect, so the
    caller restores that file afterwards."""
    r = subprocess.run(
        f". {ROOT}/.venv/bin/activate && cd {ROOT}/config && splat split {name}.yaml",
        shell=True, capture_output=True, text=True, executable="/bin/bash")
    subprocess.run(f"cd {ROOT} && git checkout -- include/include_asm.h 2>/dev/null",
                   shell=True, capture_output=True)
    tail = [l.strip() for l in (r.stdout + r.stderr).splitlines()
            if "in defined segments" in l or "unknown" in l or "rror" in l]
    return r.returncode == 0, tail[-4:]


def scan_text(name):
    """Walk splat's text.s once: function sizes, call targets, referenced syms."""
    path = os.path.join(ROOT, "asm", name, "text.s")
    if not os.path.exists(path):
        return None
    funcs = []          # (vram, size_words)
    calls = Counter()   # callee -> count
    syms = Counter()    # D_/jtbl_ symbol -> count
    entry_refs = []     # %hi(func_...) inside func_00000000
    cur = None
    words = 0
    in_entry = False
    for line in open(path, errors="replace"):
        m = re.match(r"glabel (func_[0-9A-F]+)", line)
        if m:
            cur = int(m.group(1)[5:], 16)
            in_entry = cur == 0
            words = 0
            continue
        if line.startswith("endlabel"):
            if cur is not None:
                funcs.append((cur, words))
            cur = None
            continue
        if cur is None:
            continue
        if re.match(r"\s*/\* [0-9A-F]+ ", line):
            words += 1
        m = re.search(r"\b(?:jal|j)\s+(func_[0-9A-F]+)", line)
        if m:
            calls[int(m.group(1)[5:], 16)] += 1
        for s in re.findall(r"\b(D_[0-9A-F]+|jtbl_[0-9A-F]+)\b", line):
            syms[s] += 1
        if in_entry:
            for s in re.findall(r"%hi\((func_[0-9A-F]+)\)", line):
                entry_refs.append(s)
    return {"funcs": funcs, "calls": calls, "syms": syms, "entry_refs": entry_refs}


def strings_in(prx, off, size, minlen=4, limit=60):
    """Printable runs in a file range, as (vram, text)."""
    data = open(prx, "rb").read()[off:off + size]
    out = []
    cur, start = b"", 0
    for i, b in enumerate(data + b"\0"):
        if 0x20 <= b < 0x7F:
            if not cur:
                start = i
            cur += bytes([b])
        else:
            if len(cur) >= minlen:
                out.append((off + start - 0x54, cur.decode()))
            cur = b""
    return out[:limit]


def write_doc(name, prx, size, sha1, alloc, split_ok, split_log, scan):
    by_name = {s[0]: s for s in alloc}
    text = by_name[".text"]
    stub = by_name.get(".sceStub.text")
    data = by_name.get(".data")
    info = by_name.get(".rodata.sceResident")
    nid = by_name.get(".rodata.sceNid")

    libs = []
    if info:
        libs = [s for _, s in strings_in(prx, info[3], info[4], 3, 40)
                if re.match(r"^[A-Za-z_][A-Za-z0-9_.]*$", s)]

    L = [f"# {name}.prx — module survey", "",
         "First-pass, mechanically generated by `scripts/module_survey.py`",
         "(section table + splat disassembly + printable strings). Nothing here is",
         "hand-verified; it exists so the module can be sized up without opening it.",
         "", "## Identity", "",
         "| | |", "|---|---|",
         f"| file size | {size} bytes (0x{size:X}) |",
         f"| sha1 | `{sha1}` |",
         f"| .text | 0x{text[4]:X} bytes |",
         f"| import stubs | {stub[4] // 8 if stub else 0} (.sceStub.text 0x{stub[4]:X}) |",
         (f"| .data | 0x{data[4]:X} bytes |" if data else "| .data | — |"),
         (f"| NID table | 0x{nid[4]:X} bytes ({nid[4] // 4} entries) |" if nid else "| NID table | — |"),
         ]
    if libs:
        L += ["", "Library names in `.rodata.sceResident` (this module's export name",
              "first, then the libraries it imports):", ""]
        L += [f"- `{s}`" for s in libs]

    if split_log:
        L += ["", "splat coverage: " + "; ".join(split_log)]

    L += ["", "## Sections", "", "| section | file offset | vram | size |", "|---|---|---|---|"]
    for s in alloc:
        L.append(f"| `{s[0]}` | 0x{s[3]:06X} | 0x{s[2]:06X} | 0x{s[4]:X} |")

    L += ["", "## Code", ""]
    if not scan:
        L += [f"splat did not produce `asm/{name}/text.s`"
              f"{' (split failed)' if not split_ok else ''}; log tail:", "",
              "```", *split_log, "```"]
    else:
        funcs = scan["funcs"]
        sizes = sorted((w for _, w in funcs), reverse=True)
        tiny = [f for f in funcs if f[1] <= 16]
        stub_base = text[2] + text[4]
        imports = Counter({k: v for k, v in scan["calls"].items() if k >= stub_base})
        L += [f"- **{len(funcs)} functions** in 0x{text[4]:X} bytes of `.text`",
              "- largest: " + ", ".join(f"`func_{v:08X}` ({w} words)"
                                        for v, w in sorted(funcs, key=lambda f: -f[1])[:5]),
              f"- {len(tiny)} functions are <= 16 words — the cheap first targets:",
              "  " + ", ".join(f"`func_{v:08X}`({w})" for v, w in sorted(tiny)[:20]) +
              (" ..." if len(tiny) > 20 else ""),
              f"- median function size: {sizes[len(sizes) // 2] if sizes else 0} words",
              f"- distinct import stubs called from `.text`: {len(imports)}",
              ]
        if imports:
            L += ["- most-called imports: " +
                  ", ".join(f"`func_{k:08X}`({v}x)" for k, v in imports.most_common(8))]
        if scan["entry_refs"]:
            L += ["", "`func_00000000` is the module entry point; it registers "
                  + ", ".join(f"`{s}`" for s in scan["entry_refs"]) + "."]
        jt = [s for s in scan["syms"] if s.startswith("jtbl_")]
        if jt:
            L += ["", "Jump tables referenced by the code (they live in `.data`): "
                  + ", ".join(f"`{s}`" for s in sorted(jt)) + "."]
        dsyms = sorted(s for s in scan["syms"] if s.startswith("D_"))
        if data:
            data_end_vram = data[2] + data[4]
            bss = [s for s in dsyms if int(s[2:], 16) >= data_end_vram]
            L += ["", f"Globals referenced by the code: {len(dsyms)} distinct symbols, "
                  f"{len(bss)} of them past the end of `.data` (vram 0x{data_end_vram:X}), "
                  "i.e. `.bss` state."]

    if data:
        strs = strings_in(prx, data[3], data[4])
        if strs:
            L += ["", "## Strings in `.data`", "",
                  "(vram address, first 60 found — the fastest read on what the module does)",
                  "", "```"]
            L += [f"0x{v:06X}  {t}" for v, t in strs]
            L += ["```"]

    L += ["", "## Next steps", "",
          f"1. `splat split config/{name}.yaml` (already run; `asm/{name}/` is gitignored)",
          f"2. m2c or hand-decompile the <= 16-word functions listed above into `src/{name}.c`",
          "3. verify with `scripts/mwcc_build.sh` + `scripts/mwcc_diff.py` "
          "(MWCC 1.3 SP7, `-O4,s -sdatathreshold 0`)",
          "4. read `src/rel_movie_viewer.c` and `src/rel_html_view.c` headers first — every",
          "   MWCC codegen lever found so far is documented there.",
          ""]

    path = os.path.join(ROOT, "docs", "modules", f"{name}.md")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w").write("\n".join(L))
    return path


def main():
    name = sys.argv[1]
    do_split = "--no-split" not in sys.argv
    prx = os.path.join(GMODULE, f"{name}.prx")
    secs = read_sections(prx)
    cfg, size, sha1, alloc = gen_config(name, prx, secs)
    ok, log = (run_splat(name) if do_split else (True, []))
    scan = scan_text(name)
    doc = write_doc(name, prx, size, sha1, alloc, ok, log, scan)
    print(f"{name}: config={os.path.relpath(cfg, ROOT)} doc={os.path.relpath(doc, ROOT)} "
          f"split={'ok' if ok else 'FAILED'} funcs={len(scan['funcs']) if scan else 0}")


if __name__ == "__main__":
    main()
