/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_GALLERY_H
#define GLOBALS_REL_GALLERY_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 12 globals with a type the binary determines */
extern f32 D_00009A08;
extern f32 D_00009A0C;
extern f32 D_00009A10;
extern s32 D_00009D74;
extern s32 D_00009D78;
extern s32 D_00009D7C;
extern s32 D_00009D80;
extern s32 D_00009D84;
extern s32 D_00009D88;
extern s32 D_0000A2F4;
extern s32 D_0000A2F8;
extern s32 D_0000A84C;

/* 44 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_00009854; */
/* extern ? D_00009858; */
/* extern ? D_00009898; */
/* extern ? D_0000989C; */
/* extern ? D_000098A0; */
/* extern ? D_000099E8; */
/* extern ? D_00009A00; */
/* extern ? D_00009A14; */
/* extern ? D_00009A18; */
/* extern ? D_00009D8C; */
/* extern ? D_0000A030; */
/* extern ? D_0000A034; */
/* extern ? D_0000A230; */
/* extern ? D_0000A2FC; */
/* extern ? D_0000A308; */
/* extern ? D_0000A318; */
/* extern ? D_0000A39C; */
/* extern ? D_0000A414; */
/* extern ? D_0000A538; */
/* extern ? D_0000A53C; */
/* extern ? D_0000A778; */
/* extern ? D_0000A77C; */
/* extern ? D_0000A790; */
/* extern ? D_0000A794; */
/* extern ? D_0000A7A0; */
/* extern ? D_0000A7AC; */
/* extern ? D_0000A7B8; */
/* extern ? D_0000A7C8; */
/* extern ? D_0000A7E0; */
/* extern ? D_0000A7F8; */
/* extern ? D_0000A804; */
/* extern ? D_0000A810; */
/* extern ? D_0000A840; */
/* extern ? D_0000A850; */
/* extern ? D_30A880; */
/* extern ? D_70A880; */
/* extern ? func_00000188; */
/* extern ? func_00000228; */
/* extern ? func_00000314; */
/* extern ? func_00000344; */
/* extern ? func_000007B4; */
/* extern ? func_000007FC; */
/* extern ? func_00003CA8; */
/* extern ? func_000041DC; */

#endif /* GLOBALS_REL_GALLERY_H */
