/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_HTML_VIEW_H
#define GLOBALS_REL_HTML_VIEW_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 2 globals with a type the binary determines */
extern s32 g_heap_ptr;
extern s32 g_state;

/* 10 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? func_00000034; */
/* extern ? func_00000084; */
/* extern ? g_dl_dir_buf; */
/* extern ? g_heap; */
/* extern ? g_html_param; */
/* extern ? g_module_reg; */
/* extern ? g_url_buf; */
/* extern ? jtbl_00005E34; */
/* extern ? s_download_url; */
/* extern ? s_savedata_dir; */

#endif /* GLOBALS_REL_HTML_VIEW_H */
