/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_DUEL_ENG_H
#define GLOBALS_REL_DUEL_ENG_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 576 globals with a type the binary determines */
extern s16 D_000241C8;
extern u8 D_00024249;
extern s32 D_00024268;
extern s32 D_0002428C;
extern s8 D_0002428F;
extern s16 D_00024BC4;
extern u16 D_00024BC6;
extern s16 D_00024BC8;
extern s16 D_00024BCA;
extern s32 D_00024BCC;
extern s32 D_00024BD0;
extern u8 D_00024D63;
extern s32 D_00024F4C;
extern s32 D_00024F54;
extern u16 D_00024F60;
extern s32 D_00024F88;
extern s32 D_00024F8C;
extern s32 D_00024F90;
extern s32 D_00024F94;
extern s32 D_00024F98;
extern s32 D_00024F9C;
extern s32 D_00024FA0;
extern s32 D_00024FA4;
extern s16 D_00024FC8;
extern s16 D_00024FCA;
extern u8 D_0002A7AC;
extern u8 D_0002A7F2;
extern u16 D_00302704;
extern u16 D_00321028;
extern u16 D_00321278;
extern f32 D_00325918;
extern f32 D_00325920;
extern f32 D_00325928;
extern f32 D_0032592C;
extern f32 D_00325BD0;
extern f32 D_00325BD8;
extern f32 D_00325BE0;
extern f32 D_00325BE8;
extern f32 D_00325BF0;
extern f32 D_00325BF4;
extern f32 D_00325BF8;
extern f32 D_00325C00;
extern f32 D_00325C08;
extern f32 D_00325C10;
extern f32 D_00325C18;
extern f32 D_00325C1C;
extern f32 D_00325C20;
extern f32 D_00325C28;
extern f32 D_00325C30;
extern f32 D_00325C34;
extern f32 D_00325C38;
extern f32 D_00325C40;
extern f32 D_00325C48;
extern f32 D_00325C50;
extern s32 D_00325C54;
extern s32 D_00325C58;
extern s32 D_00325C5C;
extern s32 D_00325C60;
extern s32 D_00325C64;
extern s32 D_00325C68;
extern s32 D_00325C6C;
extern s32 D_00325C70;
extern s32 D_00325C74;
extern s32 D_00325C78;
extern s32 D_00325C7C;
extern s32 D_00325C80;
extern f32 D_00325C90;
extern f32 D_00325C98;
extern f32 D_00325CA0;
extern f32 D_00325CA8;
extern f32 D_00325CB0;
extern f32 D_00325CB8;
extern s32 D_00325CC0;
extern s32 D_00325CC4;
extern s32 D_00325D30;
extern s32 D_00325D3C;
extern s32 D_00325D44;
extern s32 D_00325D48;
extern s32 D_00325D4C;
extern s32 D_00325D50;
extern s32 D_00325D54;
extern s32 D_00325D58;
extern s32 D_00325D5C;
extern s32 D_00325D60;
extern s32 D_00325D64;
extern s32 D_00325DE0;
extern s32 D_00325DE4;
extern s32 D_00325DE8;
extern s32 D_00325DEC;
extern s32 D_00325DF0;
extern s32 D_00325DF4;
extern s32 D_00325DF8;
extern s32 D_00325DFC;
extern s32 D_00325E00;
extern s32 D_00325E04;
extern s8 D_003266D5;
extern u8 D_003268DC;
extern s32 D_003268E0;
extern s32 D_003268E4;
extern s32 D_003268E8;
extern s32 D_003268EC;
extern s32 D_003268F0;
extern s32 D_003268F4;
extern s32 D_00326908;
extern s32 D_0032690C;
extern s32 D_003269CC;
extern s32 D_00326C0C;
extern s32 D_00326C10;
extern s32 D_00326C14;
extern s32 D_00326E80;
extern u16 D_00326EEC;
extern u16 D_00326F1A;
extern u16 D_00326F1C;
extern u16 D_00326F1E;
extern u16 D_00326F20;
extern u16 D_00326F24;
extern u16 D_00326F26;
extern u16 D_00326F28;
extern s32 D_00326F58;
extern s16 D_00326F5C;
extern s16 D_00326F5E;
extern s32 D_00326F60;
extern s32 D_00326F64;
extern s32 D_00326F68;
extern s32 D_00326F6C;
extern s32 D_00326F70;
extern s16 D_0032767C;
extern u16 D_00327680;
extern u16 D_00327682;
extern s32 D_00327684;
extern s32 D_00327688;
extern s32 D_0032768C;
extern s32 D_00327690;
extern u16 D_00327694;
extern u16 D_00327696;
extern s32 D_0032777C;
extern s32 D_00327780;
extern s16 D_00327784;
extern s16 D_00327786;
extern s16 D_00327788;
extern s8 D_0032BC89;
extern s8 D_0032BC8A;
extern u8 D_0032BC8B;
extern u16 D_0032BC8E;
extern f32 D_0032BC90;
extern f32 D_0032BC98;
extern f32 D_0032BCA0;
extern s16 D_0032BCA6;
extern s32 D_0032BCA8;
extern s8 D_0034B0B9;
extern u8 D_0034B0BB;
extern u16 D_0034B0BC;
extern u16 D_0034B0BE;
extern s32 D_0034B0C4;
extern s32 D_0034B0C8;
extern s32 D_0034B0CC;
extern s16 D_0034B0D0;
extern s16 D_0034B0D2;
extern u16 D_0034B124;
extern u16 D_0034B134;
extern u16 D_0034B144;
extern u16 D_0034B154;
extern u16 D_0034B164;
extern u16 D_0034B174;
extern u16 D_0034B184;
extern u16 D_0034B194;
extern u16 D_0034B1BA;
extern f32 D_0034B1BC;
extern f32 D_0034B1C0;
extern f32 D_0034B1C8;
extern f32 D_0034B1CC;
extern f32 D_0034B1D0;
extern f32 D_0034B1D8;
extern f32 D_0034B1DC;
extern f32 D_0034B1E0;
extern s32 D_0034B1E8;
extern s8 D_0034B1EB;
extern s32 D_0034B1EC;
extern s8 D_0034B1EF;
extern s16 D_0034B218;
extern u8 D_0034B220;
extern u8 D_0034B221;
extern u8 D_0034B223;
extern u8 D_0034B22C;
extern s16 D_0034B232;
extern s16 D_0034BB18;
extern s16 D_0034BB1A;
extern s16 D_0034BB1C;
extern s16 D_0034BB1E;
extern s16 D_0034BB26;
extern u8 D_0034BB3F;
extern s16 D_0034BCC0;
extern s16 D_0034BCC2;
extern s16 D_0034BCC4;
extern s16 D_0034BCC6;
extern s16 D_0034BCCE;
extern s32 D_0034BE68;
extern s32 D_0034BE6C;
extern s16 D_0034BE70;
extern s16 D_0034BE72;
extern s16 D_0034BE74;
extern s16 D_0034BE76;
extern s16 D_0034BE78;
extern s16 D_0034BE7A;
extern s16 D_0034BE7C;
extern s16 D_0034BE7E;
extern u16 D_0034BE80;
extern u16 D_0034BE82;
extern u16 D_0034BE84;
extern u16 D_0034BE86;
extern u16 D_0034BE88;
extern u16 D_0034BE8A;
extern s8 D_0034BE8D;
extern s8 D_0034BE8E;
extern u8 D_0034BE8F;
extern f32 D_0034BE90;
extern f32 D_0034BE94;
extern f32 D_0034BE98;
extern f32 D_0034BEA0;
extern f32 D_0034BEA4;
extern s32 D_0034BEA8;
extern s32 D_0034BEAC;
extern s32 D_0034BEB0;
extern s32 D_0034BEB4;
extern s32 D_0034BEDC;
extern s32 D_0034BEE0;
extern s16 D_0034BFA4;
extern s16 D_0034BFA6;
extern s16 D_0034BFA8;
extern s16 D_0034BFAA;
extern s32 D_0034BFAC;
extern s32 D_0034BFB0;
extern s32 D_0034BFB4;
extern s32 D_0034BFB8;
extern s32 D_0034BFBC;
extern s32 D_0034BFC0;
extern s8 D_0034BFC4;
extern u8 D_0034BFC5;
extern u8 D_0034BFC6;
extern s16 D_0034BFC8;
extern u16 D_0034BFCA;
extern u16 D_0034BFCC;
extern u16 D_0034BFCE;
extern s32 D_0034BFD0;
extern s32 D_0034BFD4;
extern s32 D_0034BFD8;
extern s32 D_0034BFDC;
extern u16 D_0034BFE0;
extern u16 D_0034BFE2;
extern s16 D_0034C0C8;
extern s16 D_0034C0CA;
extern s32 D_0034C0CC;
extern s32 D_0034C0D0;
extern s16 D_0034C0D4;
extern u16 D_0034C0D6;
extern u16 D_0034C0D8;
extern u16 D_0034C0DA;
extern s32 D_0034C0DC;
extern s16 D_0034C0E0;
extern s16 D_0034C0E2;
extern s16 D_0034C0E4;
extern u16 D_0034C0E6;
extern s16 D_0034C19C;
extern u16 D_0034C19E;
extern u16 D_0034C1A0;
extern s32 D_0034C1A4;
extern s16 D_0034C1A8;
extern s16 D_0034C1AA;
extern s16 D_0034C1AC;
extern u16 D_0034C1AE;
extern s32 D_0034C564;
extern s16 D_0034C634;
extern u16 D_0034C636;
extern s32 D_0034C6D0;
extern s32 D_0034C6D4;
extern s32 D_0034C6D8;
extern s32 D_0034C6DC;
extern s32 D_0034C6E0;
extern s32 D_0034C6EC;
extern s32 D_0034C6F4;
extern s32 D_0034C6F8;
extern s32 D_0034C6FC;
extern s32 D_0034C700;
extern s32 D_0034C704;
extern s32 D_0034C70C;
extern s32 D_0034C728;
extern s32 D_0034C730;
extern s32 D_0034C734;
extern s32 D_0034C738;
extern s32 D_0034C73C;
extern s32 D_0034C744;
extern s32 D_0034C748;
extern s32 D_0034C74C;
extern s32 D_0034C758;
extern s32 D_0034C774;
extern s32 D_0034C77C;
extern s32 D_0034C780;
extern s32 D_0034C784;
extern s32 D_0034C788;
extern s32 D_0034C790;
extern s32 D_0034C79C;
extern s32 D_0034C7A4;
extern s32 D_0034C7B0;
extern s32 D_0034C7E0;
extern s32 D_0034C7E4;
extern u16 D_0034C810;
extern u16 D_0034C812;
extern u16 D_0034C814;
extern u16 D_0034C816;
extern u16 D_0034C818;
extern u16 D_0034C81A;
extern u16 D_0034C81C;
extern s32 D_0034CA10;
extern s32 D_0034CA14;
extern s32 D_0034CA18;
extern s32 D_0034CA1C;
extern s32 D_0034CA20;
extern s32 D_0034CA24;
extern s32 D_0034CA30;
extern s32 D_0034CA34;
extern s32 D_0034CA38;
extern s32 D_0034CA3C;
extern s32 D_0034CA40;
extern s32 D_0034CA44;
extern s32 D_0034CA48;
extern u16 D_0034CA4C;
extern u16 D_0034CA4E;
extern u16 D_0034CA50;
extern u16 D_0034CA52;
extern s32 D_0034CA54;
extern s32 D_0034CA58;
extern s32 D_0034CA5C;
extern s32 D_0034CA60;
extern s32 D_0034D42C;
extern s32 D_0034D430;
extern s32 D_0034D434;
extern s32 D_0034D438;
extern s32 D_0034D43C;
extern s32 D_0034D540;
extern s32 D_0034D544;
extern s32 D_0034D548;
extern s32 D_0034D54C;
extern s32 D_0034D550;
extern s32 D_0034D554;
extern s32 D_0034D560;
extern s32 D_0034D564;
extern s32 D_0034D568;
extern s32 D_0034D56C;
extern s32 D_0034D570;
extern s32 D_0034D574;
extern s32 D_0034D578;
extern s32 D_0034D57C;
extern s32 D_0034D580;
extern s32 D_0034D584;
extern s32 D_0034D588;
extern s32 D_0034D58C;
extern s32 D_0034D590;
extern s32 D_0034D594;
extern u8 D_0034D598;
extern s32 D_0034D5B8;
extern s32 D_0034D638;
extern s32 D_0034D63C;
extern s32 D_0034D640;
extern s32 D_0034D644;
extern s32 D_0034D654;
extern s32 D_0034D658;
extern s32 D_0034D660;
extern s32 D_0034D664;
extern s32 D_0034D668;
extern u16 D_0034D696;
extern u16 D_0034D69E;
extern u16 D_0034D6D0;
extern u16 D_0034D6D6;
extern u16 D_0034D6D8;
extern u16 D_0034D6DA;
extern u16 D_0034D6DC;
extern u16 D_0034D6DE;
extern u16 D_0034D6E0;
extern u16 D_0034D6E2;
extern u16 D_0034D6E4;
extern u16 D_0034D6E6;
extern u16 D_0034D6E8;
extern u16 D_0034D6EA;
extern u16 D_0034D6EC;
extern u16 D_0034D6EE;
extern u16 D_0034D6F0;
extern u16 D_0034D6F2;
extern u16 D_0034D6F4;
extern u16 D_0034D6F6;
extern u16 D_0034D6F8;
extern u16 D_0034D6FA;
extern u16 D_0034D6FC;
extern u16 D_0034D6FE;
extern u16 D_0034D700;
extern u16 D_0034D702;
extern u16 D_0034D704;
extern u16 D_0034D712;
extern u16 D_0034D726;
extern u16 D_0034D728;
extern u16 D_0034D72C;
extern u16 D_0034D72E;
extern s32 D_0034DF30;
extern s32 D_0034DF34;
extern s32 D_0034DF38;
extern s32 D_0034DF3C;
extern u16 D_0034DF40;
extern u8 D_0034DF41;
extern u16 D_0034DF42;
extern s32 D_0034DF44;
extern s32 D_0034DF48;
extern s32 D_0034DF4C;
extern s32 D_0034DF50;
extern s32 D_0034DF54;
extern u16 D_0034DF58;
extern u8 D_0034DF59;
extern u16 D_0034DF5A;
extern u16 D_0034DF5C;
extern u16 D_0034DF60;
extern u16 D_0034DF64;
extern s32 D_0034E660;
extern s32 D_0034E664;
extern s32 D_0034E668;
extern s32 D_0034E66C;
extern s32 D_0034E670;
extern s32 D_0034E67C;
extern s32 D_0034E680;
extern u16 D_0034E75C;
extern u16 D_0034E764;
extern u16 D_0034E77A;
extern s32 D_0034E780;
extern s32 D_0034F19C;
extern s32 D_0034F1A0;
extern s32 D_0034F1A4;
extern s32 D_0034F1A8;
extern s32 D_0034F1AC;
extern s32 D_0034F1B8;
extern s32 D_0034F1BC;
extern u16 D_0034F298;
extern u16 D_0034F2A0;
extern u16 D_0034F2B6;
extern s32 D_0034F2BC;
extern s32 D_0034FCDC;
extern s32 D_0034FCE0;
extern s32 D_0034FCE4;
extern s32 D_0034FCE8;
extern s32 D_0034FCEC;
extern s32 D_0034FCF0;
extern s32 D_0034FCFC;
extern s32 D_0034FD00;
extern s32 D_0034FD04;
extern u8 D_00350D14;
extern s32 D_00351708;
extern s32 D_00351710;
extern s32 D_00351718;
extern s32 D_00351720;
extern s32 D_00351728;
extern s32 D_00351730;
extern s32 D_00351734;
extern s32 D_00351738;
extern s32 D_0035173C;
extern s32 D_00351740;
extern s32 D_00351744;
extern s32 D_00351748;
extern s32 D_0035174C;
extern s32 D_00351750;
extern s32 D_00351754;
extern s32 D_00351758;
extern s32 D_0035175C;
extern s32 D_00351760;
extern s32 D_00351764;
extern s32 D_00351768;
extern s32 D_0035176C;
extern s32 D_00351770;
extern s32 D_00351774;
extern s32 D_00351778;
extern s32 D_0035177C;
extern s32 D_00351780;
extern s32 D_00351784;
extern s32 D_0035178C;
extern s32 D_003517A0;
extern s32 D_003517A4;
extern s32 D_003517A8;
extern s32 D_003517AC;
extern s32 D_003517B0;
extern s32 D_003517B4;
extern s32 D_003517C0;
extern s32 D_003517C4;
extern s32 D_003517C8;
extern s32 D_003517DC;
extern s32 D_003517E0;
extern s32 D_003517E4;
extern s32 D_003517E8;
extern s32 D_003517EC;
extern s32 D_003517F0;
extern u16 D_003517F4;
extern u16 D_003517F6;
extern u16 D_003517F8;
extern u16 D_003517FA;
extern u16 D_003517FC;
extern u16 D_003517FE;
extern u16 D_00351800;
extern u16 D_00351802;
extern u16 D_00351804;
extern u16 D_00351806;
extern u16 D_00351808;
extern u16 D_0035180A;
extern u16 D_0035180C;
extern u16 D_0035180E;
extern u16 D_00351810;
extern u16 D_00351812;
extern u16 D_00351814;
extern s32 D_00351824;
extern s32 D_00351828;
extern s32 D_0035182C;
extern s32 D_00351830;
extern s32 D_00351834;
extern s32 D_00351838;
extern s32 D_0035183C;
extern s32 D_00351840;
extern u16 D_00351844;
extern u16 D_00351846;
extern u16 D_0035184A;
extern s32 D_0035184C;
extern s32 D_00351850;
extern s32 D_00351854;
extern s32 D_00351858;
extern s32 D_0035185C;
extern u16 D_00351860;
extern u16 D_00351866;
extern u16 D_0035186C;
extern u16 D_0035186E;
extern u16 D_00351870;
extern u16 D_00351872;
extern s32 D_0035187C;
extern s32 D_00351880;
extern s32 D_00351884;
extern s32 D_00351894;
extern s32 D_003518A0;
extern s32 D_003518A4;
extern s32 D_003518A8;
extern s32 D_003518AC;
extern s32 D_003518B0;
extern s32 D_00351904;
extern s32 D_00351908;
extern s32 D_0035190C;
extern s32 D_00351910;
extern s32 D_00351914;
extern s32 D_00351918;
extern s32 D_0035191C;
extern s32 D_00351920;
extern s32 D_00351924;
extern s32 D_00351928;
extern s32 D_00358154;
extern s32 D_00358158;
extern s32 D_0035815C;
extern s32 D_00358160;
extern s32 D_00358164;
extern s32 D_00358168;
extern s32 D_003593CC;
extern s32 D_003593D0;
extern s32 D_003593D4;
extern s32 D_003593D8;
extern s16 D_003593DC;
extern u16 D_003593E0;
extern s32 D_003593E4;
extern s32 D_003593E8;
extern s32 D_003593EC;
extern s32 D_003593F0;
extern s32 D_003593F4;
extern s32 D_003593F8;
extern s32 D_003593FC;
extern s32 D_00359400;
extern s32 D_00359404;
extern s32 D_00359408;
extern s32 D_0035940C;
extern s32 D_00359410;

/* 51 accessed at more than one width — a union, or two
 * structs sharing a base. Decide these by hand before using them. */
/* extern ? D_00024248;   seen as w1, w2 */
/* extern ? D_0002424A;   seen as w1, w2 */
/* extern ? D_0002424C;   seen as w1, w2 */
/* extern ? D_00024250;   seen as w1, w2 */
/* extern ? D_0032BC88;   seen as w1, w4 */
/* extern ? D_0032BC8C;   seen as w1, w4 */
/* extern ? D_0032BCA4;   seen as w1, w2 */
/* extern ? D_0034B0B8;   seen as w1, w2 */
/* extern ? D_0034B0BA;   seen as w1, w2 */
/* extern ? D_0034B0C0;   seen as w2, w4 */
/* extern ? D_0034B1A4;   seen as w1, w2 */
/* extern ? D_0034B1B8;   seen as w1, w2, w4 */
/* extern ? D_0034B222;   seen as w1, w2 */
/* extern ? D_0034BE8C;   seen as w1, w4 */
/* extern ? D_0034C1A2;   seen as w1, w2 */
/* extern ? D_0034C6C8;   seen as w1, w4 */
/* extern ? D_0034C6CC;   seen as w1, w4 */
/* extern ? D_0034C6E4;   seen as w1, w2, w4 */
/* extern ? D_0034C6E8;   seen as w1, w2, w4 */
/* extern ? D_0034C6F0;   seen as w2, w4 */
/* extern ? D_0034D424;   seen as w2, w4 */
/* extern ? D_0034D428;   seen as w2, w4 */
/* extern ? D_0034D558;   seen as w1, w2, w4 */
/* extern ? D_0034D55C;   seen as w1, w2, w4 */
/* extern ? D_0034D648;   seen as w2, w4 */
/* extern ? D_0034D64C;   seen as w2, w4 */
/* extern ? D_0034D650;   seen as w1, w2, w4 */
/* extern ? D_0034D65C;   seen as w2, w4 */
/* extern ? D_0034D6D2;   seen as w1, w2 */
/* extern ? D_0034D6D4;   seen as w1, w2 */
/* extern ? D_0034D72A;   seen as w1, w2 */
/* extern ? D_0034E690;   seen as w2, w4 */
/* extern ? D_0034F1CC;   seen as w2, w4 */
/* extern ? D_0034FCD8;   seen as w2, w4 */
/* extern ? D_0034FCF4;   seen as w2, w4 */
/* extern ? D_0034FCF8;   seen as w2, w4 */
/* extern ? D_0035170C;   seen as w2, w4 */
/* extern ? D_00351714;   seen as w1, w2, w4 */
/* extern ? D_0035171C;   seen as w2, w4 */
/* extern ? D_00351724;   seen as w2, w4 */
/* extern ? D_0035172C;   seen as w2, w4 */
/* extern ? D_00351788;   seen as w2, w4 */
/* extern ? D_003517B8;   seen as w2, w4 */
/* extern ? D_003517BC;   seen as w2, w4 */
/* extern ? D_003517CC;   seen as w1, w2, w4 */
/* extern ? D_003517D0;   seen as w2, w4 */
/* extern ? D_003517D4;   seen as w2, w4 */
/* extern ? D_003517D8;   seen as w1, w4 */
/* extern ? D_00351848;   seen as w1, w2 */
/* extern ? D_00351862;   seen as w1, w2 */
/* extern ? D_0035186A;   seen as w1, w2 */

/* 1654 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_002FC784; */
/* extern ? D_002FC9A0; */
/* extern ? D_002FC9DC; */
/* extern ? D_002FCA90; */
/* extern ? D_002FCE48; */
/* extern ? D_002FCFA8; */
/* extern ? D_002FD018; */
/* extern ? D_002FD6C8; */
/* extern ? D_002FD758; */
/* extern ? D_002FDB88; */
/* extern ? D_002FDBA8; */
/* extern ? D_002FDC48; */
/* extern ? D_002FDC64; */
/* extern ? D_002FDC70; */
/* extern ? D_002FDEC4; */
/* extern ? D_002FDF08; */
/* extern ? D_002FDF14; */
/* extern ? D_002FDFB4; */
/* extern ? D_002FE11C; */
/* extern ? D_002FE50C; */
/* extern ? D_002FE5C8; */
/* extern ? D_002FE5EC; */
/* extern ? D_002FE604; */
/* extern ? D_002FE640; */
/* extern ? D_002FE668; */
/* extern ? D_002FE6A8; */
/* extern ? D_002FE6C4; */
/* extern ? D_002FE6F4; */
/* extern ? D_002FE73C; */
/* extern ? D_002FE798; */
/* extern ? D_002FE7DC; */
/* extern ? D_002FE7FC; */
/* extern ? D_002FE938; */
/* extern ? D_002FE994; */
/* extern ? D_002FEB3C; */
/* extern ? D_002FEC0C; */
/* extern ? D_002FEC44; */
/* extern ? D_002FEE84; */
/* extern ? D_002FEED4; */
/* extern ? D_002FEEF8; */
/* extern ? D_002FEF60; */
/* extern ? D_002FEFEC; */
/* extern ? D_002FF008; */
/* extern ? D_002FF024; */
/* extern ? D_002FF054; */
/* extern ? D_002FF0D0; */
/* extern ? D_002FF308; */
/* extern ? D_002FF390; */
/* extern ? D_002FF3E0; */
/* extern ? D_002FF480; */
/* extern ? D_002FF4BC; */
/* extern ? D_002FF4EC; */
/* extern ? D_002FF50C; */
/* extern ? D_002FF5AC; */
/* extern ? D_002FF614; */
/* extern ? D_002FF6A0; */
/* extern ? D_002FF704; */
/* extern ? D_002FF81C; */
/* extern ? D_002FF830; */
/* extern ? D_002FF844; */
/* extern ? D_002FF8AC; */
/* extern ? D_002FFB4C; */
/* extern ? D_002FFDAC; */
/* extern ? D_00300058; */
/* extern ? D_00300094; */
/* extern ? D_003000CC; */
/* extern ? D_00300120; */
/* extern ? D_00300294; */
/* extern ? D_00300380; */
/* extern ? D_003003EC; */
/* extern ? D_00300434; */
/* extern ? D_00300830; */
/* extern ? D_00300AEC; */
/* extern ? D_00300B9C; */
/* extern ? D_00300BA4; */
/* extern ? D_00300BB0; */
/* extern ? D_00300BB8; */
/* extern ? D_00300BE4; */
/* extern ? D_00300C24; */
/* extern ? D_003011C0; */
/* extern ? D_003011CC; */
/* extern ? D_003011D4; */
/* extern ? D_0030140C; */
/* extern ? D_0030180C; */
/* extern ? D_00301AD8; */
/* extern ? D_00301AFC; */
/* extern ? D_00301B40; */
/* extern ? D_00301E34; */
/* extern ? D_00302314; */
/* extern ? D_003023D8; */
/* extern ? D_003023F8; */
/* extern ? D_0030242C; */
/* extern ? D_00302444; */
/* extern ? D_0030245C; */
/* extern ? D_00302508; */
/* extern ? D_00302530; */
/* extern ? D_00302590; */
/* extern ? D_00302648; */
/* extern ? D_00302706; */
/* extern ? D_00302794; */
/* extern ? D_00302798; */
/* extern ? D_0030646C; */
/* extern ? D_003064D0; */
/* extern ? D_00306504; */
/* extern ? D_00306524; */
/* extern ? D_00306A94; */
/* extern ? D_00306AB0; */
/* extern ? D_00306AC8; */
/* extern ? D_00306B18; */
/* extern ? D_0030E060; */
/* extern ? D_00315860; */
/* extern ? D_003194C0; */
/* extern ? D_0031DA08; */
/* extern ? D_0031DA2C; */
/* extern ? D_0031DA60; */
/* extern ? D_0031DAFC; */
/* extern ? D_0031DB10; */
/* extern ? D_0031DB24; */
/* extern ? D_0031DB40; */
/* extern ? D_0031DB60; */
/* extern ? D_0031DBA8; */
/* extern ? D_0031DBAC; */
/* extern ? D_0031DBB4; */
/* extern ? D_0031DBD8; */
/* extern ? D_0031DBF0; */
/* extern ? D_0031DC18; */
/* extern ? D_0031DC20; */
/* extern ? D_0031DC50; */
/* extern ? D_0031DC7C; */
/* extern ? D_0031DC90; */
/* extern ? D_0031DD2C; */
/* extern ? D_0031DD38; */
/* extern ? D_0031DD60; */
/* extern ? D_0031DD84; */
/* extern ? D_0031DD9C; */
/* extern ? D_0031DDC8; */
/* extern ? D_0031DDE0; */
/* extern ? D_0031DDFC; */
/* extern ? D_0031DE18; */
/* extern ? D_0031DE1C; */
/* extern ? D_0031DE28; */
/* extern ? D_0031DE30; */
/* extern ? D_0031DE60; */
/* extern ? D_0031E400; */
/* extern ? D_0031E428; */
/* extern ? D_0031E448; */
/* extern ? D_00320870; */
/* extern ? D_003208F8; */
/* extern ? D_00320B50; */
/* extern ? D_00320C18; */
/* extern ? D_00320CC0; */
/* extern ? D_00320FE0; */
/* extern ? D_003211C4; */
/* extern ? D_003211C6; */
/* extern ? D_003211F8; */
/* extern ? D_00321274; */
/* extern ? D_00322110; */
/* extern ? D_00322168; */
/* extern ? D_003228F0; */
/* extern ? D_00322D88; */
/* extern ? D_00322DB8; */
/* extern ? D_00322DC4; */
/* extern ? D_00322DC8; */
/* extern ? D_00322DCC; */
/* extern ? D_00322DD4; */
/* extern ? D_00322DE4; */
/* extern ? D_00322DE8; */
/* extern ? D_00322DF0; */
/* extern ? D_00322E08; */
/* extern ? D_00322E38; */
/* extern ? D_00322E40; */
/* extern ? D_00322E48; */
/* extern ? D_00322E58; */
/* extern ? D_00322E70; */
/* extern ? D_00322E78; */
/* extern ? D_00322E7C; */
/* extern ? D_00322E84; */
/* extern ? D_00322E90; */
/* extern ? D_00322E98; */
/* extern ? D_00322EA0; */
/* extern ? D_00322EAC; */
/* extern ? D_00322EB4; */
/* extern ? D_00322EC0; */
/* extern ? D_00322ECC; */
/* extern ? D_00322EDC; */
/* extern ? D_00322EE4; */
/* extern ? D_00322EEC; */
/* extern ? D_00322EF0; */
/* extern ? D_00322F00; */
/* extern ? D_00322F40; */
/* extern ? D_00322F4C; */
/* extern ? D_00322F58; */
/* extern ? D_00322F60; */
/* extern ? D_00322F74; */
/* extern ? D_00322F78; */
/* extern ? D_00322FA0; */
/* extern ? D_00322FA4; */
/* extern ? D_00322FAC; */
/* extern ? D_00322FB0; */
/* extern ? D_0032300C; */
/* extern ? D_003231A8; */
/* extern ? D_003231E4; */
/* extern ? D_00323200; */
/* extern ? D_00323228; */
/* extern ? D_00323238; */
/* extern ? D_00323264; */
/* extern ? D_0032330C; */
/* extern ? D_0032334C; */
/* extern ? D_003233D0; */
/* extern ? D_003233DC; */
/* extern ? D_003233E4; */
/* extern ? D_00323404; */
/* extern ? D_00323420; */
/* extern ? D_00323428; */
/* extern ? D_00323450; */
/* extern ? D_00323458; */
/* extern ? D_003234C4; */
/* extern ? D_00323508; */
/* extern ? D_00323524; */
/* extern ? D_0032353C; */
/* extern ? D_00323578; */
/* extern ? D_00323584; */
/* extern ? D_0032358C; */
/* extern ? D_003235A8; */
/* extern ? D_003235D8; */
/* extern ? D_00323624; */
/* extern ? D_00323648; */
/* extern ? D_00323654; */
/* extern ? D_00323658; */
/* extern ? D_0032368C; */
/* extern ? D_003236A4; */
/* extern ? D_003236D8; */
/* extern ? D_003236DC; */
/* extern ? D_003236E8; */
/* extern ? D_003236EC; */
/* extern ? D_00323780; */
/* extern ? D_003237B4; */
/* extern ? D_003237C0; */
/* extern ? D_00323808; */
/* extern ? D_00323848; */
/* extern ? D_0032385C; */
/* extern ? D_00323864; */
/* extern ? D_003238B4; */
/* extern ? D_003238F0; */
/* extern ? D_003238FC; */
/* extern ? D_00323954; */
/* extern ? D_00323960; */
/* extern ? D_0032397C; */
/* extern ? D_003239A8; */
/* extern ? D_003239D8; */
/* extern ? D_003239EC; */
/* extern ? D_003239F0; */
/* extern ? D_00323A1C; */
/* extern ? D_00323A44; */
/* extern ? D_00323A54; */
/* extern ? D_00323A90; */
/* extern ? D_00323AC4; */
/* extern ? D_00323AE0; */
/* extern ? D_00323B24; */
/* extern ? D_00323B38; */
/* extern ? D_00323B44; */
/* extern ? D_00323B74; */
/* extern ? D_00323B88; */
/* extern ? D_00323D7C; */
/* extern ? D_00323D8C; */
/* extern ? D_00323DBC; */
/* extern ? D_00323DD8; */
/* extern ? D_00323DF8; */
/* extern ? D_00323E00; */
/* extern ? D_00323E08; */
/* extern ? D_00323E4C; */
/* extern ? D_00323E5C; */
/* extern ? D_00323E68; */
/* extern ? D_00323E8C; */
/* extern ? D_00323EC0; */
/* extern ? D_00323ECC; */
/* extern ? D_00323F04; */
/* extern ? D_00323F10; */
/* extern ? D_00323F40; */
/* extern ? D_00323F54; */
/* extern ? D_00323F64; */
/* extern ? D_00323F90; */
/* extern ? D_00323FA0; */
/* extern ? D_00323FC8; */
/* extern ? D_00323FE4; */
/* extern ? D_00323FE8; */
/* extern ? D_00323FF0; */
/* extern ? D_00324014; */
/* extern ? D_00324030; */
/* extern ? D_0032403C; */
/* extern ? D_00324048; */
/* extern ? D_00324054; */
/* extern ? D_00324070; */
/* extern ? D_00324074; */
/* extern ? D_0032407C; */
/* extern ? D_00324090; */
/* extern ? D_003240A0; */
/* extern ? D_003240A4; */
/* extern ? D_003240B8; */
/* extern ? D_003240C8; */
/* extern ? D_003240CC; */
/* extern ? D_003240D4; */
/* extern ? D_003240DC; */
/* extern ? D_003240E4; */
/* extern ? D_003240F4; */
/* extern ? D_00324100; */
/* extern ? D_00324140; */
/* extern ? D_00324144; */
/* extern ? D_0032415C; */
/* extern ? D_0032417C; */
/* extern ? D_00324198; */
/* extern ? D_003241C4; */
/* extern ? D_003241EC; */
/* extern ? D_003242A0; */
/* extern ? D_003242A8; */
/* extern ? D_003242DC; */
/* extern ? D_00324340; */
/* extern ? D_003243B4; */
/* extern ? D_003243CC; */
/* extern ? D_003243D4; */
/* extern ? D_003243F0; */
/* extern ? D_00324450; */
/* extern ? D_00324468; */
/* extern ? D_0032446C; */
/* extern ? D_003245C8; */
/* extern ? D_00324620; */
/* extern ? D_003246AC; */
/* extern ? D_00324790; */
/* extern ? D_003247B0; */
/* extern ? D_00324864; */
/* extern ? D_003248C0; */
/* extern ? D_00324914; */
/* extern ? D_00324B1C; */
/* extern ? D_00324B44; */
/* extern ? D_00324E14; */
/* extern ? D_00324E34; */
/* extern ? D_00324E70; */
/* extern ? D_00324EA0; */
/* extern ? D_00324EC0; */
/* extern ? D_00324ECC; */
/* extern ? D_003250E4; */
/* extern ? D_00325104; */
/* extern ? D_00325128; */
/* extern ? D_0032515C; */
/* extern ? D_00325168; */
/* extern ? D_003251A0; */
/* extern ? D_003251C8; */
/* extern ? D_003251DC; */
/* extern ? D_00325210; */
/* extern ? D_00325238; */
/* extern ? D_00325260; */
/* extern ? D_0032526C; */
/* extern ? D_00325298; */
/* extern ? D_003252A4; */
/* extern ? D_003252C0; */
/* extern ? D_003252C8; */
/* extern ? D_003252E4; */
/* extern ? D_003252F0; */
/* extern ? D_003252F8; */
/* extern ? D_00325304; */
/* extern ? D_00325318; */
/* extern ? D_0032532C; */
/* extern ? D_00325340; */
/* extern ? D_00325364; */
/* extern ? D_00325388; */
/* extern ? D_00325390; */
/* extern ? D_003253BC; */
/* extern ? D_003253CC; */
/* extern ? D_003253E4; */
/* extern ? D_003253F8; */
/* extern ? D_0032540C; */
/* extern ? D_0032541C; */
/* extern ? D_00325424; */
/* extern ? D_0032542C; */
/* extern ? D_00325574; */
/* extern ? D_003255A0; */
/* extern ? D_003255CC; */
/* extern ? D_003255E4; */
/* extern ? D_00325608; */
/* extern ? D_0032561C; */
/* extern ? D_00325658; */
/* extern ? D_00325668; */
/* extern ? D_003256B4; */
/* extern ? D_003256C4; */
/* extern ? D_003256CC; */
/* extern ? D_003256D0; */
/* extern ? D_003256D4; */
/* extern ? D_003256F0; */
/* extern ? D_00325708; */
/* extern ? D_0032571C; */
/* extern ? D_00325724; */
/* extern ? D_0032572C; */
/* extern ? D_00325734; */
/* extern ? D_0032573C; */
/* extern ? D_0032574C; */
/* extern ? D_00325768; */
/* extern ? D_00325770; */
/* extern ? D_0032577C; */
/* extern ? D_0032578C; */
/* extern ? D_00325798; */

#endif /* GLOBALS_REL_DUEL_ENG_H */
