/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_SELECT_CARD_H
#define GLOBALS_REL_SELECT_CARD_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 101 globals with a type the binary determines */
extern s16 D_0001D944;
extern s16 D_0001D946;
extern s16 D_0001D948;
extern s16 D_0001D94A;
extern u16 D_0001D9DC;
extern u16 D_0001D9DE;
extern u16 D_0001D9E0;
extern s16 D_0001E4EC;
extern s16 D_0001E4EE;
extern s32 D_0001E4F4;
extern u16 D_0001E4F8;
extern u16 D_0001E4FA;
extern s32 D_0001E500;
extern u16 D_0001E504;
extern u16 D_0001E506;
extern s32 D_0001E50C;
extern u16 D_0001E510;
extern u16 D_0001E512;
extern s32 D_0001E518;
extern u16 D_0001E51C;
extern u16 D_0001E51E;
extern s32 D_0001E524;
extern u16 D_0001E52A;
extern s16 D_0001E540;
extern s16 D_0001E542;
extern u16 D_0001E548;
extern u16 D_0001E54A;
extern u16 D_0001E54C;
extern u16 D_0001E54E;
extern u16 D_0001E554;
extern u16 D_0001E556;
extern u16 D_0001E558;
extern u16 D_0001E55A;
extern s16 D_0001E578;
extern s16 D_0001E57A;
extern s16 D_0001E57C;
extern s16 D_0001E580;
extern s16 D_0001E582;
extern s16 D_0001E584;
extern s16 D_0001E5A4;
extern s16 D_0001E5A6;
extern s32 D_0001E5D0;
extern s32 D_0001E5E0;
extern s32 D_0001E5E4;
extern u16 D_0001E5E8;
extern u16 D_0001E5EA;
extern s32 D_0001E5F8;
extern s32 D_0001E618;
extern u16 D_0001EA2C;
extern s16 D_0001EB50;
extern u8 D_0001EB52;
extern u16 D_0001EB54;
extern s32 D_0001EB58;
extern s32 D_0001EB5C;
extern s32 D_0001EB60;
extern s32 D_0001EB64;
extern s32 D_0001EB74;
extern s32 D_0001EB78;
extern s32 D_0001EB7C;
extern s32 D_0001EB80;
extern u8 D_0001EB84;
extern s32 D_0001EB88;
extern s32 D_0001EB8C;
extern s32 D_0001EB94;
extern s32 D_0001EB98;
extern u8 D_0001EB9C;
extern u16 D_0001EBA0;
extern u16 D_0001EBA2;
extern u16 D_0001EBA4;
extern s32 D_0001EBA8;
extern s32 D_0001EBAC;
extern s32 D_0001EBB4;
extern u8 D_0001EBCC;
extern s32 D_0001EBD0;
extern u8 D_0001EBD4;
extern u16 D_0001EBD6;
extern u16 D_0001EBD8;
extern u16 D_0001EBDA;
extern s16 D_0001EBDC;
extern s32 D_0001EBFC;
extern u8 D_0001EC00;
extern u16 D_0001EC02;
extern u16 D_0001EC04;
extern u16 D_0001EC06;
extern s32 D_0001FC34;
extern u16 D_0001FC38;
extern u16 D_0001FC3A;
extern u16 D_0001FC3C;
extern s32 D_0001FC40;
extern s32 D_0001FC44;
extern s32 D_0001FC48;
extern s32 D_0001FC4C;
extern s32 D_0001FC50;
extern u8 D_0001FC60;
extern s32 D_0001FC64;
extern s32 D_0001FC68;
extern u8 D_0001FC6C;
extern s32 D_0001FC8C;
extern s32 D_0001FE18;
extern s32 D_0001FE1C;
extern s32 D_0002285C;

/* 1 accessed at more than one width — a union, or two
 * structs sharing a base. Decide these by hand before using them. */
/* extern ? D_0001EB90;   seen as w1, w2 */

/* 100 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_0001D700; */
/* extern ? D_0001D7B8; */
/* extern ? D_0001D7BC; */
/* extern ? D_0001D7F4; */
/* extern ? D_0001D800; */
/* extern ? D_0001D820; */
/* extern ? D_0001D878; */
/* extern ? D_0001D894; */
/* extern ? D_0001D8B8; */
/* extern ? D_0001D8C4; */
/* extern ? D_0001D8FC; */
/* extern ? D_0001D94C; */
/* extern ? D_0001D96C; */
/* extern ? D_0001D97C; */
/* extern ? D_0001D99C; */
/* extern ? D_0001D9A4; */
/* extern ? D_0001D9B8; */
/* extern ? D_0001D9E4; */
/* extern ? D_0001DA7C; */
/* extern ? D_0001DAC0; */
/* extern ? D_0001DB00; */
/* extern ? D_0001DB40; */
/* extern ? D_0001DB7C; */
/* extern ? D_0001DBA8; */
/* extern ? D_0001DBC0; */
/* extern ? D_0001DBCC; */
/* extern ? D_0001DBE0; */
/* extern ? D_0001DCA8; */
/* extern ? D_0001DD14; */
/* extern ? D_0001DD24; */
/* extern ? D_0001DD64; */
/* extern ? D_0001DD9C; */
/* extern ? D_0001DDA8; */
/* extern ? D_0001DE58; */
/* extern ? D_0001DE90; */
/* extern ? D_0001DED8; */
/* extern ? D_0001DEE4; */
/* extern ? D_0001DF48; */
/* extern ? D_0001E218; */
/* extern ? D_0001E414; */
/* extern ? D_0001E420; */
/* extern ? D_0001E43C; */
/* extern ? D_0001E448; */
/* extern ? D_0001E450; */
/* extern ? D_0001E494; */
/* extern ? D_0001E4A0; */
/* extern ? D_0001E4A8; */
/* extern ? D_0001E4B0; */
/* extern ? D_0001E4B4; */
/* extern ? D_0001E4B8; */
/* extern ? D_0001E4BC; */
/* extern ? D_0001E4C8; */
/* extern ? D_0001E52C; */
/* extern ? D_0001E55C; */
/* extern ? D_0001E588; */
/* extern ? D_0001E594; */
/* extern ? D_0001E5A8; */
/* extern ? D_0001E5EC; */
/* extern ? D_0001E5FC; */
/* extern ? D_0001E60C; */
/* extern ? D_0001E62C; */
/* extern ? D_0001EA7E; */
/* extern ? D_0001EA88; */
/* extern ? D_0001EB68; */
/* extern ? D_0001EC28; */
/* extern ? D_0001F310; */
/* extern ? D_0001F35C; */
/* extern ? D_0001F434; */
/* extern ? D_0001FC70; */
/* extern ? D_0001FCB0; */
/* extern ? D_0001FCE4; */
/* extern ? D_0001FD16; */
/* extern ? func_0000120C; */
/* extern ? func_000012BC; */
/* extern ? func_000014A8; */
/* extern ? func_00001824; */
/* extern ? func_000018F8; */
/* extern ? func_00001AF4; */
/* extern ? func_00007770; */
/* extern ? func_00007A28; */
/* extern ? func_0000B858; */
/* extern ? func_0000BB34; */
/* extern ? func_0000BCC0; */
/* extern ? func_0000BCEC; */
/* extern ? func_0000BD18; */
/* extern ? func_0000F7A8; */
/* extern ? func_0000FF28; */
/* extern ? func_00010A18; */
/* extern ? func_00010A48; */
/* extern ? func_00010EC4; */
/* extern ? func_00010F4C; */
/* extern ? jtbl_0001D644; */
/* extern ? jtbl_0001D66C; */
/* extern ? jtbl_0001D698; */
/* extern ? jtbl_0001D6B8; */
/* extern ? jtbl_0001D6D4; */
/* extern ? jtbl_0001D708; */
/* extern ? jtbl_0001D734; */
/* extern ? jtbl_0001D760; */
/* extern ? jtbl_0001D788; */

#endif /* GLOBALS_REL_SELECT_CARD_H */
