/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_DUEL_MGR_H
#define GLOBALS_REL_DUEL_MGR_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 84 globals with a type the binary determines */
extern f32 D_0001D0C4;
extern s32 D_0001D784;
extern s16 D_0001DB30;
extern s16 D_0001DB32;
extern s16 D_0001DB34;
extern s16 D_0001DB36;
extern s16 D_0001DB40;
extern s16 D_0001DB42;
extern s16 D_0001DB4C;
extern s16 D_0001DB4E;
extern s16 D_0001DB50;
extern s16 D_0001DB52;
extern s16 D_0001DB54;
extern s16 D_0001DB56;
extern s16 D_0001DF00;
extern s16 D_0001DF02;
extern s16 D_0001DF04;
extern s16 D_0001DF06;
extern s16 D_0001DF08;
extern s16 D_0001DF0A;
extern s16 D_0001DF0C;
extern s16 D_0001DF0E;
extern s16 D_0001DF10;
extern s16 D_0001DF12;
extern s16 D_0001DF24;
extern s16 D_0001DF26;
extern s16 D_0001DF28;
extern s16 D_0001DF2A;
extern s16 D_0001DF3C;
extern s16 D_0001DF3E;
extern s16 D_0001DF40;
extern s16 D_0001DF42;
extern s16 D_0001DF44;
extern s16 D_0001DF46;
extern s16 D_0001DF48;
extern s16 D_0001DF4A;
extern s16 D_0001DF5C;
extern s16 D_0001DF5E;
extern s16 D_0001DF60;
extern s16 D_0001DF62;
extern s16 D_0001DF74;
extern s16 D_0001DF76;
extern s16 D_0001DF78;
extern s16 D_0001DF7A;
extern s16 D_0001DFCC;
extern s16 D_0001DFCE;
extern s16 D_0001DFD0;
extern s16 D_0001DFD2;
extern f32 D_0001DFE8;
extern s16 D_0001DFEC;
extern s16 D_0001DFEE;
extern s32 D_0001E760;
extern s32 D_0001E764;
extern s32 D_0001E76C;
extern s32 D_0001E770;
extern s32 D_0001E778;
extern u16 D_0001E77C;
extern u16 D_0001E77E;
extern u16 D_0001E780;
extern u16 D_0001E782;
extern u16 D_0001E8BA;
extern u16 D_0001E8C4;
extern s32 D_0001E904;
extern s32 D_0001E918;
extern s32 D_0001E91C;
extern s32 D_0001E920;
extern s32 D_0001E924;
extern s32 D_0001E928;
extern s32 D_0001E92C;
extern s32 D_0001E930;
extern s32 D_0001E934;
extern s32 D_0001E938;
extern s32 D_0001E93C;
extern s32 D_0001E940;
extern s32 D_0001E944;
extern s32 D_0001E948;
extern s32 D_0001F300;
extern s32 D_0001F304;
extern s32 D_0001F308;
extern s32 D_0001F30C;
extern s32 D_0001F314;
extern s32 D_0001F324;
extern s32 D_0001F328;
extern s32 D_0001F32C;

/* 105 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_0001D168; */
/* extern ? D_0001D6E0; */
/* extern ? D_0001D75C; */
/* extern ? D_0001D788; */
/* extern ? D_0001D794; */
/* extern ? D_0001D804; */
/* extern ? D_0001D81C; */
/* extern ? D_0001D880; */
/* extern ? D_0001D90C; */
/* extern ? D_0001DAC0; */
/* extern ? D_0001DAE4; */
/* extern ? D_0001DAEC; */
/* extern ? D_0001DAF4; */
/* extern ? D_0001DAFC; */
/* extern ? D_0001DB18; */
/* extern ? D_0001DB28; */
/* extern ? D_0001DB38; */
/* extern ? D_0001DB44; */
/* extern ? D_0001DB58; */
/* extern ? D_0001DB80; */
/* extern ? D_0001DBC8; */
/* extern ? D_0001DC10; */
/* extern ? D_0001DC58; */
/* extern ? D_0001DC70; */
/* extern ? D_0001DCEE; */
/* extern ? D_0001DD00; */
/* extern ? D_0001DD10; */
/* extern ? D_0001DD18; */
/* extern ? D_0001DD20; */
/* extern ? D_0001DD28; */
/* extern ? D_0001DD30; */
/* extern ? D_0001DD38; */
/* extern ? D_0001DD40; */
/* extern ? D_0001DF14; */
/* extern ? D_0001DF2C; */
/* extern ? D_0001DF4C; */
/* extern ? D_0001DF64; */
/* extern ? D_0001DF7C; */
/* extern ? D_0001DF9C; */
/* extern ? D_0001DFAC; */
/* extern ? D_0001DFBC; */
/* extern ? D_0001DFD4; */
/* extern ? D_0001DFF0; */
/* extern ? D_0001E010; */
/* extern ? D_0001E018; */
/* extern ? D_0001E024; */
/* extern ? D_0001E224; */
/* extern ? D_0001E44C; */
/* extern ? D_0001E7A8; */
/* extern ? D_0001E8AC; */
/* extern ? D_0001E94C; */
/* extern ? D_0001E95C; */
/* extern ? D_0001F318; */
/* extern ? duel_draw_1A643ACE; */
/* extern ? func_0000149C; */
/* extern ? func_00003E80; */
/* extern ? func_00004C60; */
/* extern ? func_00004DB8; */
/* extern ? func_0000500C; */
/* extern ? func_0000BFF8; */
/* extern ? func_00010E6C; */
/* extern ? func_00011814; */
/* extern ? func_0001220C; */
/* extern ? jtbl_0001CE70; */
/* extern ? jtbl_0001CE94; */
/* extern ? jtbl_0001CEB0; */
/* extern ? jtbl_0001CFF4; */
/* extern ? jtbl_0001D050; */
/* extern ? jtbl_0001D06C; */
/* extern ? jtbl_0001D0C8; */
/* extern ? jtbl_0001D10C; */
/* extern ? jtbl_0001D14C; */
/* extern ? jtbl_0001D170; */
/* extern ? jtbl_0001D18C; */
/* extern ? jtbl_0001D1A8; */
/* extern ? jtbl_0001D1D4; */
/* extern ? jtbl_0001D200; */
/* extern ? jtbl_0001D228; */
/* extern ? jtbl_0001D250; */
/* extern ? jtbl_0001D274; */
/* extern ? jtbl_0001D298; */
/* extern ? jtbl_0001D2BC; */
/* extern ? jtbl_0001D2E0; */
/* extern ? jtbl_0001D304; */
/* extern ? jtbl_0001D328; */
/* extern ? jtbl_0001D344; */
/* extern ? jtbl_0001D370; */
/* extern ? jtbl_0001D39C; */
/* extern ? jtbl_0001D3C8; */
/* extern ? jtbl_0001D3EC; */
/* extern ? jtbl_0001D418; */
/* extern ? jtbl_0001D430; */
/* extern ? jtbl_0001D4CC; */
/* extern ? jtbl_0001D4F0; */
/* extern ? jtbl_0001D508; */
/* extern ? jtbl_0001D528; */
/* extern ? jtbl_0001D54C; */
/* extern ? jtbl_0001D564; */
/* extern ? jtbl_0001D584; */
/* extern ? jtbl_0001D5A8; */
/* extern ? jtbl_0001D5C0; */
/* extern ? jtbl_0001D5E0; */
/* extern ? jtbl_0001D60C; */
/* extern ? jtbl_0001D624; */
/* extern ? jtbl_0001D644; */

#endif /* GLOBALS_REL_DUEL_MGR_H */
