/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_SOUNDTEST_H
#define GLOBALS_REL_SOUNDTEST_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 21 globals with a type the binary determines */
extern f32 D_000067C4;
extern f32 D_000067C8;
extern s32 D_00006960;
extern s32 D_00006964;
extern s32 D_00006968;
extern s32 D_0000696C;
extern s32 D_00006974;
extern s32 D_00006978;
extern s32 D_0000697C;
extern s32 D_00006980;
extern s32 D_00006A28;
extern s32 D_00006A2C;
extern s32 D_00006A30;
extern s32 D_00006A34;
extern s32 D_00006A38;
extern s32 D_00006A3C;
extern s32 D_00006A40;
extern s32 D_00006A44;
extern s32 D_00006A48;
extern s32 D_00006A4C;
extern s32 D_00006A50;

/* 1 accessed at more than one width — a union, or two
 * structs sharing a base. Decide these by hand before using them. */
/* extern ? D_00006970;   seen as f32, s32 */

/* 15 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_000067D0; */
/* extern ? D_000067D4; */
/* extern ? D_000067E0; */
/* extern ? D_00006820; */
/* extern ? D_000068C4; */
/* extern ? D_000068DC; */
/* extern ? D_000068E8; */
/* extern ? D_000068F0; */
/* extern ? D_000068F8; */
/* extern ? D_00006908; */
/* extern ? D_00006918; */
/* extern ? D_00006920; */
/* extern ? D_00006928; */
/* extern ? D_00006930; */
/* extern ? D_00006984; */

#endif /* GLOBALS_REL_SOUNDTEST_H */
