/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_UMD_REPLACE_H
#define GLOBALS_REL_UMD_REPLACE_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 20 globals with a type the binary determines */
extern f32 D_00009280;
extern f32 D_00009284;
extern f32 D_00009288;
extern f32 D_000092F0;
extern f32 D_00009320;
extern f32 D_00009328;
extern f32 D_00009330;
extern f32 D_00009338;
extern f32 D_00009340;
extern f32 D_00009348;
extern s32 D_000096EC;
extern s32 D_000096F0;
extern s32 D_000096F4;
extern s32 D_0000B100;
extern s32 D_0000B104;
extern s32 D_0000B3D0;
extern s32 D_0000B3D8;
extern s32 D_0000B7E0;
extern s32 D_0000B7E4;
extern s32 D_0000B7E8;

/* 57 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_00009350; */
/* extern ? D_00009354; */
/* extern ? D_0000935C; */
/* extern ? D_00009364; */
/* extern ? D_00009370; */
/* extern ? D_0000937C; */
/* extern ? D_00009388; */
/* extern ? D_00009394; */
/* extern ? D_000093A0; */
/* extern ? D_000093AC; */
/* extern ? D_000093B8; */
/* extern ? D_000093C4; */
/* extern ? D_000093D0; */
/* extern ? D_000093DC; */
/* extern ? D_000093E8; */
/* extern ? D_000093F4; */
/* extern ? D_000094B4; */
/* extern ? D_000096AC; */
/* extern ? D_000096B0; */
/* extern ? D_000096E0; */
/* extern ? D_00009700; */
/* extern ? D_00009780; */
/* extern ? D_0000B108; */
/* extern ? D_0000B154; */
/* extern ? D_0000B3E0; */
/* extern ? D_0000B3E2; */
/* extern ? D_0000B7EC; */
/* extern ? D_10CC0; */
/* extern ? D_190CC0; */
/* extern ? D_290CC0; */
/* extern ? D_290CE4; */
/* extern ? D_B910; */
/* extern ? D_B95C; */
/* extern ? D_B9E0; */
/* extern ? D_BA50; */
/* extern ? D_BAC0; */
/* extern ? D_BAD0; */
/* extern ? D_BBF4; */
/* extern ? D_BC40; */
/* extern ? D_BCC0; */
/* extern ? D_C033; */
/* extern ? func_00000038; */
/* extern ? func_000000DC; */
/* extern ? func_00000150; */
/* extern ? func_0000017C; */
/* extern ? func_00000B20; */
/* extern ? func_00001A88; */
/* extern ? func_0000327C; */
/* extern ? func_00003898; */
/* extern ? func_000038A8; */
/* extern ? func_00003970; */
/* extern ? jtbl_00009224; */
/* extern ? jtbl_00009244; */
/* extern ? jtbl_00009264; */
/* extern ? jtbl_0000928C; */
/* extern ? jtbl_000092D4; */
/* extern ? jtbl_000092F4; */

#endif /* GLOBALS_REL_UMD_REPLACE_H */
