/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_PASSWORD_H
#define GLOBALS_REL_PASSWORD_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 4 globals with a type the binary determines */
extern f32 D_000089EC;
extern f32 D_000089F0;
extern u8 D_00008C40;
extern s32 D_00008C44;

/* 19 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_00008ADC; */
/* extern ? D_00008BEC; */
/* extern ? D_00008C00; */
/* extern ? D_00008C08; */
/* extern ? D_00008C48; */
/* extern ? D_1DC50; */
/* extern ? D_1DC54; */
/* extern ? D_1DC55; */
/* extern ? D_1DC57; */
/* extern ? D_1DC6C; */
/* extern ? D_1DCFE; */
/* extern ? D_1DD90; */
/* extern ? D_1E590; */
/* extern ? D_1EDA0; */
/* extern ? func_0000149C; */
/* extern ? func_0000152C; */
/* extern ? jtbl_000089D0; */
/* extern ? jtbl_000089F8; */
/* extern ? jtbl_00008A1C; */

#endif /* GLOBALS_REL_PASSWORD_H */
