/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_TUTORIAL_H
#define GLOBALS_REL_TUTORIAL_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 25 globals with a type the binary determines */
extern s32 D_0000C7B8;
extern s16 D_0000C7BC;
extern s16 D_0000C7BE;
extern s16 D_0000C7C0;
extern s16 D_0000C7C2;
extern s32 D_0000C7C4;
extern s32 D_0000C7C8;
extern s16 D_0000CA04;
extern s16 D_0000CA06;
extern s16 D_0000CA08;
extern s32 D_0000E7FC;
extern s32 D_0000EC24;
extern s32 D_0000F04C;
extern s32 D_0000F474;
extern s32 D_00010028;
extern s32 D_0001002C;
extern s32 D_00010048;
extern u8 D_00010174;
extern u8 D_00010175;
extern s32 D_00010178;
extern s32 D_0001017C;
extern s32 D_00010180;
extern s32 D_00010184;
extern u8 D_000101BC;
extern s32 D_000101D4;

/* 66 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_0000C7B0; */
/* extern ? D_0000C974; */
/* extern ? D_0000C994; */
/* extern ? D_0000C9A4; */
/* extern ? D_0000C9B4; */
/* extern ? D_0000C9C8; */
/* extern ? D_0000C9E0; */
/* extern ? D_0000C9F0; */
/* extern ? D_0000CA0C; */
/* extern ? D_0000CA34; */
/* extern ? D_0000CA5C; */
/* extern ? D_0000CA64; */
/* extern ? D_0000CA8C; */
/* extern ? D_0000CABC; */
/* extern ? D_0000CAF0; */
/* extern ? D_0000E3E0; */
/* extern ? D_0000F480; */
/* extern ? D_00010030; */
/* extern ? D_00010050; */
/* extern ? D_000101A4; */
/* extern ? D_000101C8; */
/* extern ? D_15058; */
/* extern ? D_15060; */
/* extern ? D_150AC; */
/* extern ? D_15150; */
/* extern ? D_151C4; */
/* extern ? D_151CC; */
/* extern ? D_151DC; */
/* extern ? D_15200; */
/* extern ? D_15210; */
/* extern ? D_15A14; */
/* extern ? D_15A2C; */
/* extern ? D_15A30; */
/* extern ? D_15A34; */
/* extern ? D_15A38; */
/* extern ? D_15A3C; */
/* extern ? D_15A40; */
/* extern ? D_15A44; */
/* extern ? D_15A50; */
/* extern ? D_15A60; */
/* extern ? D_15E60; */
/* extern ? func_00000440; */
/* extern ? func_00000624; */
/* extern ? func_000007C0; */
/* extern ? func_00003A30; */
/* extern ? func_00004398; */
/* extern ? func_00004604; */
/* extern ? func_00005A14; */
/* extern ? func_0000614C; */
/* extern ? func_00006194; */
/* extern ? jtbl_0000C6B0; */
/* extern ? jtbl_0000C6C8; */
/* extern ? jtbl_0000C6EC; */
/* extern ? jtbl_0000C704; */
/* extern ? jtbl_0000C72C; */
/* extern ? jtbl_0000C754; */
/* extern ? jtbl_0000C76C; */
/* extern ? jtbl_0000C784; */
/* extern ? jtbl_0000C7D0; */
/* extern ? jtbl_0000C7F4; */
/* extern ? jtbl_0000C844; */
/* extern ? jtbl_0000C868; */
/* extern ? jtbl_0000C88C; */
/* extern ? jtbl_0000C8E0; */
/* extern ? jtbl_0000C8F8; */
/* extern ? jtbl_0000C94C; */

#endif /* GLOBALS_REL_TUTORIAL_H */
