/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_MOVIE_VIEWER_H
#define GLOBALS_REL_MOVIE_VIEWER_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 0 globals with a type the binary determines */

/* 14 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_00005A74; */
/* extern ? D_00005A7C; */
/* extern ? D_00005A88; */
/* extern ? D_00005AA4; */
/* extern ? D_00005AC0; */
/* extern ? D_00005AD0; */
/* extern ? D_85B00; */
/* extern ? D_9DB00; */
/* extern ? D_A3F0C; */
/* extern ? func_00000034; */
/* extern ? func_000001C0; */
/* extern ? func_000005C8; */
/* extern ? func_000006B4; */
/* extern ? func_000007C8; */

#endif /* GLOBALS_REL_MOVIE_VIEWER_H */
