/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_CHARALIST_H
#define GLOBALS_REL_CHARALIST_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 52 globals with a type the binary determines */
extern f32 D_0000E098;
extern s16 D_0000E0EC;
extern s16 D_0000E0EE;
extern s16 D_0000E0F0;
extern f32 D_0000E168;
extern f32 D_0000E170;
extern s16 D_0000E178;
extern s16 D_0000E17A;
extern s16 D_000252C8;
extern s16 D_000252CA;
extern u8 D_00025DC0;
extern u16 D_00025DC2;
extern u16 D_00025DC4;
extern u8 D_00025DC6;
extern u16 D_00025DD0;
extern u16 D_00025DD2;
extern u16 D_00025DD4;
extern s32 D_00025DD8;
extern s32 D_00025DDC;
extern s32 D_00025DE0;
extern s32 D_00025DE4;
extern u8 D_00025DE8;
extern s32 D_00025DEC;
extern s32 D_00025DF0;
extern s32 D_00025DF4;
extern s32 D_00025DF8;
extern s32 D_00025DFC;
extern u16 D_00025E00;
extern u16 D_00025E02;
extern u16 D_00025E04;
extern u8 D_00025E06;
extern u8 D_00025E07;
extern s32 D_00025E08;
extern u16 D_00025E0C;
extern s32 D_00025E10;
extern s32 D_00025E14;
extern u8 D_00025E18;
extern u16 D_00025E1A;
extern u16 D_00025E1C;
extern s32 D_00025E20;
extern u16 D_00025E26;
extern s32 D_000261FC;
extern s32 D_00026200;
extern u8 D_00026210;
extern s32 D_00026214;
extern u8 D_00026218;
extern s32 D_000278C8;
extern s32 D_00027918;
extern u8 D_0002791C;
extern s32 D_0002793C;
extern s32 D_00027AC8;
extern s32 D_00027ACC;

/* 1 accessed at more than one width — a union, or two
 * structs sharing a base. Decide these by hand before using them. */
/* extern ? D_00025E1E;   seen as s16, u16 */

/* 43 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_0000E094; */
/* extern ? D_0000E0A0; */
/* extern ? D_0000E0DC; */
/* extern ? D_0000E0F4; */
/* extern ? D_0000E17C; */
/* extern ? D_0000E3F8; */
/* extern ? D_00024EA8; */
/* extern ? D_00024EAC; */
/* extern ? D_00025214; */
/* extern ? D_00025280; */
/* extern ? D_00025298; */
/* extern ? D_000252A0; */
/* extern ? D_000252AC; */
/* extern ? D_000252B8; */
/* extern ? D_000252CC; */
/* extern ? D_0002544C; */
/* extern ? D_0002570C; */
/* extern ? D_0002590C; */
/* extern ? D_00025974; */
/* extern ? D_000259BC; */
/* extern ? D_000259CC; */
/* extern ? D_000259DC; */
/* extern ? D_000259E8; */
/* extern ? D_00025C28; */
/* extern ? D_00025DC8; */
/* extern ? D_00025DCC; */
/* extern ? D_000260A8; */
/* extern ? D_000260AC; */
/* extern ? D_00027920; */
/* extern ? D_00027960; */
/* extern ? D_00027994; */
/* extern ? D_000279C6; */
/* extern ? func_00006224; */
/* extern ? func_000062B4; */
/* extern ? func_000062DC; */
/* extern ? func_00006D50; */
/* extern ? jtbl_0000DFB4; */
/* extern ? jtbl_0000DFD8; */
/* extern ? jtbl_0000DFF0; */
/* extern ? jtbl_0000E008; */
/* extern ? jtbl_0000E020; */
/* extern ? jtbl_0000E04C; */
/* extern ? jtbl_0000E070; */

#endif /* GLOBALS_REL_CHARALIST_H */
