/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_DECKSWAP_H
#define GLOBALS_REL_DECKSWAP_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 114 globals with a type the binary determines */
extern f32 D_0001D560;
extern f32 D_0001D568;
extern s16 D_0001D6E8;
extern s16 D_0001D6EA;
extern s16 D_0001D6EC;
extern s16 D_0001D6EE;
extern u16 D_0001D780;
extern u16 D_0001D782;
extern u16 D_0001D784;
extern s16 D_0001DED0;
extern s16 D_0001DED2;
extern s16 D_0001E214;
extern s16 D_0001E216;
extern s32 D_0001E21C;
extern u16 D_0001E220;
extern u16 D_0001E222;
extern s32 D_0001E228;
extern u16 D_0001E22C;
extern u16 D_0001E22E;
extern s32 D_0001E234;
extern u16 D_0001E238;
extern u16 D_0001E23A;
extern s32 D_0001E240;
extern u16 D_0001E244;
extern u16 D_0001E246;
extern s32 D_0001E24C;
extern u16 D_0001E252;
extern s16 D_0001E268;
extern s16 D_0001E26A;
extern u16 D_0001E270;
extern u16 D_0001E272;
extern u16 D_0001E274;
extern u16 D_0001E276;
extern u16 D_0001E27C;
extern u16 D_0001E27E;
extern u16 D_0001E280;
extern u16 D_0001E282;
extern s16 D_0001E2A0;
extern s16 D_0001E2A2;
extern s16 D_0001E2A4;
extern s16 D_0001E2A8;
extern s16 D_0001E2AA;
extern s16 D_0001E2AC;
extern s16 D_0001E2CC;
extern s16 D_0001E2CE;
extern s32 D_0001E2E4;
extern u16 D_0001E2E8;
extern u16 D_0001E2EA;
extern s32 D_0001E2F0;
extern s32 D_0001E2F8;
extern s32 D_0001E2FC;
extern u16 D_0001E300;
extern s32 D_0001E310;
extern s32 D_0001E318;
extern s32 D_0001E31C;
extern u16 D_0001E320;
extern s32 D_0001E330;
extern s32 D_0001E338;
extern s32 D_0001E33C;
extern u16 D_0001E340;
extern u16 D_0001E75C;
extern s16 D_0001E880;
extern s32 D_0001E884;
extern u8 D_0001E888;
extern u16 D_0001E88A;
extern s32 D_0001E88C;
extern s32 D_0001E890;
extern s32 D_0001E894;
extern s32 D_0001E898;
extern s32 D_0001E89C;
extern s32 D_0001E8A0;
extern s32 D_0001E8A4;
extern s32 D_0001E8A8;
extern s32 D_0001E8AC;
extern s32 D_0001E8B0;
extern s32 D_0001E8B4;
extern s32 D_0001E8C4;
extern s32 D_0001E8C8;
extern u8 D_0001E8CC;
extern u16 D_0001E8D0;
extern u16 D_0001E8D2;
extern u16 D_0001E8D4;
extern s32 D_0001E8D8;
extern s32 D_0001E8DC;
extern s32 D_0001E8E4;
extern u8 D_0001E8FC;
extern s32 D_0001E900;
extern u8 D_0001E904;
extern u16 D_0001E906;
extern u16 D_0001E908;
extern u16 D_0001E90A;
extern s16 D_0001E90C;
extern s32 D_0001E92C;
extern u8 D_0001E930;
extern u16 D_0001E932;
extern u16 D_0001E934;
extern u16 D_0001E936;
extern s16 D_0001F964;
extern s32 D_0001F968;
extern u16 D_0001F96C;
extern u16 D_0001F96E;
extern u16 D_0001F970;
extern s32 D_0001F974;
extern s32 D_0001F978;
extern s32 D_0001F97C;
extern s32 D_0001F980;
extern s32 D_0001F984;
extern u8 D_0001F990;
extern s32 D_0001F994;
extern s32 D_0001F998;
extern u8 D_0001F99C;
extern s32 D_0001F9BC;
extern s32 D_0001FB48;
extern s32 D_0001FB4C;

/* 4 accessed at more than one width — a union, or two
 * structs sharing a base. Decide these by hand before using them. */
/* extern ? D_0001E302;   seen as w1, w2 */
/* extern ? D_0001E322;   seen as w1, w2 */
/* extern ? D_0001E342;   seen as w1, w2 */
/* extern ? D_0001E8C0;   seen as w1, w2 */

/* 95 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_0001D464; */
/* extern ? D_0001D548; */
/* extern ? D_0001D54C; */
/* extern ? D_0001D558; */
/* extern ? D_0001D56C; */
/* extern ? D_0001D5A4; */
/* extern ? D_0001D5B0; */
/* extern ? D_0001D5D0; */
/* extern ? D_0001D628; */
/* extern ? D_0001D644; */
/* extern ? D_0001D668; */
/* extern ? D_0001D6A0; */
/* extern ? D_0001D6F0; */
/* extern ? D_0001D710; */
/* extern ? D_0001D720; */
/* extern ? D_0001D740; */
/* extern ? D_0001D748; */
/* extern ? D_0001D75C; */
/* extern ? D_0001D788; */
/* extern ? D_0001D820; */
/* extern ? D_0001D860; */
/* extern ? D_0001D8BC; */
/* extern ? D_0001D8E0; */
/* extern ? D_0001D904; */
/* extern ? D_0001D930; */
/* extern ? D_0001D944; */
/* extern ? D_0001D974; */
/* extern ? D_0001DC2C; */
/* extern ? D_0001DE40; */
/* extern ? D_0001DE58; */
/* extern ? D_0001DE60; */
/* extern ? D_0001DEA4; */
/* extern ? D_0001DEB0; */
/* extern ? D_0001DEB8; */
/* extern ? D_0001DEC0; */
/* extern ? D_0001DEC8; */
/* extern ? D_0001DED4; */
/* extern ? D_0001DEF8; */
/* extern ? D_0001DFC0; */
/* extern ? D_0001E02C; */
/* extern ? D_0001E03C; */
/* extern ? D_0001E07C; */
/* extern ? D_0001E0B4; */
/* extern ? D_0001E0C0; */
/* extern ? D_0001E170; */
/* extern ? D_0001E1A8; */
/* extern ? D_0001E1F0; */
/* extern ? D_0001E1FC; */
/* extern ? D_0001E208; */
/* extern ? D_0001E254; */
/* extern ? D_0001E284; */
/* extern ? D_0001E2B0; */
/* extern ? D_0001E2BC; */
/* extern ? D_0001E2E0; */
/* extern ? D_0001E2EC; */
/* extern ? D_0001E30C; */
/* extern ? D_0001E32C; */
/* extern ? D_0001E34C; */
/* extern ? D_0001E74C; */
/* extern ? D_0001E7AE; */
/* extern ? D_0001E7B8; */
/* extern ? D_0001F040; */
/* extern ? D_0001F08C; */
/* extern ? D_0001F164; */
/* extern ? D_0001F9A0; */
/* extern ? D_0001F9E0; */
/* extern ? D_0001FA14; */
/* extern ? D_0001FA46; */
/* extern ? func_0000627C; */
/* extern ? func_00006534; */
/* extern ? func_00009D50; */
/* extern ? func_0000A02C; */
/* extern ? func_0000A1B8; */
/* extern ? func_0000A1E4; */
/* extern ? func_0000C29C; */
/* extern ? func_0000C72C; */
/* extern ? func_0000D21C; */
/* extern ? func_0000D24C; */
/* extern ? func_0000D6CC; */
/* extern ? func_0000D754; */
/* extern ? func_0000EDBC; */
/* extern ? func_0000EE6C; */
/* extern ? func_0000F058; */
/* extern ? func_0000F3D4; */
/* extern ? func_0000F4A8; */
/* extern ? func_0000F6A4; */
/* extern ? jtbl_0001D3D4; */
/* extern ? jtbl_0001D3FC; */
/* extern ? jtbl_0001D428; */
/* extern ? jtbl_0001D448; */
/* extern ? jtbl_0001D46C; */
/* extern ? jtbl_0001D494; */
/* extern ? jtbl_0001D4C0; */
/* extern ? jtbl_0001D4EC; */
/* extern ? jtbl_0001D518; */

#endif /* GLOBALS_REL_DECKSWAP_H */
