/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_DEBUG_MENU_H
#define GLOBALS_REL_DEBUG_MENU_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 15 globals with a type the binary determines */
extern s32 D_00009C90;
extern s32 D_00009C94;
extern s32 D_00009C98;
extern s32 D_00009C9C;
extern s32 D_00009CA4;
extern s32 D_00009CAC;
extern s32 D_00009CB0;
extern s32 D_00009CB4;
extern s32 D_00009CB8;
extern s32 D_00009CBC;
extern s32 D_00009CC0;
extern s32 D_00009CC4;
extern s32 D_00009CD8;
extern s32 D_00009CDC;
extern s32 D_00009CE4;

/* 87 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_000091E0; */
/* extern ? D_00009220; */
/* extern ? D_00009250; */
/* extern ? D_00009350; */
/* extern ? D_00009490; */
/* extern ? D_000098B0; */
/* extern ? D_00009A04; */
/* extern ? D_00009A14; */
/* extern ? D_00009A38; */
/* extern ? D_00009A3C; */
/* extern ? D_00009A40; */
/* extern ? D_00009A44; */
/* extern ? D_00009A48; */
/* extern ? D_00009A58; */
/* extern ? D_00009A64; */
/* extern ? D_00009A68; */
/* extern ? D_00009A74; */
/* extern ? D_00009A7C; */
/* extern ? D_00009A88; */
/* extern ? D_00009A94; */
/* extern ? D_00009A9C; */
/* extern ? D_00009AA0; */
/* extern ? D_00009AAC; */
/* extern ? D_00009AB0; */
/* extern ? D_00009AB4; */
/* extern ? D_00009AB8; */
/* extern ? D_00009ABC; */
/* extern ? D_00009AC4; */
/* extern ? D_00009AD4; */
/* extern ? D_00009AE8; */
/* extern ? D_00009AF0; */
/* extern ? D_00009B00; */
/* extern ? D_00009B14; */
/* extern ? D_00009B1C; */
/* extern ? D_00009B20; */
/* extern ? D_00009B28; */
/* extern ? D_00009B2C; */
/* extern ? D_00009B34; */
/* extern ? D_00009B3C; */
/* extern ? D_00009B44; */
/* extern ? D_00009B4C; */
/* extern ? D_00009B54; */
/* extern ? D_00009B5C; */
/* extern ? D_00009B64; */
/* extern ? D_00009B70; */
/* extern ? D_00009B78; */
/* extern ? D_00009B80; */
/* extern ? D_00009B88; */
/* extern ? D_00009B90; */
/* extern ? D_00009B94; */
/* extern ? D_00009BB4; */
/* extern ? D_00009BC0; */
/* extern ? D_00009BC8; */
/* extern ? D_00009BD4; */
/* extern ? D_00009BEC; */
/* extern ? D_00009C08; */
/* extern ? D_00009C14; */
/* extern ? D_00009C1C; */
/* extern ? D_00009C28; */
/* extern ? D_00009C40; */
/* extern ? D_00009C68; */
/* extern ? D_00009CF0; */
/* extern ? D_809CF8; */
/* extern ? D_809D04; */
/* extern ? D_80A108; */
/* extern ? D_80A498; */
/* extern ? D_80A49C; */
/* extern ? D_80AB9C; */
/* extern ? D_80ABD0; */
/* extern ? D_80AFA0; */
/* extern ? D_80B330; */
/* extern ? D_80B334; */
/* extern ? D_80B374; */
/* extern ? D_80B3A4; */
/* extern ? D_80B5A4; */
/* extern ? D_80B664; */
/* extern ? D_80BA2C; */
/* extern ? func_00000034; */
/* extern ? func_00000264; */
/* extern ? func_000002DC; */
/* extern ? func_00000C78; */
/* extern ? jtbl_000095B4; */
/* extern ? jtbl_000095DC; */
/* extern ? jtbl_000095FC; */
/* extern ? jtbl_0000961C; */
/* extern ? jtbl_00009644; */
/* extern ? jtbl_00009674; */

#endif /* GLOBALS_REL_DEBUG_MENU_H */
