/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_CUTIN_VIEWER_H
#define GLOBALS_REL_CUTIN_VIEWER_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 232 globals with a type the binary determines */
extern s32 D_00008724;
extern s32 D_00008728;
extern s32 D_0000872C;
extern s32 D_00008730;
extern s32 D_00008734;
extern s32 D_00008738;
extern f32 D_0000B080;
extern f32 D_0000B090;
extern s32 D_0000B098;
extern f32 D_0000B0A0;
extern f32 D_0000B0A8;
extern f32 D_0000B0B4;
extern s32 D_0000B0BC;
extern s32 D_0000B0C0;
extern f32 D_0000B0C8;
extern s32 D_0000B0D8;
extern u16 D_0000E160;
extern u16 D_0000E162;
extern f32 D_0000E740;
extern f32 D_0000E748;
extern s32 D_00010B44;
extern s32 D_00010B4C;
extern s32 D_00010B50;
extern s32 D_00010B54;
extern s32 D_00010B58;
extern s32 D_00010B5C;
extern s32 D_00010B60;
extern s32 D_00010B64;
extern s32 D_00010B68;
extern s32 D_00010B6C;
extern s32 D_00010B70;
extern s32 D_00010B74;
extern f32 D_00010B78;
extern s32 D_00010B7C;
extern s32 D_00010B80;
extern s32 D_00010B84;
extern s32 D_00010B88;
extern s32 D_00010B90;
extern s32 D_00010B94;
extern s32 D_00010B98;
extern s32 D_00010B9C;
extern s32 D_00010BA0;
extern s32 D_00010BA4;
extern s32 D_00010BA8;
extern f32 D_00010BAC;
extern s32 D_00010BB0;
extern s32 D_00010BB4;
extern s32 D_00010BB8;
extern s32 D_00010BBC;
extern f32 D_00010BC0;
extern f32 D_00010BC4;
extern s32 D_00010BC8;
extern s32 D_00010BE4;
extern s32 D_00010BF0;
extern s32 D_00010BF4;
extern f32 D_00010BF8;
extern s32 D_00010C00;
extern s32 D_00010C04;
extern f32 D_00010C08;
extern s32 D_00010C10;
extern u8 D_00011815;
extern u8 D_00011896;
extern u8 D_00011897;
extern f32 D_00011D18;
extern f32 D_00011D20;
extern s32 D_00011D24;
extern f32 D_00011D30;
extern s32 D_00011D34;
extern f32 D_00011D38;
extern s32 D_00011D3C;
extern s32 D_00011E58;
extern s32 D_00011E5C;
extern s32 D_00011E60;
extern s32 D_00011E64;
extern s32 D_00011E68;
extern f32 D_00011E70;
extern f32 D_00011E74;
extern s32 D_00011E78;
extern f32 D_00011E80;
extern s32 D_00011E88;
extern f32 D_00011E8C;
extern s32 D_00011E90;
extern s32 D_00012D94;
extern s32 D_00012D9C;
extern s32 D_00012DA0;
extern s32 D_00012DAC;
extern s32 D_00012DBC;
extern s32 D_00012DC0;
extern f32 D_00012DC8;
extern f32 D_00012DCC;
extern s32 D_00012DD0;
extern s32 D_00013734;
extern s32 D_00013738;
extern s32 D_0001373C;
extern s32 D_00013740;
extern s32 D_00013B04;
extern s32 D_00013B08;
extern s32 D_00013B0C;
extern s32 D_00013B10;
extern s32 D_00013B14;
extern s32 D_00013B18;
extern s32 D_00013B1C;
extern s32 D_00013B20;
extern s32 D_00013B24;
extern f32 D_00013B28;
extern s32 D_00013B30;
extern f32 D_0001E898;
extern s32 D_000201E0;
extern f32 D_000201E8;
extern s32 D_000201F0;
extern s32 D_000201F4;
extern f32 D_000201F8;
extern f32 D_00020200;
extern s32 D_00020208;
extern f32 D_0002020C;
extern f32 D_00020210;
extern s32 D_00020214;
extern s32 D_00020218;
extern s32 D_0002021C;
extern f32 D_00020220;
extern s32 D_00020228;
extern s32 D_00020230;
extern s32 D_00021D50;
extern f32 D_00021D98;
extern f32 D_00021DA0;
extern f32 D_00021DA8;
extern f32 D_00022670;
extern f32 D_00022674;
extern f32 D_00022678;
extern f32 D_00022680;
extern f32 D_00022688;
extern f32 D_0002268C;
extern f32 D_00022690;
extern f32 D_00022694;
extern f32 D_00022698;
extern f32 D_0002269C;
extern f32 D_000226A0;
extern f32 D_000226A4;
extern f32 D_000226A8;
extern f32 D_000226AC;
extern f32 D_000226B0;
extern f32 D_000226B8;
extern f32 D_000226C0;
extern f32 D_000226C4;
extern f32 D_000226C8;
extern f32 D_000226D0;
extern f32 D_000226D4;
extern f32 D_000226D8;
extern f32 D_000226E0;
extern f32 D_000226E4;
extern f32 D_000226E8;
extern f32 D_000226EC;
extern f32 D_000226F0;
extern f32 D_000226F8;
extern f32 D_00022700;
extern f32 D_00022708;
extern f32 D_00022790;
extern f32 D_00022794;
extern s32 D_00023F98;
extern s32 D_00023FAC;
extern s32 D_00023FC0;
extern s32 D_00023FD4;
extern f32 D_00024230;
extern f32 D_00024238;
extern f32 D_00024240;
extern f32 D_00024248;
extern f32 D_00024250;
extern f32 D_00024258;
extern f32 D_00024260;
extern f32 D_00024268;
extern f32 D_00024410;
extern f32 D_00024418;
extern f32 D_00024420;
extern f32 D_00024428;
extern s32 D_00024430;
extern s32 D_00024438;
extern s32 D_00024440;
extern s32 D_00024444;
extern s32 D_000244A8;
extern s32 D_000244AC;
extern s32 D_000244C0;
extern s32 D_000244C4;
extern s32 D_00024528;
extern s32 D_0002452C;
extern f32 D_000248C0;
extern f32 D_000248C4;
extern f32 D_000248C8;
extern f32 D_000248D0;
extern s32 D_000248E0;
extern f32 D_000248E8;
extern f32 D_000248EC;
extern s32 D_000248F0;
extern f32 D_000248F8;
extern f32 D_000248FC;
extern s32 D_00024900;
extern f32 D_00024908;
extern f32 D_0002490C;
extern s32 D_00024910;
extern f32 D_00024918;
extern f32 D_0002491C;
extern f32 D_00024920;
extern f32 D_00024928;
extern f32 D_00024930;
extern f32 D_00024938;
extern f32 D_00024940;
extern f32 D_00024948;
extern f32 D_00024950;
extern f32 D_00024958;
extern f32 D_00024960;
extern f32 D_00024968;
extern f32 D_00024970;
extern f32 D_00024978;
extern f32 D_00024980;
extern f32 D_00024988;
extern u8 D_00025904;
extern u8 D_00025905;
extern s32 D_00025AA0;
extern s32 D_00025AA4;
extern s32 D_0002BEA8;
extern u8 D_0002BF99;
extern s32 D_0002BFD0;
extern s32 D_0002C02C;
extern s32 D_0002C1C0;
extern s32 D_0002C1C4;
extern s32 D_0002D1C4;
extern s32 D_0002E1C4;
extern s32 D_0002E1C8;
extern s32 D_0002E1CC;
extern s32 D_0002E1D0;
extern s32 D_0002E1D4;
extern s32 D_0002E1D8;
extern f32 ehsys_8F3D00D1;

/* 11 accessed at more than one width — a union, or two
 * structs sharing a base. Decide these by hand before using them. */
/* extern ? D_0000B084;   seen as f32, s32 */
/* extern ? D_0000B088;   seen as f32, s32 */
/* extern ? D_0000B0B0;   seen as f32, s32 */
/* extern ? D_0000B0B8;   seen as f32, s32 */
/* extern ? D_0000B0C4;   seen as f32, s32 */
/* extern ? D_0000B0D0;   seen as f32, s32 */
/* extern ? D_00010B40;   seen as f32, s32 */
/* extern ? D_00012D90;   seen as f32, s32 */
/* extern ? D_00012DA4;   seen as f32, s32 */
/* extern ? D_00012DB0;   seen as f32, s32 */
/* extern ? D_00012DB8;   seen as f32, s32 */

/* 187 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_00021D74; */
/* extern ? D_00022710; */
/* extern ? D_00022724; */
/* extern ? D_00022738; */
/* extern ? D_0002274C; */
/* extern ? D_00022798; */
/* extern ? D_000227A0; */
/* extern ? D_000227B4; */
/* extern ? D_000227C0; */
/* extern ? D_000227D0; */
/* extern ? D_000227DC; */
/* extern ? D_000227F8; */
/* extern ? D_000227FC; */
/* extern ? D_00022804; */
/* extern ? D_00022814; */
/* extern ? D_00022820; */
/* extern ? D_00022828; */
/* extern ? D_00022830; */
/* extern ? D_00023F1C; */
/* extern ? D_00024050; */
/* extern ? D_00024068; */
/* extern ? D_0002407C; */
/* extern ? D_00024094; */
/* extern ? D_000240AC; */
/* extern ? D_000240BC; */
/* extern ? D_000240CC; */
/* extern ? D_000240E0; */
/* extern ? D_000240F4; */
/* extern ? D_00024108; */
/* extern ? D_00024118; */
/* extern ? D_00024128; */
/* extern ? D_00024138; */
/* extern ? D_00024148; */
/* extern ? D_00024158; */
/* extern ? D_00024168; */
/* extern ? D_00024178; */
/* extern ? D_0002418C; */
/* extern ? D_0002419C; */
/* extern ? D_000241AC; */
/* extern ? D_000241BC; */
/* extern ? D_000241CC; */
/* extern ? D_00024204; */
/* extern ? D_00024210; */
/* extern ? D_0002421C; */
/* extern ? D_00024270; */
/* extern ? D_00024294; */
/* extern ? D_00024458; */
/* extern ? D_000244B0; */
/* extern ? D_000244D8; */
/* extern ? D_00024530; */
/* extern ? D_00024544; */
/* extern ? D_00024554; */
/* extern ? D_00024564; */
/* extern ? D_00024578; */
/* extern ? D_00024588; */
/* extern ? D_00024810; */
/* extern ? D_00024D00; */
/* extern ? D_000250FC; */
/* extern ? D_00025458; */
/* extern ? D_000257C8; */
/* extern ? D_000258B8; */
/* extern ? D_000258C0; */
/* extern ? D_000258D8; */
/* extern ? D_000258EC; */
/* extern ? D_00025908; */
/* extern ? D_0002591C; */
/* extern ? D_0002592C; */
/* extern ? D_00025938; */
/* extern ? D_00025944; */
/* extern ? D_00025950; */
/* extern ? D_0002595C; */
/* extern ? D_00025968; */
/* extern ? D_00025974; */
/* extern ? D_00025980; */
/* extern ? D_0002598C; */
/* extern ? D_00025998; */
/* extern ? D_000259A4; */
/* extern ? D_000259B0; */
/* extern ? D_000259BC; */
/* extern ? D_000259C0; */
/* extern ? D_000259C8; */
/* extern ? D_000259DC; */
/* extern ? D_000259EC; */
/* extern ? D_00025A00; */
/* extern ? D_00025A10; */
/* extern ? D_00025A20; */
/* extern ? D_00025A30; */
/* extern ? D_00025A40; */
/* extern ? D_00025A58; */
/* extern ? D_00025A80; */
/* extern ? D_00025A90; */
/* extern ? D_0002BEAC; */
/* extern ? D_0002BFE0; */
/* extern ? D_0002E1E0; */
/* extern ? D_B2E1E0; */
/* extern ? D_B2E6E0; */
/* extern ? D_B2EE90; */
/* extern ? D_B2EEBC; */
/* extern ? D_B2EEC8; */
/* extern ? D_B2EEF4; */
/* extern ? D_B2F4A0; */
/* extern ? D_B31464; */
/* extern ? D_B31480; */
/* extern ? D_B314C0; */
/* extern ? D_B31500; */
/* extern ? D_B31540; */
/* extern ? D_B31580; */
/* extern ? D_B31590; */
/* extern ? D_B316C0; */
/* extern ? D_B31780; */
/* extern ? D_B32B90; */
/* extern ? D_C82B90; */
/* extern ? D_D32BA0; */
/* extern ? D_E32BD0; */
/* extern ? func_0000003C; */
/* extern ? func_000002E0; */
/* extern ? func_00000B4C; */
/* extern ? func_000010F0; */
/* extern ? func_0000130C; */
/* extern ? func_00001440; */
/* extern ? func_000034C4; */
/* extern ? func_0000369C; */
/* extern ? func_000039E8; */
/* extern ? func_00003A40; */
/* extern ? func_00003B94; */
/* extern ? func_00003C40; */
/* extern ? func_00003E8C; */
/* extern ? func_00003E94; */
/* extern ? func_00005248; */
/* extern ? func_00005588; */
/* extern ? func_000056F0; */
/* extern ? func_0000572C; */
/* extern ? func_00005A1C; */
/* extern ? func_00005A60; */
/* extern ? func_00007E04; */
/* extern ? func_000091BC; */
/* extern ? func_0000BB28; */
/* extern ? func_0000C5E4; */
/* extern ? func_0000D1D0; */
/* extern ? func_0000E238; */
/* extern ? func_0000ECD4; */
/* extern ? func_0000F5DC; */
/* extern ? func_00010538; */
/* extern ? func_0001149C; */
/* extern ? func_00011AB8; */
/* extern ? func_000120EC; */
/* extern ? func_00012694; */
/* extern ? func_000131F4; */
/* extern ? func_00013D94; */
/* extern ? func_00014A78; */
/* extern ? func_00015B40; */
/* extern ? func_00016ECC; */
/* extern ? func_00017AF4; */
/* extern ? func_00017CB8; */
/* extern ? func_0001AEA4; */
/* extern ? func_0001BD1C; */
/* extern ? func_0001BDDC; */
/* extern ? func_0001C044; */
/* extern ? func_0001C200; */
/* extern ? func_0001C244; */
/* extern ? func_0001C4DC; */
/* extern ? func_0001C4F8; */
/* extern ? func_0001C5C4; */
/* extern ? func_0001C5D4; */
/* extern ? func_0001C7E4; */
/* extern ? func_0001C7FC; */
/* extern ? func_0001C8CC; */
/* extern ? func_0001C91C; */
/* extern ? func_0001C97C; */
/* extern ? func_0001C9E8; */
/* extern ? func_0001CA84; */
/* extern ? func_0001CAE4; */
/* extern ? func_0001CAEC; */
/* extern ? func_0001CAF4; */
/* extern ? jtbl_00021D24; */
/* extern ? jtbl_00021D80; */
/* extern ? jtbl_00021DAC; */
/* extern ? jtbl_0002248C; */
/* extern ? jtbl_000224DC; */
/* extern ? jtbl_0002252C; */
/* extern ? jtbl_00022568; */
/* extern ? jtbl_000225A4; */
/* extern ? jtbl_000225E0; */
/* extern ? jtbl_00022600; */
/* extern ? jtbl_00022624; */
/* extern ? jtbl_00022654; */
/* extern ? jtbl_00022760; */

#endif /* GLOBALS_REL_CUTIN_VIEWER_H */
