/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_STORY_H
#define GLOBALS_REL_STORY_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 91 globals with a type the binary determines */
extern f32 D_0001B888;
extern s16 D_0001FF20;
extern s16 D_0001FF22;
extern s16 D_0001FF4C;
extern s16 D_0001FF4E;
extern f32 D_000241B8;
extern f32 D_000241C0;
extern s32 D_0002A5D0;
extern s32 D_0002A654;
extern s32 D_0002A658;
extern s32 D_0002A65C;
extern s32 D_0002A660;
extern s32 D_0002F128;
extern s32 D_0002F12C;
extern s32 D_0002F134;
extern s32 D_0002F138;
extern s32 D_0002F13C;
extern s32 D_0002F144;
extern s32 D_0002F148;
extern s32 D_0002F150;
extern s32 D_0002F35C;
extern s32 D_00033A98;
extern s32 D_00033AA8;
extern s32 D_00033B98;
extern s32 D_00033B9C;
extern u8 D_00033BA0;
extern u8 D_00033BA1;
extern u8 D_00033BA2;
extern u8 D_00033BA3;
extern u8 D_00033BA4;
extern u8 D_00033BA5;
extern u8 D_00033BA6;
extern u8 D_00033BA7;
extern s32 D_00033BA8;
extern s32 D_00033BAC;
extern u16 D_00033BB4;
extern u16 D_00033BB6;
extern u16 D_00033BBC;
extern s32 D_00033DA8;
extern u16 D_00033DAC;
extern u16 D_00033DAE;
extern u16 D_00033DB4;
extern s32 D_00033FA0;
extern u16 D_00033FA4;
extern u16 D_00033FA6;
extern u16 D_00033FAC;
extern s32 D_00034198;
extern u16 D_0003419C;
extern u16 D_0003419E;
extern u16 D_000341A4;
extern s32 D_00034390;
extern s32 D_00034398;
extern s32 D_0003439C;
extern s32 D_00034470;
extern u8 D_00034480;
extern s32 D_00034484;
extern s32 D_00034488;
extern s32 D_00034490;
extern s32 D_00034494;
extern s32 D_00034498;
extern s32 D_000344A4;
extern s32 D_00034560;
extern s32 D_00034574;
extern s32 D_00034578;
extern s32 D_0003457C;
extern s32 D_00034580;
extern s32 D_00034584;
extern s32 D_00034588;
extern s32 D_0003458C;
extern s32 D_00034590;
extern s32 D_00034594;
extern s32 D_00034F98;
extern s32 D_00034F9C;
extern s32 D_00034FA4;
extern s32 D_00034FA8;
extern s32 D_00034FAC;
extern s32 D_00034FB8;
extern s32 D_00034FBC;
extern s32 D_00034FC0;
extern s32 D_00034FC4;
extern s32 D_00034FC8;
extern s32 D_00034FCC;
extern s32 D_00034FD0;
extern s32 D_00034FD4;
extern s32 D_000351F8;
extern s32 D_000351FC;
extern s32 D_00035200;
extern s32 D_00035204;
extern s32 D_00035218;
extern s32 D_0003521C;
extern s32 D_00035220;

/* 97 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_0001B5A0; */
/* extern ? D_0001B6EC; */
/* extern ? D_0001B890; */
/* extern ? D_0001FC44; */
/* extern ? D_0001FF24; */
/* extern ? D_0001FF50; */
/* extern ? D_0001FF54; */
/* extern ? D_0001FF58; */
/* extern ? D_0001FF5C; */
/* extern ? D_00020010; */
/* extern ? D_0002001C; */
/* extern ? D_00020050; */
/* extern ? D_00020068; */
/* extern ? D_0002007C; */
/* extern ? D_00020084; */
/* extern ? D_0002008C; */
/* extern ? D_000200A4; */
/* extern ? D_000200BC; */
/* extern ? D_000200C8; */
/* extern ? D_000200D4; */
/* extern ? D_000200DC; */
/* extern ? D_000200E4; */
/* extern ? D_000200EC; */
/* extern ? D_000200F4; */
/* extern ? D_00020108; */
/* extern ? D_0002011C; */
/* extern ? D_00020134; */
/* extern ? D_00020144; */
/* extern ? D_00023EC8; */
/* extern ? D_000241A4; */
/* extern ? D_00024260; */
/* extern ? D_0002A530; */
/* extern ? D_0002A558; */
/* extern ? D_0002A55C; */
/* extern ? D_0002A5AC; */
/* extern ? D_0002A5C0; */
/* extern ? D_0002A5CC; */
/* extern ? D_0002A5D4; */
/* extern ? D_0002A664; */
/* extern ? D_0002F130; */
/* extern ? D_0002F14C; */
/* extern ? D_0002F15C; */
/* extern ? D_0002F360; */
/* extern ? D_00033AAC; */
/* extern ? D_00033ACC; */
/* extern ? D_0003449C; */
/* extern ? D_000344A8; */
/* extern ? D_0003452C; */
/* extern ? D_00034564; */
/* extern ? D_00034FA0; */
/* extern ? D_00034FD8; */
/* extern ? D_00035208; */
/* extern ? D_00035230; */
/* extern ? func_00000038; */
/* extern ? func_00000230; */
/* extern ? func_00000238; */
/* extern ? func_00000240; */
/* extern ? func_000034F8; */
/* extern ? func_000096D4; */
/* extern ? func_000097B8; */
/* extern ? func_00009824; */
/* extern ? func_000098B8; */
/* extern ? func_00015A08; */
/* extern ? jtbl_0001B284; */
/* extern ? jtbl_0001B2D8; */
/* extern ? jtbl_0001B334; */
/* extern ? jtbl_0001B390; */
/* extern ? jtbl_0001B3DC; */
/* extern ? jtbl_0001B3F4; */
/* extern ? jtbl_0001B40C; */
/* extern ? jtbl_0001B4B8; */
/* extern ? jtbl_0001B524; */
/* extern ? jtbl_0001B580; */
/* extern ? jtbl_0001B5B4; */
/* extern ? jtbl_0001B5F0; */
/* extern ? jtbl_0001B6C4; */
/* extern ? jtbl_0001B750; */
/* extern ? jtbl_0001B7D4; */
/* extern ? jtbl_0001B7F0; */
/* extern ? jtbl_0001B848; */
/* extern ? jtbl_0001B8B0; */
/* extern ? jtbl_0001B8FC; */
/* extern ? jtbl_0001BC28; */
/* extern ? jtbl_0001BC50; */
/* extern ? jtbl_0001BC7C; */
/* extern ? jtbl_0001BCAC; */
/* extern ? jtbl_0001BCDC; */
/* extern ? jtbl_0001BCFC; */
/* extern ? jtbl_0001BD2C; */
/* extern ? jtbl_0001BD5C; */
/* extern ? jtbl_0001BDE8; */
/* extern ? jtbl_0001BE24; */
/* extern ? jtbl_0001BE3C; */
/* extern ? jtbl_0001BE54; */
/* extern ? jtbl_0001BE74; */
/* extern ? jtbl_0001BE90; */
/* extern ? jtbl_0001BEAC; */

#endif /* GLOBALS_REL_STORY_H */
