/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_LABO_H
#define GLOBALS_REL_LABO_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 10 globals with a type the binary determines */
extern s32 D_00006BE4;
extern s32 D_00006BE8;
extern s32 D_00006BEC;
extern s32 D_0000ADF0;
extern s32 D_0000ADF4;
extern s32 D_0000ADF8;
extern s32 D_0000ADFC;
extern s32 D_0000AE18;
extern s32 D_0000AE24;
extern s32 D_0000AE30;

/* 2 accessed at more than one width — a union, or two
 * structs sharing a base. Decide these by hand before using them. */
/* extern ? D_0000AE1C;   seen as s32, u16 */
/* extern ? D_0000AE20;   seen as s32, u16 */

/* 22 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_00006820; */
/* extern ? D_00006850; */
/* extern ? D_0000688C; */
/* extern ? D_00006B8C; */
/* extern ? D_00006B9C; */
/* extern ? D_00006BA0; */
/* extern ? D_0000A868; */
/* extern ? D_0000AD60; */
/* extern ? D_0000AD68; */
/* extern ? D_0000AD6C; */
/* extern ? D_0000AD78; */
/* extern ? D_0000AD90; */
/* extern ? D_0000ADA4; */
/* extern ? D_0000ADB0; */
/* extern ? D_0000ADB4; */
/* extern ? D_0000AE0C; */
/* extern ? D_0000AE40; */
/* extern ? func_00000034; */
/* extern ? func_0000097C; */
/* extern ? func_00000984; */
/* extern ? func_00000A0C; */
/* extern ? jtbl_000067E4; */

#endif /* GLOBALS_REL_LABO_H */
