/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_DECK_H
#define GLOBALS_REL_DECK_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 110 globals with a type the binary determines */
extern s32 D_000154C4;
extern s32 D_000154C8;
extern s16 D_00029D54;
extern s16 D_00029D56;
extern s16 D_00029D58;
extern s16 D_00029E24;
extern s16 D_00029E26;
extern s16 D_00029E28;
extern s16 D_00029E2A;
extern u16 D_00029EBC;
extern u16 D_00029EBE;
extern u16 D_00029EC0;
extern f32 D_0002A118;
extern f32 D_0002A130;
extern f32 D_0002A134;
extern f32 D_0002A138;
extern f32 D_0002A140;
extern f32 D_0002A148;
extern f32 D_0002A14C;
extern s16 D_0002A974;
extern s16 D_0002A976;
extern s32 D_0002A97C;
extern u16 D_0002A980;
extern u16 D_0002A982;
extern s32 D_0002A988;
extern u16 D_0002A98C;
extern u16 D_0002A98E;
extern s32 D_0002A994;
extern u16 D_0002A998;
extern u16 D_0002A99A;
extern s32 D_0002A9A0;
extern u16 D_0002A9A4;
extern u16 D_0002A9A6;
extern s32 D_0002A9AC;
extern u16 D_0002A9B2;
extern s16 D_0002A9C8;
extern s16 D_0002A9CA;
extern u16 D_0002A9D0;
extern u16 D_0002A9D2;
extern u16 D_0002A9D4;
extern u16 D_0002A9D6;
extern u16 D_0002A9DC;
extern u16 D_0002A9DE;
extern u16 D_0002A9E0;
extern u16 D_0002A9E2;
extern s16 D_0002AA00;
extern s16 D_0002AA02;
extern s16 D_0002AA04;
extern s16 D_0002AA08;
extern s16 D_0002AA0A;
extern s16 D_0002AA0C;
extern s16 D_0002AA2C;
extern s16 D_0002AA2E;
extern s32 D_0002CFE0;
extern u16 D_0002CFE4;
extern u16 D_0002CFE6;
extern u16 D_0002D90C;
extern s32 D_0002D910;
extern u16 D_0002D914;
extern u16 D_0002D916;
extern u16 D_0002D918;
extern s32 D_0002D91C;
extern s32 D_0002D920;
extern s32 D_0002D924;
extern s32 D_0002D93C;
extern s32 D_0002D95C;
extern s32 D_0002D97C;
extern s32 D_0002D994;
extern s32 D_0002D9BC;
extern s32 D_0002D9DC;
extern u16 D_0002DA70;
extern u16 D_0002DA72;
extern u16 D_0002DA74;
extern u8 D_0002DA76;
extern u8 D_0002DA77;
extern u16 D_0002DA78;
extern u16 D_0002DA7A;
extern u16 D_0002DA7E;
extern u16 D_0002DF50;
extern s32 D_0002E0A8;
extern s32 D_0002E0AC;
extern s32 D_0002E0FC;
extern s32 D_0002E100;
extern s32 D_0002E104;
extern s32 D_0002E108;
extern s32 D_0002E10C;
extern s32 D_0002E110;
extern s32 D_0002E114;
extern u8 D_0002E121;
extern s32 D_0002E124;
extern s32 D_0002E128;
extern u8 D_0002E12C;
extern u16 D_0002E130;
extern u16 D_0002E132;
extern u16 D_0002E134;
extern s32 D_0002E138;
extern s32 D_0002E13C;
extern s32 D_0002E144;
extern u8 D_0002E15C;
extern s32 D_0002E160;
extern u8 D_0002E164;
extern u16 D_0002E166;
extern u16 D_0002E168;
extern u16 D_0002E16A;
extern s16 D_0002E16C;
extern s32 D_0002E18C;
extern u8 D_0002E190;
extern u16 D_0002E192;
extern u16 D_0002E194;
extern u16 D_0002E196;

/* 3 accessed at more than one width — a union, or two
 * structs sharing a base. Decide these by hand before using them. */
/* extern ? D_0002DA7C;   seen as u16, u8 */
/* extern ? D_0002E074;   seen as s16, u16 */
/* extern ? D_0002E120;   seen as u16, u8 */

/* 185 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_000297C8; */
/* extern ? D_0002987C; */
/* extern ? D_000298B0; */
/* extern ? D_000298E0; */
/* extern ? D_00029C34; */
/* extern ? D_00029C4C; */
/* extern ? D_00029C58; */
/* extern ? D_00029C90; */
/* extern ? D_00029C9C; */
/* extern ? D_00029CBC; */
/* extern ? D_00029D14; */
/* extern ? D_00029D30; */
/* extern ? D_00029D5C; */
/* extern ? D_00029D74; */
/* extern ? D_00029D88; */
/* extern ? D_00029D94; */
/* extern ? D_00029DA0; */
/* extern ? D_00029DDC; */
/* extern ? D_00029E2C; */
/* extern ? D_00029E4C; */
/* extern ? D_00029E5C; */
/* extern ? D_00029E7C; */
/* extern ? D_00029E84; */
/* extern ? D_00029E98; */
/* extern ? D_00029EC4; */
/* extern ? D_00029F5C; */
/* extern ? D_00029FA0; */
/* extern ? D_00029FB4; */
/* extern ? D_00029FBE; */
/* extern ? D_0002A054; */
/* extern ? D_0002A06C; */
/* extern ? D_0002A0A4; */
/* extern ? D_0002A0C4; */
/* extern ? D_0002A0E8; */
/* extern ? D_0002A0FC; */
/* extern ? D_0002A108; */
/* extern ? D_0002A11C; */
/* extern ? D_0002A128; */
/* extern ? D_0002A150; */
/* extern ? D_0002A218; */
/* extern ? D_0002A284; */
/* extern ? D_0002A294; */
/* extern ? D_0002A2D4; */
/* extern ? D_0002A30C; */
/* extern ? D_0002A318; */
/* extern ? D_0002A3C8; */
/* extern ? D_0002A400; */
/* extern ? D_0002A448; */
/* extern ? D_0002A454; */
/* extern ? D_0002A700; */
/* extern ? D_0002A8EC; */
/* extern ? D_0002A8FC; */
/* extern ? D_0002A904; */
/* extern ? D_0002A90C; */
/* extern ? D_0002A914; */
/* extern ? D_0002A958; */
/* extern ? D_0002A964; */
/* extern ? D_0002A96C; */
/* extern ? D_0002A9B4; */
/* extern ? D_0002A9E4; */
/* extern ? D_0002AA10; */
/* extern ? D_0002AA1C; */
/* extern ? D_0002AA30; */
/* extern ? D_0002AA3C; */
/* extern ? D_0002AA48; */
/* extern ? D_0002AA54; */
/* extern ? D_0002AD90; */
/* extern ? D_0002B114; */
/* extern ? D_0002B684; */
/* extern ? D_0002BB64; */
/* extern ? D_0002C044; */
/* extern ? D_0002C524; */
/* extern ? D_0002CA04; */
/* extern ? D_0002CEE4; */
/* extern ? D_0002CFA4; */
/* extern ? D_0002CFB4; */
/* extern ? D_0002CFBC; */
/* extern ? D_0002CFE8; */
/* extern ? D_0002D034; */
/* extern ? D_0002D10C; */
/* extern ? D_0002D930; */
/* extern ? D_0002D940; */
/* extern ? D_0002D950; */
/* extern ? D_0002D970; */
/* extern ? D_0002D990; */
/* extern ? D_0002D9B0; */
/* extern ? D_0002D9D0; */
/* extern ? D_0002D9F0; */
/* extern ? D_0002DA80; */
/* extern ? D_0002DA90; */
/* extern ? D_0002DB50; */
/* extern ? D_0002DFA2; */
/* extern ? D_0002DFAC; */
/* extern ? D_0002E078; */
/* extern ? D_0002E07C; */
/* extern ? D_0002E0B0; */
/* extern ? D_0002E1B8; */
/* extern ? D_0002E8A0; */
/* extern ? D_F768A0; */
/* extern ? D_F768B0; */
/* extern ? D_F768BC; */
/* extern ? D_F768C0; */
/* extern ? D_F76900; */
/* extern ? D_F76934; */
/* extern ? D_F76966; */
/* extern ? D_F76A70; */
/* extern ? D_F76A80; */
/* extern ? D_F76ACC; */
/* extern ? D_F76B60; */
/* extern ? D_F76BC8; */
/* extern ? D_F76C90; */
/* extern ? D_F76C9C; */
/* extern ? D_F76CE8; */
/* extern ? D_F76D64; */
/* extern ? D_F76D7C; */
/* extern ? D_F76DB0; */
/* extern ? D_F76DFC; */
/* extern ? D_F76E88; */
/* extern ? D_F76EA0; */
/* extern ? D_F76ED4; */
/* extern ? D_F76F20; */
/* extern ? func_00001BEC; */
/* extern ? func_00001D9C; */
/* extern ? func_0000C0A8; */
/* extern ? func_0000C360; */
/* extern ? func_0000EE34; */
/* extern ? func_0000EF68; */
/* extern ? func_0000F028; */
/* extern ? func_0000F0D0; */
/* extern ? func_0001112C; */
/* extern ? func_000114B0; */
/* extern ? func_0001163C; */
/* extern ? func_00011690; */
/* extern ? func_0001171C; */
/* extern ? func_00011BFC; */
/* extern ? func_000136C0; */
/* extern ? func_00015AEC; */
/* extern ? func_00015B04; */
/* extern ? func_00015FE0; */
/* extern ? func_00016ACC; */
/* extern ? func_00016AFC; */
/* extern ? func_00016F7C; */
/* extern ? func_00017004; */
/* extern ? func_00018638; */
/* extern ? func_000186E8; */
/* extern ? func_000188D8; */
/* extern ? func_00018C54; */
/* extern ? func_00018D28; */
/* extern ? func_00018F24; */
/* extern ? func_00022190; */
/* extern ? func_00023148; */
/* extern ? func_000231A0; */
/* extern ? func_000232F4; */
/* extern ? func_00023374; */
/* extern ? func_00023560; */
/* extern ? func_00023D00; */
/* extern ? func_00023D20; */
/* extern ? func_00023EE8; */
/* extern ? func_00024034; */
/* extern ? func_00024144; */
/* extern ? jtbl_000295E0; */
/* extern ? jtbl_000295F8; */
/* extern ? jtbl_00029610; */
/* extern ? jtbl_00029634; */
/* extern ? jtbl_00029658; */
/* extern ? jtbl_00029684; */
/* extern ? jtbl_000296A4; */
/* extern ? jtbl_000296C4; */
/* extern ? jtbl_000296E4; */
/* extern ? jtbl_00029710; */
/* extern ? jtbl_0002972C; */
/* extern ? jtbl_00029748; */
/* extern ? jtbl_00029760; */
/* extern ? jtbl_0002978C; */
/* extern ? jtbl_000297A8; */
/* extern ? jtbl_000297D0; */
/* extern ? jtbl_00029800; */
/* extern ? jtbl_00029824; */
/* extern ? jtbl_00029850; */
/* extern ? jtbl_000298E8; */
/* extern ? jtbl_00029900; */
/* extern ? jtbl_0002996C; */
/* extern ? jtbl_00029AB4; */
/* extern ? jtbl_00029BFC; */
/* extern ? jtbl_00029C14; */

#endif /* GLOBALS_REL_DECK_H */
