/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_DUEL_DRAW_H
#define GLOBALS_REL_DUEL_DRAW_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 963 globals with a type the binary determines */
extern s32 D_00008008;
extern s32 D_00008018;
extern s32 D_000086F8;
extern s32 D_000086FC;
extern s32 D_00008700;
extern s32 D_00008704;
extern u8 D_0000AA40;
extern u8 D_0000AA41;
extern u8 D_0000AA44;
extern u8 D_0000AA45;
extern u8 D_0000AA48;
extern u8 D_0000AA49;
extern s32 D_0000AA88;
extern s32 D_0000AA8C;
extern s32 D_0000AA90;
extern s32 D_0000AA94;
extern s32 D_0000AA98;
extern s32 D_0000AA9C;
extern s32 D_0000AAA0;
extern s32 D_0000AAA4;
extern f32 D_0000AAA8;
extern s32 D_0000AAAC;
extern s32 D_0000AAB0;
extern s32 D_0000AAB4;
extern s32 D_0000AAB8;
extern s32 D_0000AABC;
extern s32 D_0000AAC0;
extern s32 D_0000AAC4;
extern s32 D_0000AAC8;
extern s32 D_0000AACC;
extern s32 D_0000AAD0;
extern s32 D_0000AAD4;
extern s32 D_0000AAD8;
extern f32 D_0000AADC;
extern s32 D_0000AAE0;
extern s32 D_0000AAE4;
extern s32 D_0000AAE8;
extern s32 D_0000AAEC;
extern f32 D_0000AAF0;
extern s32 D_0000AB30;
extern s32 D_0000AB34;
extern f32 D_0000AB38;
extern f32 D_0000AB3C;
extern s32 D_0000AB40;
extern s32 D_0000AB44;
extern s32 D_0000AB48;
extern s32 D_0000AB4C;
extern s32 D_0000AB50;
extern f32 D_0000AB54;
extern s32 D_0000AB58;
extern s32 D_0000AB5C;
extern s32 D_0000AB60;
extern s32 D_0000AB64;
extern s32 D_0000AB68;
extern s32 D_0000AB6C;
extern s32 D_0000AB70;
extern s32 D_0000AB74;
extern s32 D_0000AB78;
extern f32 D_0000AB88;
extern s32 D_0000AB8C;
extern f32 D_0000AB90;
extern f32 D_0000AB94;
extern f32 D_0000AB98;
extern f32 D_0000AB9C;
extern s32 D_0000ABA0;
extern f32 D_0000ABA4;
extern f32 D_0000ABA8;
extern f32 D_0000ABB0;
extern s32 D_0000ABB4;
extern s32 D_0000ABB8;
extern f32 D_0000ABC0;
extern f32 D_0000ABC4;
extern f32 D_0000ABC8;
extern s32 D_0000ABCC;
extern s32 D_0000ABD0;
extern s32 D_0000ABD4;
extern s32 D_0000ABD8;
extern s32 D_0000ABDC;
extern s32 D_0000ABE0;
extern f32 D_0000ABE4;
extern f32 D_0000ABE8;
extern s32 D_0000ABEC;
extern f32 D_0000ABF0;
extern s32 D_0000B050;
extern s32 D_0000B054;
extern s32 D_0000B058;
extern s32 D_0000B05C;
extern s32 D_0000B060;
extern s32 D_0000B064;
extern f32 D_0000B068;
extern f32 D_0000B06C;
extern s32 D_0000B070;
extern f32 D_0000B074;
extern f32 D_0000B080;
extern f32 D_0000B088;
extern f32 D_0000B090;
extern s32 D_0000B098;
extern f32 D_0000B0A8;
extern f32 D_0000B0B0;
extern f32 D_0000B0B4;
extern f32 D_0000B0B8;
extern s32 D_0000B0BC;
extern s32 D_0000B0C0;
extern f32 D_0000B0C4;
extern f32 D_0000B0C8;
extern f32 D_0000B0D0;
extern s32 D_0000B3CC;
extern s32 D_0000B3D0;
extern f32 D_0000B3D8;
extern s32 D_0000B3E0;
extern s32 D_0000B3E4;
extern f32 D_0000B400;
extern s32 D_0000B408;
extern s32 D_0000B40C;
extern s32 D_0000B410;
extern s32 D_0000B414;
extern s32 D_0000B41C;
extern s32 D_0000B420;
extern f32 D_0000B428;
extern s32 D_0000B5E8;
extern s32 D_0000B5EC;
extern s32 D_0000DC04;
extern f32 D_0000E740;
extern f32 D_0000E748;
extern s32 D_000108B4;
extern s32 D_000108BC;
extern s32 D_00010A08;
extern s32 D_00010AD4;
extern f32 D_00010B40;
extern s32 D_00010B44;
extern s32 D_00010B48;
extern s32 D_00010B4C;
extern s32 D_00010B50;
extern s32 D_00010B54;
extern s32 D_00010B58;
extern s32 D_00010B5C;
extern s32 D_00010B60;
extern s32 D_00010B64;
extern s32 D_00010B68;
extern s32 D_00010B6C;
extern s32 D_00010B70;
extern s32 D_00010B74;
extern f32 D_00010B78;
extern s32 D_00010B7C;
extern s32 D_00010B80;
extern s32 D_00010B84;
extern s32 D_00010B88;
extern s32 D_00010B8C;
extern s32 D_00010B90;
extern s32 D_00010B94;
extern s32 D_00010B98;
extern s32 D_00010B9C;
extern s32 D_00010BA0;
extern s32 D_00010BA4;
extern f32 D_00010BAC;
extern s32 D_00010BB0;
extern s32 D_00010BB4;
extern s32 D_00010BB8;
extern s32 D_00010BBC;
extern f32 D_00010BC4;
extern s32 D_00010BC8;
extern s32 D_00010BE4;
extern f32 D_00010BE8;
extern s32 D_00010BF0;
extern s32 D_00010BF4;
extern f32 D_00010BF8;
extern s32 D_00010C00;
extern f32 D_00010C08;
extern s32 D_00010C10;
extern f32 D_00011D18;
extern f32 D_00011D20;
extern s32 D_00011D24;
extern f32 D_00011D30;
extern s32 D_00011D34;
extern f32 D_00011D38;
extern s32 D_00011D3C;
extern s32 D_00011E58;
extern s32 D_00011E5C;
extern s32 D_00011E60;
extern s32 D_00011E64;
extern s32 D_00011E68;
extern f32 D_00011E70;
extern f32 D_00011E74;
extern s32 D_00011E78;
extern f32 D_00011E80;
extern s32 D_00011E88;
extern f32 D_00011E8C;
extern s32 D_00011E90;
extern f32 D_00012D90;
extern s32 D_00012D94;
extern s32 D_00012D98;
extern s32 D_00012D9C;
extern s32 D_00012DA0;
extern f32 D_00012DA4;
extern f32 D_00012DA8;
extern s32 D_00012DAC;
extern f32 D_00012DB0;
extern f32 D_00012DB4;
extern f32 D_00012DB8;
extern s32 D_00012DBC;
extern s32 D_00012DC0;
extern s32 D_00012DC4;
extern f32 D_00012DC8;
extern f32 D_00012DCC;
extern s32 D_00012DD0;
extern s32 D_00013B04;
extern s32 D_00013B08;
extern s32 D_00013B0C;
extern s32 D_00013B10;
extern s32 D_00013B14;
extern s32 D_00013B18;
extern s32 D_00013B1C;
extern s32 D_00013B20;
extern s32 D_00013B24;
extern f32 D_00013B28;
extern f32 D_00013B2C;
extern f32 D_00015AF8;
extern s32 D_000163D0;
extern s32 D_000163D4;
extern s32 D_000163D8;
extern f32 D_000163DC;
extern s32 D_000163E0;
extern s32 D_000163E4;
extern s32 D_000163E8;
extern s32 D_000163EC;
extern s32 D_000163F0;
extern s32 D_000163F4;
extern f32 D_000163F8;
extern s32 D_000163FC;
extern s32 D_00016400;
extern s32 D_00016404;
extern s32 D_00016408;
extern s32 D_0001640C;
extern f32 D_00016410;
extern s32 D_00016418;
extern s32 D_0001641C;
extern s32 D_00016420;
extern s32 D_00016428;
extern s32 D_0001642C;
extern s32 D_00016430;
extern s32 D_00016434;
extern s32 D_00016438;
extern s32 D_00016440;
extern s32 D_00016444;
extern s32 D_00016448;
extern s32 D_0001644C;
extern s32 D_00016450;
extern s32 D_00016454;
extern s32 D_00016458;
extern s32 D_0001645C;
extern s32 D_00016460;
extern f32 D_00016464;
extern f32 D_00016468;
extern s32 D_0001646C;
extern f32 D_00016470;
extern s32 D_00018388;
extern s32 D_0001838C;
extern s32 D_00018390;
extern f32 D_00018394;
extern s32 D_00018398;
extern s32 D_0001880C;
extern s32 D_00018810;
extern s32 D_00018814;
extern s32 D_0001881C;
extern s32 D_00018820;
extern s32 D_00018824;
extern s32 D_00018828;
extern s32 D_0001882C;
extern s32 D_00018830;
extern f32 D_00018834;
extern s32 D_00018838;
extern s32 D_0001883C;
extern s32 D_00018840;
extern s32 D_000188C0;
extern s32 D_00018BCC;
extern s32 D_00018BD0;
extern s32 D_00018BD4;
extern f32 D_00018BD8;
extern s32 D_00018BDC;
extern s32 D_00018BE0;
extern s32 D_00018BE4;
extern s32 D_00018BE8;
extern s32 D_00018BEC;
extern f32 D_00018BF0;
extern s32 D_00018BF8;
extern s32 D_00018BFC;
extern s32 D_00018C00;
extern s32 D_00018C04;
extern f32 D_00018C08;
extern s32 D_00018C0C;
extern s32 D_00018C10;
extern s32 D_00018C14;
extern s32 D_00018C18;
extern s32 D_00018C1C;
extern f32 D_00018C20;
extern f32 D_00018C24;
extern s32 D_00018C28;
extern s32 D_00018C2C;
extern s32 D_00018C30;
extern f32 D_0001E898;
extern s32 D_000201E0;
extern f32 D_000201E8;
extern s32 D_000201F0;
extern s32 D_000201F4;
extern f32 D_00020200;
extern s32 D_00020208;
extern f32 D_0002020C;
extern f32 D_00020210;
extern s32 D_00020214;
extern s32 D_00020218;
extern s32 D_0002021C;
extern f32 D_00020220;
extern s32 D_00020228;
extern s32 D_00020230;
extern s32 D_00023C08;
extern s32 D_00023C0C;
extern s32 D_00023C8C;
extern s32 D_00074460;
extern f32 D_00074668;
extern f32 D_00074688;
extern f32 D_00074690;
extern f32 D_00074694;
extern f32 D_00074698;
extern f32 D_000746A0;
extern f32 D_000746A4;
extern s32 D_00074734;
extern s32 D_00074738;
extern f32 D_0007476C;
extern f32 D_00074770;
extern f32 D_00074774;
extern f32 D_00074778;
extern f32 D_0007477C;
extern f32 D_00074780;
extern f32 D_00074788;
extern f32 D_000747AC;
extern f32 D_000747B0;
extern f32 D_000747B4;
extern f32 D_000747DC;
extern f32 D_000747F8;
extern f32 D_00074800;
extern f32 D_00074808;
extern f32 D_0007480C;
extern f32 D_00074810;
extern f32 D_00074818;
extern f32 D_00074820;
extern u8 D_0007483C;
extern u8 D_0007483D;
extern s32 D_000748C0;
extern f32 D_000748DC;
extern f32 D_000748E0;
extern f32 D_000748E4;
extern f32 D_000748E8;
extern f32 D_000748EC;
extern f32 D_000748F0;
extern f32 D_000748F4;
extern f32 D_000748F8;
extern f32 D_00074900;
extern f32 D_00074908;
extern f32 D_0007490C;
extern f32 D_00074910;
extern f32 D_00074918;
extern f32 D_0007491C;
extern f32 D_00074920;
extern f32 D_00074928;
extern f32 D_00074930;
extern f32 D_00074934;
extern f32 D_00074938;
extern f32 D_0007493C;
extern f32 D_00074940;
extern f32 D_00074948;
extern f32 D_0007494C;
extern f32 D_00074950;
extern f32 D_00074958;
extern f32 D_0007495C;
extern f32 D_00074960;
extern f32 D_00074964;
extern f32 D_00074968;
extern f32 D_00074970;
extern f32 D_00074978;
extern f32 D_0007497C;
extern f32 D_00074980;
extern f32 D_00074984;
extern f32 D_00074988;
extern f32 D_0007498C;
extern f32 D_00074990;
extern f32 D_00074994;
extern f32 D_00074998;
extern f32 D_000749A0;
extern f32 D_000749A4;
extern f32 D_000749A8;
extern f32 D_000749B0;
extern f32 D_000749B8;
extern f32 D_000749BC;
extern f32 D_000749C0;
extern f32 D_000749C4;
extern f32 D_000749C8;
extern f32 D_000749D0;
extern f32 D_000749D4;
extern f32 D_000749D8;
extern f32 D_000749DC;
extern f32 D_000749E0;
extern f32 D_000749E4;
extern f32 D_000749E8;
extern f32 D_000749F0;
extern f32 D_000749F8;
extern f32 D_00074A00;
extern f32 D_00074A08;
extern f32 D_00074A10;
extern f32 D_00074A14;
extern f32 D_00074A18;
extern f32 D_00074A20;
extern f32 D_00074A28;
extern f32 D_00074A30;
extern f32 D_00074A38;
extern f32 D_00074A40;
extern f32 D_00074A48;
extern f32 D_00074A50;
extern f32 D_00074A58;
extern f32 D_00075328;
extern f32 D_0007532C;
extern f32 D_00075330;
extern f32 D_00075338;
extern f32 D_00075340;
extern f32 D_00075344;
extern f32 D_00075348;
extern f32 D_0007534C;
extern f32 D_00075350;
extern f32 D_00075354;
extern f32 D_00075358;
extern f32 D_0007535C;
extern f32 D_00075360;
extern f32 D_00075364;
extern f32 D_00075368;
extern f32 D_00075370;
extern f32 D_00075378;
extern f32 D_0007537C;
extern f32 D_00075380;
extern f32 D_00075388;
extern f32 D_0007538C;
extern f32 D_00075390;
extern f32 D_00075398;
extern f32 D_0007539C;
extern f32 D_000753A0;
extern f32 D_000753A4;
extern f32 D_000753A8;
extern f32 D_000753B0;
extern f32 D_000753B8;
extern f32 D_000753C0;
extern f32 D_00075488;
extern f32 D_00075510;
extern f32 D_0007559C;
extern f32 D_00075638;
extern s32 D_00076F54;
extern s32 D_00076F68;
extern s32 D_00076F7C;
extern s32 D_00076F90;
extern f32 D_000771F0;
extern f32 D_000771F8;
extern f32 D_00077200;
extern f32 D_00077208;
extern f32 D_00077210;
extern f32 D_00077218;
extern f32 D_00077220;
extern f32 D_00077228;
extern f32 D_000773D0;
extern f32 D_000773D8;
extern f32 D_000773E0;
extern f32 D_000773E8;
extern s32 D_000773F0;
extern s32 D_000773F4;
extern f32 D_00077660;
extern f32 D_00077668;
extern f32 D_000777B0;
extern f32 D_000777B4;
extern f32 D_000777B8;
extern f32 D_000777C0;
extern u16 D_000777C4;
extern u8 D_000777C9;
extern f32 D_000777D0;
extern f32 D_000777D8;
extern f32 D_000777E0;
extern f32 D_000777E8;
extern f32 D_000777F0;
extern f32 D_000777F8;
extern f32 D_00077800;
extern f32 D_00077808;
extern f32 D_00077810;
extern f32 D_00077818;
extern f32 D_00077820;
extern f32 D_00077828;
extern f32 D_00077830;
extern f32 D_00077838;
extern f32 D_00077840;
extern f32 D_00077848;
extern f32 D_00077850;
extern f32 D_00077858;
extern f32 D_00077860;
extern f32 D_00077868;
extern f32 D_00077870;
extern f32 D_00077878;
extern f32 D_00077880;
extern f32 D_00077888;
extern f32 D_00077890;
extern f32 D_00077898;
extern f32 D_000778A0;
extern f32 D_000778A8;
extern f32 D_000778B0;
extern f32 D_000778B8;
extern f32 D_000778C0;
extern f32 D_000778C8;
extern f32 D_000778D0;
extern f32 D_000778D8;
extern f32 D_000778E0;
extern f32 D_000778E8;
extern f32 D_000778F0;
extern f32 D_000778F8;
extern f32 D_00077900;
extern f32 D_00077908;
extern f32 D_00077910;
extern f32 D_00077918;
extern f32 D_00077920;
extern f32 D_00077928;
extern f32 D_00077930;
extern f32 D_00077938;
extern f32 D_00077940;
extern f32 D_00077948;
extern f32 D_00077950;
extern f32 D_00077958;
extern f32 D_00077960;
extern f32 D_00077968;
extern f32 D_00077970;
extern f32 D_00077978;
extern f32 D_00077980;
extern f32 D_00077988;
extern f32 D_00077990;
extern f32 D_00077998;
extern f32 D_000779A0;
extern f32 D_000779A8;
extern f32 D_000779B0;
extern f32 D_000779B8;
extern f32 D_000779C0;
extern f32 D_000779C8;
extern f32 D_000779D0;
extern f32 D_000779D8;
extern f32 D_000779E0;
extern f32 D_000779E8;
extern f32 D_000779F0;
extern f32 D_000779F8;
extern f32 D_000779FC;
extern f32 D_00077A00;
extern f32 D_00077A08;
extern f32 D_00077A10;
extern f32 D_00077A18;
extern f32 D_00077A20;
extern f32 D_00077A28;
extern s16 D_00077A44;
extern f32 D_00077A50;
extern f32 D_00077A58;
extern f32 D_00077A60;
extern f32 D_00077A68;
extern f32 D_00077A70;
extern f32 D_00077A78;
extern s16 D_00077A80;
extern f32 D_00077A90;
extern f32 D_00077A98;
extern f32 D_00077AA0;
extern f32 D_00077AA8;
extern f32 D_00077AB0;
extern f32 D_00077AB8;
extern f32 D_00077AC0;
extern f32 D_00077AC8;
extern f32 D_00077ACC;
extern f32 D_00077AD0;
extern f32 D_00077AD8;
extern f32 D_00077AE0;
extern u16 D_00077B28;
extern f32 D_00077B30;
extern f32 D_00077B34;
extern f32 D_00077B40;
extern f32 D_00077B48;
extern f32 D_00077BB0;
extern f32 D_00077BB8;
extern u8 D_00077BC0;
extern u8 D_00077BC1;
extern u8 D_00077BC2;
extern u8 D_00077BC3;
extern u8 D_00077BC4;
extern u8 D_00077BC5;
extern u8 D_00077BC6;
extern u8 D_00077BC7;
extern u8 D_00077BC8;
extern u8 D_00077BC9;
extern u8 D_00077BCA;
extern u8 D_00077BCB;
extern u8 D_00077BCC;
extern u8 D_00077BCD;
extern u8 D_00077BCE;
extern u8 D_00077BCF;
extern f32 D_00077BD0;
extern f32 D_00077BD8;
extern f32 D_00077BDC;
extern f32 D_00077BF0;
extern f32 D_00077BF8;
extern f32 D_00077C20;
extern f32 D_00077C28;
extern s32 D_00077C9C;
extern s32 D_00077D04;
extern f32 D_00077DC8;
extern f32 D_00077DCC;
extern f32 D_00077DD0;
extern f32 D_00077DD4;
extern f32 D_00078088;
extern f32 D_00078090;
extern f32 D_00078098;
extern f32 D_0007809C;
extern f32 D_000780A0;
extern f32 D_000780E0;
extern f32 D_000780E8;
extern f32 D_000780F0;
extern f32 D_000780F4;
extern f32 D_000780F8;
extern f32 D_00078100;
extern f32 D_00078108;
extern f32 D_0007810C;
extern f32 D_00078110;
extern f32 D_00078118;
extern f32 D_00078120;
extern f32 D_00078124;
extern f32 D_00078128;
extern f32 D_00078130;
extern f32 D_00078138;
extern f32 D_0007813C;
extern f32 D_00078140;
extern f32 D_00078148;
extern f32 D_00078150;
extern f32 D_00078154;
extern f32 D_00078158;
extern f32 D_00078160;
extern f32 D_00078168;
extern f32 D_0007816C;
extern f32 D_00078170;
extern f32 D_00078178;
extern f32 D_00078180;
extern f32 D_00078184;
extern f32 D_00078188;
extern f32 D_00078190;
extern f32 D_00078198;
extern f32 D_0007819C;
extern f32 D_000781A0;
extern f32 D_000781A8;
extern f32 D_000781B0;
extern f32 D_000781B8;
extern f32 D_000781E8;
extern f32 D_000781F0;
extern f32 D_000781F8;
extern s32 D_00078200;
extern f32 D_00078208;
extern f32 D_0007820C;
extern f32 D_00078230;
extern f32 D_00078238;
extern f32 D_00078240;
extern f32 D_00078248;
extern s32 D_00078250;
extern f32 D_00078258;
extern s32 D_0007825C;
extern f32 D_00078260;
extern f32 D_00078270;
extern f32 D_00078278;
extern f32 D_00078280;
extern f32 D_00078288;
extern s32 D_00078290;
extern f32 D_00078298;
extern s32 D_0007829C;
extern f32 D_000782A0;
extern s32 D_000782A8;
extern s32 D_000782B0;
extern s32 D_000782B8;
extern s32 D_000782BC;
extern s32 D_00078320;
extern s32 D_00078324;
extern s32 D_00078338;
extern s32 D_0007833C;
extern s32 D_000783A0;
extern s32 D_000783A4;
extern f32 D_00078410;
extern f32 D_00078418;
extern f32 D_00078420;
extern f32 D_00078428;
extern f32 D_00078430;
extern f32 D_00078438;
extern f32 D_00078470;
extern f32 D_00078478;
extern f32 D_00078480;
extern f32 D_00078488;
extern f32 D_000784E0;
extern f32 D_000784E8;
extern f32 D_000784F0;
extern f32 D_000784F4;
extern f32 D_000784F8;
extern f32 D_00078500;
extern f32 D_00078504;
extern f32 D_00078508;
extern f32 D_00078510;
extern f32 D_00078518;
extern f32 D_00078520;
extern f32 D_00078528;
extern f32 D_00078530;
extern f32 D_00078534;
extern f32 D_00078538;
extern f32 D_00078540;
extern f32 D_00078550;
extern f32 D_00078558;
extern f32 D_00078560;
extern s32 D_00078570;
extern f32 D_00078578;
extern f32 D_0007857C;
extern s32 D_00078580;
extern f32 D_00078588;
extern f32 D_0007858C;
extern f32 D_00078590;
extern f32 D_00078598;
extern f32 D_000785A0;
extern f32 D_000785A8;
extern f32 D_000785B0;
extern f32 D_000785B8;
extern s32 D_000785C0;
extern f32 D_000785C4;
extern f32 D_000785C8;
extern f32 D_000785CC;
extern s32 D_000785F0;
extern f32 D_000785F4;
extern f32 D_000785F8;
extern f32 D_000785FC;
extern s32 D_00078630;
extern f32 D_00078634;
extern f32 D_00078638;
extern f32 D_0007863C;
extern f32 D_00078660;
extern f32 D_00078668;
extern f32 D_00078670;
extern f32 D_00078674;
extern f32 D_00078678;
extern f32 D_00078680;
extern f32 D_00078688;
extern f32 D_0007868C;
extern f32 D_00078690;
extern f32 D_00078698;
extern s32 D_000786C0;
extern f32 D_000786C4;
extern f32 D_000786C8;
extern f32 D_000786CC;
extern f32 D_00078738;
extern f32 D_00078740;
extern f32 D_00078748;
extern f32 D_0007874C;
extern f32 D_00078750;
extern f32 D_00078758;
extern f32 D_00078760;
extern f32 D_00078768;
extern f32 D_00078770;
extern f32 D_00078778;
extern f32 D_000787A0;
extern f32 D_000787A8;
extern f32 D_000787B0;
extern f32 D_000787B8;
extern f32 D_00078B00;
extern f32 D_00078B08;
extern f32 D_00078B10;
extern f32 D_00078B14;
extern f32 D_00078B30;
extern f32 D_00078B38;
extern f32 D_00078B40;
extern f32 D_00078B48;
extern f32 D_00078B50;
extern f32 D_00078B54;
extern f32 D_00078B58;
extern f32 D_00078B60;
extern f32 D_00078B68;
extern f32 D_00078B6C;
extern f32 D_00078B70;
extern f32 D_00078B78;
extern f32 D_00078BC0;
extern f32 D_00078BC8;
extern s32 D_00078BD0;
extern f32 D_00078BD8;
extern f32 D_00078BDC;
extern s32 D_00078BE0;
extern f32 D_00078BE8;
extern f32 D_00078BEC;
extern s32 D_00078BF0;
extern f32 D_00078BF8;
extern f32 D_00078BFC;
extern s32 D_00078C00;
extern f32 D_00078C08;
extern f32 D_00078C0C;
extern f32 D_00078C10;
extern f32 D_00078C18;
extern f32 D_00078C20;
extern f32 D_00078C28;
extern f32 D_00078C30;
extern f32 D_00078C38;
extern f32 D_00078C40;
extern f32 D_00078C48;
extern f32 D_00078C50;
extern f32 D_00078C58;
extern f32 D_00078C60;
extern f32 D_00078C68;
extern f32 D_00078C70;
extern f32 D_00078C78;
extern u8 D_0007A574;
extern u8 D_0007A575;
extern f32 D_0007A778;
extern f32 D_0007A780;
extern s16 D_0007B404;
extern s16 D_0007B406;
extern s16 D_0007B408;
extern s16 D_0007B40A;
extern s16 D_0007B450;
extern s16 D_0007B452;
extern s16 D_0007B454;
extern s16 D_0007B456;
extern s16 D_0007B5A8;
extern s16 D_0007B5AA;
extern s16 D_0007B5FC;
extern s16 D_0007B5FE;
extern s16 D_0007E150;
extern s16 D_0007E152;
extern f32 D_0007E270;
extern f32 D_0007E274;
extern f32 D_0007E2F8;
extern f32 D_0007E2FC;
extern f32 D_0007E510;
extern f32 D_0007E518;
extern f32 D_0007E540;
extern f32 D_0007E548;
extern f32 D_0007E568;
extern f32 D_0007E570;
extern f32 D_0007E580;
extern f32 D_0007E584;
extern f32 D_0007E588;
extern f32 D_0007E590;
extern f32 D_0007E598;
extern f32 D_0007E5A0;
extern f32 D_0007E5A8;
extern f32 D_0007E5B0;
extern f32 D_0007E5B8;
extern f32 D_0007E5BC;
extern s32 D_0007E5D4;
extern s8 D_0007EB28;
extern s32 D_0007EB38;
extern s32 D_0007EB3C;
extern s32 D_0007EB40;
extern s32 D_0007F2D0;
extern s32 D_0007F2E0;
extern s32 D_0007F2E4;
extern s32 D_0007F300;
extern s32 D_0007F304;
extern s32 D_0007F308;
extern s32 D_0007F30C;
extern s32 D_0007F310;
extern s32 D_0007F314;
extern s32 D_0007F330;
extern s32 D_0007F334;
extern s32 D_0007F340;
extern s32 D_0008006C;
extern s32 D_00080070;
extern s32 D_00080074;
extern s32 D_000800BC;
extern s32 D_000800C8;
extern s32 D_0008DD20;
extern s32 D_0008DD24;
extern s32 D_000909D0;
extern s32 D_000909DC;
extern s32 D_000909E0;
extern s32 D_000909E4;
extern s32 D_00090BF0;
extern s32 D_00090BF4;
extern s32 D_00090C00;
extern s32 D_00090C04;
extern s32 D_00090C4C;
extern s32 D_00090C58;
extern s32 D_00090CA4;
extern s32 D_00090CD4;
extern s32 D_00090CDC;
extern s32 D_00090D20;
extern s32 D_00090D34;
extern s32 D_00090D70;
extern s32 D_00090D74;
extern s32 D_00090ED0;
extern s32 D_00090ED4;
extern s32 D_00090F40;
extern s32 D_00090F44;
extern s32 D_000910CC;
extern s32 D_000910E4;
extern s32 D_000910F0;
extern s32 D_000910F8;
extern s32 D_000910FC;
extern s32 D_00091114;
extern s32 D_00091648;
extern s32 D_0009164C;
extern s32 D_00091650;
extern s32 D_00091654;
extern f32 D_00091658;
extern f32 D_0009165C;
extern f32 D_00091660;
extern f32 D_00091668;
extern f32 D_0009166C;
extern s32 D_00091670;
extern s32 D_00091678;
extern s32 D_0009167C;
extern s32 D_00091680;
extern f32 D_00091684;
extern s32 D_00091688;
extern s32 D_0009168C;
extern f32 D_00091690;
extern s32 D_00091694;
extern s32 D_00091698;
extern s32 D_0009169C;
extern s32 D_000916A0;
extern s32 D_000916A4;
extern s32 D_000937A0;
extern s32 D_000937A4;
extern s32 D_000937A8;
extern s32 D_000938C8;
extern s32 D_00093ACC;
extern s32 D_00093AD0;
extern s32 D_00093AD4;
extern s32 D_00093AD8;
extern s32 D_00093ADC;
extern s32 D_00093AE0;
extern s32 D_00093AE4;
extern s32 D_00093AE8;
extern s32 D_00093AF8;
extern s32 D_00093AFC;
extern s32 D_00093B00;
extern s32 D_00093B04;
extern s32 D_00093B74;
extern s32 D_00093B78;
extern s32 D_00093B8C;
extern s32 D_00093B90;
extern s32 D_00093B94;
extern s32 D_000940E0;
extern s32 D_000940E4;
extern s32 D_000940F4;
extern s32 D_000940F8;
extern s32 D_000940FC;
extern s32 D_00094108;
extern s32 D_0009412C;
extern s32 D_00095530;
extern s32 D_00095538;
extern s32 D_0009553C;
extern f32 func_0000AAF4;
extern s32 func_0000B00C;
extern f32 func_0000B3E8;
extern s32 func_0000B3F4;
extern f32 func_0000B42C;
extern s32 func_00013B30;
extern s32 func_00015B74;
extern s32 func_00015B9C;
extern s32 func_0001839C;
extern s32 func_000183AC;
extern f32 jtbl_000747B8;
extern f32 jtbl_00074A60;

/* 1 accessed at more than one width — a union, or two
 * structs sharing a base. Decide these by hand before using them. */
/* extern ? D_000800B0;   seen as w1, w2 */

/* 620 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_0002000E; */
/* extern ? D_00074484; */
/* extern ? D_000745D4; */
/* extern ? D_0007473C; */
/* extern ? D_00074740; */
/* extern ? D_0007474C; */
/* extern ? D_0007548C; */
/* extern ? D_000754A0; */
/* extern ? D_000754B4; */
/* extern ? D_000754C8; */
/* extern ? D_0007563C; */
/* extern ? D_00075670; */
/* extern ? D_000756A0; */
/* extern ? D_00075764; */
/* extern ? D_0007576C; */
/* extern ? D_000757D8; */
/* extern ? D_000757DC; */
/* extern ? D_000757E0; */
/* extern ? D_00076ECC; */
/* extern ? D_00076F38; */
/* extern ? D_0007700C; */
/* extern ? D_00077024; */
/* extern ? D_00077038; */
/* extern ? D_00077050; */
/* extern ? D_00077068; */
/* extern ? D_00077078; */
/* extern ? D_00077088; */
/* extern ? D_0007709C; */
/* extern ? D_000770B0; */
/* extern ? D_000770C4; */
/* extern ? D_000770D4; */
/* extern ? D_000770E4; */
/* extern ? D_000770F4; */
/* extern ? D_00077104; */
/* extern ? D_00077114; */
/* extern ? D_00077124; */
/* extern ? D_00077134; */
/* extern ? D_00077148; */
/* extern ? D_00077158; */
/* extern ? D_00077168; */
/* extern ? D_00077178; */
/* extern ? D_00077188; */
/* extern ? D_000771C0; */
/* extern ? D_000771CC; */
/* extern ? D_000771D8; */
/* extern ? D_00077230; */
/* extern ? D_00077254; */
/* extern ? D_000773F8; */
/* extern ? D_0007745C; */
/* extern ? D_00077670; */
/* extern ? D_000776F0; */
/* extern ? D_00077770; */
/* extern ? D_00077784; */
/* extern ? D_00077798; */
/* extern ? D_00077A30; */
/* extern ? D_00077AE8; */
/* extern ? D_00077B50; */
/* extern ? D_00077BA0; */
/* extern ? D_00077BE0; */
/* extern ? D_00077C00; */
/* extern ? D_00077C10; */
/* extern ? D_00077C18; */
/* extern ? D_00077C30; */
/* extern ? D_00077CA0; */
/* extern ? D_00077D74; */
/* extern ? D_00077D94; */
/* extern ? D_00077D98; */
/* extern ? D_00077DB4; */
/* extern ? D_00077DD8; */
/* extern ? D_00077EC8; */
/* extern ? D_00077ED8; */
/* extern ? D_00077EE0; */
/* extern ? D_00077F90; */
/* extern ? D_00077FF8; */
/* extern ? D_00078000; */
/* extern ? D_00078008; */
/* extern ? D_00078010; */
/* extern ? D_000780B0; */
/* extern ? D_000780C0; */
/* extern ? D_000780D0; */
/* extern ? D_000781C0; */
/* extern ? D_000781D8; */
/* extern ? D_00078210; */
/* extern ? D_00078220; */
/* extern ? D_000782D0; */
/* extern ? D_00078328; */
/* extern ? D_00078350; */
/* extern ? D_000783A8; */
/* extern ? D_000783BC; */
/* extern ? D_000783CC; */
/* extern ? D_000783DC; */
/* extern ? D_000783F0; */
/* extern ? D_00078400; */
/* extern ? D_00078440; */
/* extern ? D_00078458; */
/* extern ? D_00078490; */
/* extern ? D_000785D0; */
/* extern ? D_00078600; */
/* extern ? D_00078640; */
/* extern ? D_0007869C; */
/* extern ? D_000786D0; */
/* extern ? D_000786FC; */
/* extern ? D_00078780; */
/* extern ? D_00078790; */
/* extern ? D_000787BC; */
/* extern ? D_000787CC; */
/* extern ? D_00078A54; */
/* extern ? D_00078B18; */
/* extern ? D_00078B80; */
/* extern ? D_00078B94; */
/* extern ? D_00078BAC; */
/* extern ? D_00078C80; */
/* extern ? D_0007901C; */
/* extern ? D_00079044; */
/* extern ? D_00079050; */
/* extern ? D_0007905C; */
/* extern ? D_00079088; */
/* extern ? D_00079408; */
/* extern ? D_00079804; */
/* extern ? D_00079B60; */
/* extern ? D_00079ED0; */
/* extern ? D_0007A2F8; */
/* extern ? D_0007A528; */
/* extern ? D_0007A530; */
/* extern ? D_0007A548; */
/* extern ? D_0007A55C; */
/* extern ? D_0007A578; */
/* extern ? D_0007A58C; */
/* extern ? D_0007A59C; */
/* extern ? D_0007A5A8; */
/* extern ? D_0007A5B4; */
/* extern ? D_0007A5C0; */
/* extern ? D_0007A5CC; */
/* extern ? D_0007A5D8; */
/* extern ? D_0007A5E4; */
/* extern ? D_0007A5F0; */
/* extern ? D_0007A5FC; */
/* extern ? D_0007A608; */
/* extern ? D_0007A614; */
/* extern ? D_0007A620; */
/* extern ? D_0007A62C; */
/* extern ? D_0007A630; */
/* extern ? D_0007A638; */
/* extern ? D_0007A64C; */
/* extern ? D_0007A65C; */
/* extern ? D_0007A670; */
/* extern ? D_0007A680; */
/* extern ? D_0007A690; */
/* extern ? D_0007A694; */
/* extern ? D_0007A69C; */
/* extern ? D_0007A6A8; */
/* extern ? D_0007A6C0; */
/* extern ? D_0007A6C8; */
/* extern ? D_0007A6D4; */
/* extern ? D_0007A6EC; */
/* extern ? D_0007A6FC; */
/* extern ? D_0007A70C; */
/* extern ? D_0007A718; */
/* extern ? D_0007A72C; */
/* extern ? D_0007A73C; */
/* extern ? D_0007A788; */
/* extern ? D_0007A78C; */
/* extern ? D_0007A790; */
/* extern ? D_0007A798; */
/* extern ? D_0007A8A0; */
/* extern ? D_0007AD34; */
/* extern ? D_0007B144; */
/* extern ? D_0007B40C; */
/* extern ? D_0007B44C; */
/* extern ? D_0007B458; */
/* extern ? D_0007B4A0; */
/* extern ? D_0007B4E8; */
/* extern ? D_0007B5AC; */
/* extern ? D_0007B600; */
/* extern ? D_0007B678; */
/* extern ? D_0007B67A; */
/* extern ? D_0007B6A0; */
/* extern ? D_0007B6A2; */
/* extern ? D_0007B6A8; */
/* extern ? D_0007B6B0; */
/* extern ? D_0007B6B8; */
/* extern ? D_0007B6DC; */
/* extern ? D_0007B6DE; */
/* extern ? D_0007B700; */
/* extern ? D_0007B710; */
/* extern ? D_0007B810; */
/* extern ? D_0007B8D0; */
/* extern ? D_0007B990; */
/* extern ? D_0007B994; */
/* extern ? D_0007B9F8; */
/* extern ? D_0007BA2C; */
/* extern ? D_0007BAFC; */
/* extern ? D_0007BB34; */
/* extern ? D_0007BB9C; */
/* extern ? D_0007BF1C; */
/* extern ? D_0007C2A0; */
/* extern ? D_0007C810; */
/* extern ? D_0007CCF0; */
/* extern ? D_0007D1D0; */
/* extern ? D_0007D6B0; */
/* extern ? D_0007DB90; */
/* extern ? D_0007E070; */
/* extern ? D_0007E130; */
/* extern ? D_0007E140; */
/* extern ? D_0007E148; */
/* extern ? D_0007E154; */
/* extern ? D_0007E19C; */
/* extern ? D_0007E1AC; */
/* extern ? D_0007E1BC; */
/* extern ? D_0007E1D4; */
/* extern ? D_0007E298; */
/* extern ? D_0007E300; */
/* extern ? D_0007E498; */
/* extern ? D_0007E5C0; */
/* extern ? D_0007E5CC; */
/* extern ? D_0007E608; */
/* extern ? D_0007E630; */
/* extern ? D_0007EB30; */
/* extern ? D_0007EB50; */
/* extern ? D_0007EB54; */
/* extern ? D_0007F318; */
/* extern ? D_0007F31C; */
/* extern ? D_0007F320; */
/* extern ? D_0007F344; */
/* extern ? D_00080090; */
/* extern ? D_000800A0; */
/* extern ? D_00080120; */
/* extern ? D_000909D4; */
/* extern ? D_00090B28; */
/* extern ? D_00090C08; */
/* extern ? D_00090CB0; */
/* extern ? D_00090CE4; */
/* extern ? D_00090CF4; */
/* extern ? D_00090D80; */
/* extern ? D_00090F4C; */
/* extern ? D_00091628; */
/* extern ? D_000916B0; */
/* extern ? D_00093674; */
/* extern ? D_00093690; */
/* extern ? D_000936D0; */
/* extern ? D_00093710; */
/* extern ? D_00093750; */
/* extern ? D_00093790; */
/* extern ? D_000938C4; */
/* extern ? D_00093AEC; */
/* extern ? D_00093B08; */
/* extern ? D_00093B0C; */
/* extern ? D_00093B1C; */
/* extern ? D_00094020; */
/* extern ? D_0009410C; */
/* extern ? D_00094124; */
/* extern ? D_00094130; */
/* extern ? D_00095540; */
/* extern ? D_1E5540; */
/* extern ? D_295550; */
/* extern ? D_395580; */
/* extern ? D_395650; */
/* extern ? D_395678; */
/* extern ? D_395680; */
/* extern ? D_3956BC; */
/* extern ? D_3956E0; */
/* extern ? D_395730; */
/* extern ? D_395778; */
/* extern ? D_395840; */
/* extern ? D_3958D8; */
/* extern ? D_395A20; */
/* extern ? D_395A6C; */
/* extern ? D_395D0C; */
/* extern ? D_395D58; */
/* extern ? D_395D64; */
/* extern ? D_395D7C; */
/* extern ? D_3962AC; */
/* extern ? D_3962B8; */
/* extern ? D_3962C0; */
/* extern ? D_3964D0; */
/* extern ? D_3964D4; */
/* extern ? D_396628; */
/* extern ? D_39663C; */
/* extern ? D_396850; */
/* extern ? D_396854; */
/* extern ? D_3968A0; */
/* extern ? D_396978; */
/* extern ? D_397608; */
/* extern ? D_397ABC; */
/* extern ? D_39844C; */
/* extern ? D_39847C; */
/* extern ? D_398484; */
/* extern ? D_398528; */
/* extern ? D_398538; */
/* extern ? D_398584; */
/* extern ? D_398618; */
/* extern ? D_398680; */
/* extern ? D_398748; */
/* extern ? D_398754; */
/* extern ? D_3987A0; */
/* extern ? D_39881C; */
/* extern ? D_398834; */
/* extern ? D_398868; */
/* extern ? D_3988B4; */
/* extern ? D_398940; */
/* extern ? D_398958; */
/* extern ? D_39898C; */
/* extern ? D_3989D8; */
/* extern ? D_398A64; */
/* extern ? D_3A1170; */
/* extern ? D_3A1174; */
/* extern ? D_3A11A4; */
/* extern ? D_3A13A8; */
/* extern ? D_3A13B0; */
/* extern ? ehsys_375A7F03; */
/* extern ? ehsys_E3C8F657; */
/* extern ? func_00003C48; */
/* extern ? func_00003E20; */
/* extern ? func_000041B8; */
/* extern ? func_00004210; */
/* extern ? func_00004364; */
/* extern ? func_00004410; */
/* extern ? func_0000465C; */
/* extern ? func_00004664; */
/* extern ? func_000068A8; */
/* extern ? func_000076A4; */
/* extern ? func_00007700; */
/* extern ? func_00007840; */
/* extern ? func_0000B668; */
/* extern ? func_0000E968; */
/* extern ? func_0000EA08; */
/* extern ? func_00015304; */
/* extern ? func_00015314; */
/* extern ? func_00015A30; */
/* extern ? func_00015B54; */
/* extern ? func_00015BF0; */
/* extern ? func_00016050; */
/* extern ? func_00016058; */
/* extern ? func_00018994; */
/* extern ? func_00018CD4; */
/* extern ? func_00018E3C; */
/* extern ? func_00018E78; */
/* extern ? func_00019168; */
/* extern ? func_000191AC; */
/* extern ? func_00019628; */
/* extern ? func_00019630; */
/* extern ? func_00019638; */
/* extern ? func_000197C8; */
/* extern ? func_00019C44; */
/* extern ? func_00019CF8; */
/* extern ? func_00019D00; */
/* extern ? func_00019F40; */
/* extern ? func_0001A138; */
/* extern ? func_0001A1F4; */
/* extern ? func_0001A1FC; */
/* extern ? func_0001A468; */
/* extern ? func_0001A864; */
/* extern ? func_0001A8A8; */
/* extern ? func_0001A8D4; */
/* extern ? func_0001B288; */
/* extern ? func_0001B364; */
/* extern ? func_0001B6BC; */
/* extern ? func_0001B70C; */
/* extern ? func_0001B714; */
/* extern ? func_0001B868; */
/* extern ? func_0001BA0C; */
/* extern ? func_0001BA64; */
/* extern ? func_0001BD3C; */
/* extern ? func_0001BD44; */
/* extern ? func_0001BDDC; */
/* extern ? func_0001BE80; */
/* extern ? func_0001BFC4; */
/* extern ? func_0001C138; */
/* extern ? func_0001C17C; */
/* extern ? func_0001C2C8; */
/* extern ? func_0001C490; */
/* extern ? func_0001C500; */
/* extern ? func_0001C898; */
/* extern ? func_0001C930; */
/* extern ? func_0001C968; */
/* extern ? func_0001CA60; */
/* extern ? func_0001CAB8; */
/* extern ? func_0001CB98; */
/* extern ? func_0001CD08; */
/* extern ? func_0001CD50; */
/* extern ? func_0001D0F8; */
/* extern ? func_0001DC64; */
/* extern ? func_0001E268; */
/* extern ? func_0001F348; */
/* extern ? func_000204A0; */
/* extern ? func_0002053C; */
/* extern ? func_00020E54; */
/* extern ? func_00020EA0; */
/* extern ? func_00021AEC; */
/* extern ? func_00021DE8; */
/* extern ? func_0002236C; */
/* extern ? func_00022680; */
/* extern ? func_00022E74; */
/* extern ? func_00023344; */
/* extern ? func_00023800; */
/* extern ? func_00023F28; */
/* extern ? func_00024410; */
/* extern ? func_00024EE8; */
/* extern ? func_00024F40; */
/* extern ? func_0002563C; */

#endif /* GLOBALS_REL_DUEL_DRAW_H */
