/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_CONV_MACHINE_H
#define GLOBALS_REL_CONV_MACHINE_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 21 globals with a type the binary determines */
extern f32 D_00008948;
extern f32 D_0000894C;
extern f32 D_00008950;
extern f32 D_00008960;
extern f32 D_00008968;
extern f32 D_00008970;
extern f32 D_00008974;
extern f32 D_00008978;
extern f32 D_0000897C;
extern s32 D_00008988;
extern s16 D_0000898C;
extern s16 D_0000898E;
extern s16 D_00008990;
extern s16 D_00008992;
extern s32 D_00008994;
extern s32 D_00008998;
extern f32 D_00009008;
extern f32 D_0000900C;
extern f32 D_00009010;
extern f32 D_00009018;
extern u8 D_00009030;

/* 34 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_000088F0; */
/* extern ? D_00008980; */
/* extern ? D_000089C8; */
/* extern ? D_00008C80; */
/* extern ? D_00008F28; */
/* extern ? D_00008FE8; */
/* extern ? D_00008FFC; */
/* extern ? D_00009034; */
/* extern ? D_47D410; */
/* extern ? D_47D420; */
/* extern ? D_47D460; */
/* extern ? D_47D468; */
/* extern ? D_47D4B4; */
/* extern ? D_47D558; */
/* extern ? D_47D5CC; */
/* extern ? D_47D5D4; */
/* extern ? D_7D040; */
/* extern ? D_7D054; */
/* extern ? D_7D058; */
/* extern ? D_7D05C; */
/* extern ? D_7D0A8; */
/* extern ? D_7D180; */
/* extern ? D_7D380; */
/* extern ? D_7D390; */
/* extern ? D_7D410; */
/* extern ? func_000006F0; */
/* extern ? func_00000780; */
/* extern ? func_000017DC; */
/* extern ? func_000018B8; */
/* extern ? func_000018C8; */
/* extern ? func_00001F98; */
/* extern ? jtbl_000088FC; */
/* extern ? jtbl_00008914; */
/* extern ? jtbl_00008930; */

#endif /* GLOBALS_REL_CONV_MACHINE_H */
