/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_LIMITLIST_H
#define GLOBALS_REL_LIMITLIST_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 46 globals with a type the binary determines */
extern s16 D_0000AB04;
extern s16 D_0000AB06;
extern s16 D_0000AB08;
extern s16 D_0000B030;
extern s16 D_0000B032;
extern s32 D_0000B038;
extern u16 D_0000B03C;
extern u16 D_0000B03E;
extern s32 D_0000B044;
extern u16 D_0000B048;
extern u16 D_0000B04A;
extern s32 D_0000B050;
extern u16 D_0000B054;
extern u16 D_0000B056;
extern s16 D_0000B06C;
extern s16 D_0000B06E;
extern u16 D_0000B074;
extern u16 D_0000B076;
extern u16 D_0000B078;
extern u16 D_0000B07A;
extern u16 D_0000B080;
extern u16 D_0000B082;
extern u16 D_0000B084;
extern u16 D_0000B086;
extern s16 D_0000B0A4;
extern s16 D_0000B0A6;
extern s16 D_0000B0A8;
extern s16 D_0000B0AC;
extern s16 D_0000B0AE;
extern s16 D_0000B0B0;
extern u16 D_0000B0D0;
extern u16 D_0000B0D2;
extern u8 D_0000B0D5;
extern s32 D_0000B0FC;
extern s32 D_0000B100;
extern s32 D_0000B104;
extern s32 D_0000B10C;
extern s32 D_0000B124;
extern s32 D_0000B128;
extern u16 D_0000B130;
extern u16 D_0000B132;
extern u8 D_0000B134;
extern s32 D_0000B538;
extern s32 D_0000B53C;
extern u8 D_0000B670;
extern s32 D_0000B674;

/* 1 accessed at more than one width — a union, or two
 * structs sharing a base. Decide these by hand before using them. */
/* extern ? D_0000B0D4;   seen as w1, w2 */

/* 26 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_0000AA74; */
/* extern ? D_0000AAAC; */
/* extern ? D_0000AAB0; */
/* extern ? D_0000AAD4; */
/* extern ? D_0000AADC; */
/* extern ? D_0000AB00; */
/* extern ? D_0000AB34; */
/* extern ? D_0000ADEC; */
/* extern ? D_0000B004; */
/* extern ? D_0000B028; */
/* extern ? D_0000B058; */
/* extern ? D_0000B088; */
/* extern ? D_0000B0D6; */
/* extern ? D_0000B0DC; */
/* extern ? D_0000B0E2; */
/* extern ? D_0000B0EA; */
/* extern ? D_0000B0F0; */
/* extern ? D_0000B138; */
/* extern ? D_0000B540; */
/* extern ? func_00001D14; */
/* extern ? func_00001DD4; */
/* extern ? func_00003150; */
/* extern ? func_000034C8; */
/* extern ? func_00003B18; */
/* extern ? jtbl_0000AA54; */
/* extern ? jtbl_0000AA7C; */

#endif /* GLOBALS_REL_LIMITLIST_H */
