/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_CARDALBUM_H
#define GLOBALS_REL_CARDALBUM_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 66 globals with a type the binary determines */
extern f32 D_0000C110;
extern f32 D_0000C114;
extern f32 D_0000C118;
extern f32 D_0000C120;
extern f32 D_0000C154;
extern f32 D_0000C158;
extern f32 D_0000C15C;
extern f32 D_0000C160;
extern f32 D_0000C168;
extern f32 D_0000C16C;
extern s16 D_0000C240;
extern s16 D_0000C242;
extern s16 D_0000C244;
extern s16 D_0000C246;
extern f32 D_0000C298;
extern f32 D_0000C2A0;
extern f32 D_0000C2A8;
extern f32 D_0000C2AC;
extern f32 D_0000C2B0;
extern f32 D_0000C2B8;
extern f32 D_0000C2C0;
extern f32 D_0000C2C8;
extern f32 D_0000C2D0;
extern f32 D_0000C2D8;
extern u8 D_0000CA72;
extern u8 D_0000CA73;
extern s32 D_0000CA74;
extern u8 D_0000CA78;
extern s32 D_0000CA7C;
extern u8 D_0000CA80;
extern u8 D_0000CA81;
extern s32 D_0000CA84;
extern s32 D_0000CA88;
extern s32 D_0000CA8C;
extern s32 D_0000CA90;
extern s32 D_0000CA94;
extern u8 D_0000CAD0;
extern s32 D_0000CAF8;
extern s32 D_0000CAFC;
extern s32 D_0000CB00;
extern u16 D_0000CB10;
extern u16 D_0000CB12;
extern u8 D_0000CB14;
extern s32 D_0000CB18;
extern u16 D_0000CB1C;
extern u16 D_0000CB1E;
extern u16 D_0000F032;
extern f32 D_0000F034;
extern u8 D_0000F038;
extern u8 D_0000F039;
extern s32 D_0000F03C;
extern f32 D_0000F040;
extern f32 D_0000F044;
extern u8 D_0000F048;
extern u16 D_0000F04A;
extern f32 D_0000F04C;
extern u8 D_0000F050;
extern s32 D_0000F054;
extern s32 D_0000F05C;
extern s32 D_0000F074;
extern s32 D_0000F078;
extern s32 D_0000F07C;
extern s32 D_0000F080;
extern s32 D_0000F084;
extern u16 D_0000F088;
extern s32 D_0000FAF8;

/* 32 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_0000C198; */
/* extern ? D_0000C19C; */
/* extern ? D_0000C228; */
/* extern ? D_0000C234; */
/* extern ? D_0000C248; */
/* extern ? D_0000C27C; */
/* extern ? D_0000C2E0; */
/* extern ? D_0000C360; */
/* extern ? D_0000C364; */
/* extern ? D_0000C3F0; */
/* extern ? D_0000C694; */
/* extern ? D_0000C96C; */
/* extern ? D_0000C9D0; */
/* extern ? D_0000C9E8; */
/* extern ? D_0000C9F0; */
/* extern ? D_0000C9F8; */
/* extern ? D_0000C9FC; */
/* extern ? D_0000CA00; */
/* extern ? D_0000CA58; */
/* extern ? D_0000CA70; */
/* extern ? D_0000CA98; */
/* extern ? D_0000CB20; */
/* extern ? D_0000F08C; */
/* extern ? func_00001C74; */
/* extern ? func_00002E24; */
/* extern ? func_00002E34; */
/* extern ? func_00002E44; */
/* extern ? func_00006354; */
/* extern ? func_000063E4; */
/* extern ? jtbl_0000C124; */
/* extern ? jtbl_0000C13C; */
/* extern ? jtbl_0000C174; */

#endif /* GLOBALS_REL_CARDALBUM_H */
