/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_FIELD_H
#define GLOBALS_REL_FIELD_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 368 globals with a type the binary determines */
extern f32 D_0003D1F0;
extern f32 D_0003D2B0;
extern f32 D_0003D2B4;
extern f32 D_0003D2B8;
extern f32 D_0003D330;
extern f32 D_0003D334;
extern f32 D_0003D338;
extern f32 D_0003D340;
extern f32 D_0003D344;
extern f32 D_0003D348;
extern f32 D_0003D34C;
extern f32 D_0003D380;
extern f32 D_0003D384;
extern f32 D_0003D388;
extern f32 D_0003D38C;
extern s16 D_0003D448;
extern s16 D_0003D44A;
extern s16 D_0003D44C;
extern s16 D_0003D44E;
extern s32 D_0003D450;
extern s16 D_0003D454;
extern s16 D_0003D456;
extern s16 D_0003D458;
extern s16 D_0003D45A;
extern s32 D_0003D45C;
extern f32 D_0003D470;
extern f32 D_0003D474;
extern f32 D_0003D478;
extern f32 D_0003D480;
extern f32 D_0003D484;
extern f32 D_0003D488;
extern f32 D_0003D48C;
extern f32 D_0003D490;
extern f32 D_0003D494;
extern f32 D_0003D498;
extern f32 D_0003D49C;
extern s32 D_0003D4A0;
extern s32 D_0003D4A4;
extern s32 D_0003D4A8;
extern s32 D_0003D4AC;
extern s32 D_0003D4B0;
extern s32 D_0003D4B4;
extern f32 D_0003D4B8;
extern f32 D_0003D4BC;
extern f32 D_0003D4C0;
extern f32 D_0003D4C4;
extern f32 D_0003D868;
extern f32 D_0003D88C;
extern f32 D_0003D890;
extern f32 D_0003DA20;
extern f32 D_0003DA24;
extern f32 D_0003E328;
extern f32 D_0003E32C;
extern f32 D_0003E330;
extern f32 D_0003E334;
extern f32 D_0003E338;
extern s16 D_0003E344;
extern s16 D_0003E346;
extern s16 D_0003E348;
extern s16 D_0003E34A;
extern s16 D_0003E34C;
extern s16 D_0003E34E;
extern s16 D_0003E350;
extern s16 D_0003E352;
extern f32 D_0003E35C;
extern f32 D_0003E360;
extern s32 D_0003E3C0;
extern s16 D_0003E3C4;
extern s16 D_0003E3C6;
extern s16 D_0003E3C8;
extern s16 D_0003E3CA;
extern s32 D_0003E3CC;
extern s32 D_0003E3D0;
extern f32 D_0003E5A0;
extern f32 D_0003E5A4;
extern f32 D_0003E5A8;
extern f32 D_0003E5AC;
extern f32 D_0003E5B0;
extern f32 D_0003E5B8;
extern f32 D_0003E5BC;
extern f32 D_0003E5C0;
extern f32 D_0003E758;
extern f32 D_0003E75C;
extern f32 D_0003E760;
extern f32 D_0003E764;
extern s32 D_0003E768;
extern s32 D_0003E76C;
extern s32 D_0003E770;
extern s32 D_0003E774;
extern s32 D_0003E778;
extern s32 D_0003E77C;
extern s32 D_0003E780;
extern s32 D_0003E784;
extern s32 D_0003E888;
extern s32 D_0003E88C;
extern s32 D_00041900;
extern f32 D_000453E0;
extern f32 D_000453E8;
extern f32 D_000453F0;
extern f32 D_000453F8;
extern f32 D_00045400;
extern f32 D_00045408;
extern f32 D_00045410;
extern f32 D_00045418;
extern f32 D_00045420;
extern f32 D_00045428;
extern f32 D_00045430;
extern f32 D_00045438;
extern f32 D_00045440;
extern f32 D_00045448;
extern f32 D_00045450;
extern f32 D_00045458;
extern f32 D_00045DC0;
extern f32 D_00045DC8;
extern f32 D_00045DD0;
extern f32 D_00045DD8;
extern f32 D_00046438;
extern f32 D_00046440;
extern f32 D_00046448;
extern f32 D_00046458;
extern f32 D_00046460;
extern f32 D_00046468;
extern f32 D_00046470;
extern f32 D_00046478;
extern f32 D_00046480;
extern f32 D_00046878;
extern f32 D_00046880;
extern f32 D_00046888;
extern f32 D_00046890;
extern f32 D_00046898;
extern f32 D_000468A0;
extern s32 D_00047364;
extern s32 D_00047370;
extern f32 D_00048260;
extern f32 D_00048268;
extern f32 D_00048448;
extern f32 D_00048450;
extern f32 D_00048458;
extern f32 D_00048460;
extern f32 D_00048468;
extern f32 D_00048470;
extern f32 D_00048478;
extern f32 D_00048480;
extern f32 D_00048488;
extern f32 D_00048490;
extern s16 D_00048CB8;
extern s16 D_00048CBA;
extern f32 D_000490F0;
extern f32 D_000490F8;
extern f32 D_00049100;
extern f32 D_00049104;
extern s16 D_00049138;
extern s16 D_0004913A;
extern s32 D_00049150;
extern s32 D_00049154;
extern s32 D_00049158;
extern s32 D_0004915C;
extern s32 D_00049160;
extern s32 D_00049164;
extern f32 D_000491F0;
extern f32 D_000491F8;
extern f32 D_00049230;
extern f32 D_00049238;
extern f32 D_000494B4;
extern f32 D_000494B8;
extern f32 D_000494C0;
extern f32 D_000494C8;
extern f32 D_00049588;
extern f32 D_00049590;
extern f32 D_000495C0;
extern f32 D_000495C8;
extern f32 D_00049618;
extern f32 D_00049620;
extern f32 D_00049628;
extern f32 D_0004962C;
extern f32 D_00049648;
extern f32 D_00049650;
extern f32 D_00049658;
extern f32 D_00049660;
extern s32 D_00049800;
extern s32 D_00049804;
extern f32 D_00049808;
extern f32 D_00049810;
extern f32 D_00049818;
extern f32 D_0004981C;
extern f32 D_00049820;
extern f32 D_00049828;
extern f32 D_00049830;
extern f32 D_00049834;
extern f32 D_0004BE10;
extern f32 D_0004BE18;
extern f32 D_0004BE30;
extern f32 D_0004BE38;
extern s32 D_0004BE3C;
extern s32 D_0004BE40;
extern s32 D_0004BE44;
extern s32 D_0004BE48;
extern s32 D_0004BE4C;
extern s32 D_0004BE50;
extern s16 D_0004BF70;
extern s16 D_0004BF72;
extern s16 D_0004BF74;
extern f32 D_0004BFD0;
extern f32 D_0004BFD8;
extern s16 D_0004BFDC;
extern s16 D_0004BFDE;
extern s16 D_0004BFE0;
extern s32 D_0004C000;
extern s32 D_00052860;
extern s32 D_00052864;
extern s32 D_000528D0;
extern s32 D_000528D4;
extern s32 D_000528D8;
extern s32 D_000528DC;
extern s32 D_000528E0;
extern s32 D_00052910;
extern s32 D_00053444;
extern s32 D_00053460;
extern s32 D_00053468;
extern u16 D_0005346C;
extern u16 D_0005346E;
extern u16 D_00053470;
extern u16 D_00053472;
extern u16 D_00053474;
extern u16 D_00053476;
extern s32 D_00053478;
extern s32 D_0005347C;
extern u16 D_00053480;
extern u16 D_00053482;
extern s32 D_00053484;
extern s32 D_00053488;
extern s32 D_00053690;
extern s32 D_00053694;
extern s32 D_00053698;
extern s32 D_0005369C;
extern s32 D_000536A0;
extern s32 D_000536A4;
extern s32 D_000536A8;
extern s32 D_000536B0;
extern s32 D_000536D0;
extern s32 D_000536D4;
extern s32 D_000536D8;
extern s32 D_000536E8;
extern s32 D_00053704;
extern s32 D_00053854;
extern s32 D_00053858;
extern s32 D_0005385C;
extern s32 D_00053860;
extern s32 D_00053864;
extern u16 D_00053948;
extern s32 D_000539B0;
extern s32 D_000539CC;
extern s32 D_000539D0;
extern s32 D_000539D4;
extern s32 D_000539D8;
extern s32 D_000539DC;
extern s32 D_000539EC;
extern s32 D_000539F0;
extern s32 D_000539F4;
extern s32 D_000539F8;
extern s32 D_000539FC;
extern s32 D_00053A40;
extern s32 D_00054650;
extern s32 D_00054654;
extern s32 D_000546CC;
extern s32 D_000546D0;
extern s32 D_000546D4;
extern s32 D_000547D8;
extern s32 D_000547DC;
extern s32 D_000547E0;
extern s32 D_00054864;
extern s32 D_00054870;
extern s32 D_00054874;
extern s32 D_00054878;
extern s32 D_0005496C;
extern s32 D_00054A1C;
extern s32 D_00054A2C;
extern s32 D_00054A50;
extern s32 D_00054A54;
extern s32 D_00054A58;
extern s32 D_00054A60;
extern s32 D_00054A64;
extern s32 D_00054A68;
extern s32 D_00054B3C;
extern s32 D_00054B44;
extern f32 D_00054B48;
extern s32 D_00054B5C;
extern s32 D_00054B60;
extern s32 D_00054BC0;
extern s32 D_00054BD0;
extern s32 D_00054BD4;
extern s32 D_00054BD8;
extern s32 D_00054BDC;
extern s32 D_00054BE0;
extern s32 D_00054BE4;
extern s32 D_00054BE8;
extern s32 D_00054BEC;
extern s32 D_00054BF0;
extern s32 D_00054BF4;
extern s32 D_00054BFC;
extern s32 D_00054C08;
extern s32 D_00054C0C;
extern s32 D_00054C10;
extern s32 D_00054C14;
extern s32 D_00054C18;
extern s32 D_00054C20;
extern s32 D_00054C24;
extern s32 D_00054C2C;
extern s32 D_00055038;
extern s32 D_00055044;
extern s32 D_0005504C;
extern s32 D_00055050;
extern s32 D_0005505C;
extern f32 D_0005507C;
extern s32 D_00055080;
extern s32 D_00055084;
extern s32 D_00055098;
extern s32 D_000550A0;
extern s32 D_000550A4;
extern s32 D_0005F4B4;
extern s32 D_0005F4B8;
extern s32 D_0005F4C0;
extern s32 D_0005F4C4;
extern s32 D_0005F4C8;
extern s32 D_0005F5D0;
extern s32 D_0005F650;
extern s32 D_0005F654;
extern s32 D_0005F658;
extern s32 D_0005F65C;
extern s32 D_0005F660;
extern s32 D_0005F664;
extern s32 D_0005F668;
extern s32 D_0005F670;
extern s32 D_0005F678;
extern s32 D_0005F680;
extern s32 D_0005F684;
extern s32 D_0005F694;
extern s32 D_0005F6AC;
extern s32 D_0005F6B0;
extern s32 D_0005F6DC;
extern s32 D_0005F6E0;
extern s32 D_0005F6E8;
extern s32 D_0005F710;
extern s32 D_0005F714;
extern s32 D_0005F718;
extern s32 D_0005F71C;
extern s32 D_0005F720;
extern s32 D_0005F728;
extern s32 D_0005F74C;
extern s32 D_0005F758;
extern s32 D_0005F75C;
extern s32 D_0005F760;
extern s32 D_0005F764;
extern s32 D_0005F770;
extern s32 D_0005F780;
extern s32 D_0005F784;
extern s32 D_0005F890;
extern s32 D_0005F8A4;
extern s32 D_0005F8E0;
extern s32 D_0005F8E4;
extern s32 D_0005F8E8;
extern f32 D_0005F8F0;
extern f32 D_0005F8FC;
extern s32 D_0005F908;
extern s32 D_0005FE44;
extern s32 D_0005FE48;
extern s32 D_0005FE4C;
extern s32 func_0000A418;

/* 423 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_0003D044; */
/* extern ? D_0003D0F4; */
/* extern ? D_0003D120; */
/* extern ? D_0003D250; */
/* extern ? D_0003D2BC; */
/* extern ? D_0003D2C8; */
/* extern ? D_0003D390; */
/* extern ? D_0003D394; */
/* extern ? D_0003D408; */
/* extern ? D_0003D40C; */
/* extern ? D_0003D430; */
/* extern ? D_0003D460; */
/* extern ? D_0003D4C8; */
/* extern ? D_0003D4F4; */
/* extern ? D_0003D898; */
/* extern ? D_0003DAE8; */
/* extern ? D_0003DC80; */
/* extern ? D_0003DCE0; */
/* extern ? D_0003DD40; */
/* extern ? D_0003DD44; */
/* extern ? D_0003DD60; */
/* extern ? D_0003DD64; */
/* extern ? D_0003DD80; */
/* extern ? D_0003DD84; */
/* extern ? D_0003DDD8; */
/* extern ? D_0003DDDC; */
/* extern ? D_0003DE80; */
/* extern ? D_0003DE84; */
/* extern ? D_0003DF28; */
/* extern ? D_0003DF2C; */
/* extern ? D_0003DF30; */
/* extern ? D_0003DF34; */
/* extern ? D_0003E078; */
/* extern ? D_0003E120; */
/* extern ? D_0003E138; */
/* extern ? D_0003E150; */
/* extern ? D_0003E33C; */
/* extern ? D_0003E354; */
/* extern ? D_0003E364; */
/* extern ? D_0003E3B8; */
/* extern ? D_0003E4B8; */
/* extern ? D_0003E4E0; */
/* extern ? D_0003E558; */
/* extern ? D_0003E5C4; */
/* extern ? D_0003E5F8; */
/* extern ? D_0003E628; */
/* extern ? D_0003E788; */
/* extern ? D_0003E890; */
/* extern ? D_0003E8A8; */
/* extern ? D_00041ED0; */
/* extern ? D_00042078; */
/* extern ? D_00042084; */
/* extern ? D_00042090; */
/* extern ? D_0004209C; */
/* extern ? D_00042118; */
/* extern ? D_0004217C; */
/* extern ? D_00042180; */
/* extern ? D_00042184; */
/* extern ? D_000422A8; */
/* extern ? D_000422AC; */
/* extern ? D_000422CC; */
/* extern ? D_000422D0; */
/* extern ? D_00042A98; */
/* extern ? D_00042AAC; */
/* extern ? D_00042AB4; */
/* extern ? D_00045290; */
/* extern ? D_000453B0; */
/* extern ? D_000453BC; */
/* extern ? D_00045460; */
/* extern ? D_00045820; */
/* extern ? D_00045DE4; */
/* extern ? D_00046420; */
/* extern ? D_00046430; */
/* extern ? D_00046450; */
/* extern ? D_00046484; */
/* extern ? D_0004661C; */
/* extern ? D_00046628; */
/* extern ? D_00046634; */
/* extern ? D_00046644; */
/* extern ? D_00046650; */
/* extern ? D_00046660; */
/* extern ? D_0004666C; */
/* extern ? D_00046670; */
/* extern ? D_00046674; */
/* extern ? D_00046678; */
/* extern ? D_0004667C; */
/* extern ? D_00046860; */
/* extern ? D_00046870; */
/* extern ? D_0004735C; */
/* extern ? D_00047D04; */
/* extern ? D_00047FB8; */
/* extern ? D_00048148; */
/* extern ? D_00048220; */
/* extern ? D_0004822C; */
/* extern ? D_00048234; */
/* extern ? D_0004823C; */
/* extern ? D_00048244; */
/* extern ? D_0004824C; */
/* extern ? D_00048270; */
/* extern ? D_0004827C; */
/* extern ? D_00048288; */
/* extern ? D_00048294; */
/* extern ? D_000482A0; */
/* extern ? D_000482AC; */
/* extern ? D_000482B8; */
/* extern ? D_000482C8; */
/* extern ? D_000482F0; */
/* extern ? D_00048308; */
/* extern ? D_00048330; */
/* extern ? D_00048348; */
/* extern ? D_00048370; */
/* extern ? D_00048388; */
/* extern ? D_000483B0; */
/* extern ? D_000483C8; */
/* extern ? D_000483F0; */
/* extern ? D_00048408; */
/* extern ? D_00048430; */
/* extern ? D_00048498; */
/* extern ? D_000484A4; */
/* extern ? D_000484B0; */
/* extern ? D_000484C0; */
/* extern ? D_000484D0; */
/* extern ? D_000484DC; */
/* extern ? D_000484E8; */
/* extern ? D_000484F4; */
/* extern ? D_00048500; */
/* extern ? D_0004850C; */
/* extern ? D_00048518; */
/* extern ? D_00048528; */
/* extern ? D_00048538; */
/* extern ? D_00048544; */
/* extern ? D_00048550; */
/* extern ? D_00048554; */
/* extern ? D_00048594; */
/* extern ? D_0004859A; */
/* extern ? D_00048BE0; */
/* extern ? D_00048BF0; */
/* extern ? D_00048C10; */
/* extern ? D_00048C1C; */
/* extern ? D_00048C28; */
/* extern ? D_00048C40; */
/* extern ? D_00048C50; */
/* extern ? D_00048C54; */
/* extern ? D_00048C60; */
/* extern ? D_00048C70; */
/* extern ? D_00048C80; */
/* extern ? D_00048C90; */
/* extern ? D_00048CA0; */
/* extern ? D_00048CB0; */
/* extern ? D_00048CBC; */
/* extern ? D_00048CC4; */
/* extern ? D_00048CCC; */
/* extern ? D_00048CE0; */
/* extern ? D_00048CF0; */
/* extern ? D_00048D00; */
/* extern ? D_00048D14; */
/* extern ? D_00048D28; */
/* extern ? D_00048D60; */
/* extern ? D_00048E20; */
/* extern ? D_00048EE0; */
/* extern ? D_00048F18; */
/* extern ? D_00048F30; */
/* extern ? D_00048F40; */
/* extern ? D_00048F4C; */
/* extern ? D_00048F58; */
/* extern ? D_00048F64; */
/* extern ? D_00048F70; */
/* extern ? D_00048F7C; */
/* extern ? D_00048F88; */
/* extern ? D_00049028; */
/* extern ? D_00049048; */
/* extern ? D_00049068; */
/* extern ? D_000490BC; */
/* extern ? D_000490D8; */
/* extern ? D_00049108; */
/* extern ? D_0004913C; */
/* extern ? D_00049168; */
/* extern ? D_000491A4; */
/* extern ? D_000491AC; */
/* extern ? D_000491B4; */
/* extern ? D_000491BC; */
/* extern ? D_000491C4; */
/* extern ? D_000491D4; */
/* extern ? D_000491E8; */
/* extern ? D_00049200; */
/* extern ? D_0004923C; */
/* extern ? D_0004929C; */
/* extern ? D_000492EC; */
/* extern ? D_000493B4; */
/* extern ? D_000493EC; */
/* extern ? D_00049424; */
/* extern ? D_00049438; */
/* extern ? D_00049444; */
/* extern ? D_00049458; */
/* extern ? D_00049488; */
/* extern ? D_0004949C; */
/* extern ? D_00049530; */
/* extern ? D_00049538; */
/* extern ? D_00049540; */
/* extern ? D_00049548; */
/* extern ? D_00049550; */
/* extern ? D_00049558; */
/* extern ? D_00049564; */
/* extern ? D_00049578; */
/* extern ? D_00049580; */
/* extern ? D_00049594; */
/* extern ? D_000495CC; */
/* extern ? D_00049630; */
/* extern ? D_00049668; */
/* extern ? D_00049758; */
/* extern ? D_000497E8; */
/* extern ? D_00049B50; */
/* extern ? D_00049ED4; */
/* extern ? D_0004A444; */
/* extern ? D_0004A924; */
/* extern ? D_0004AE04; */
/* extern ? D_0004B2E4; */
/* extern ? D_0004B7C4; */
/* extern ? D_0004BCA4; */
/* extern ? D_0004BD64; */
/* extern ? D_0004BD74; */
/* extern ? D_0004BD7C; */
/* extern ? D_0004BD84; */
/* extern ? D_0004BD90; */
/* extern ? D_0004BD91; */
/* extern ? D_0004BDE4; */
/* extern ? D_0004BDF4; */
/* extern ? D_0004BDF6; */
/* extern ? D_0004BE1C; */
/* extern ? D_0004BE54; */
/* extern ? D_0004BEB8; */
/* extern ? D_0004BEC0; */
/* extern ? D_0004BEC8; */
/* extern ? D_0004BED0; */
/* extern ? D_0004BED8; */
/* extern ? D_0004BEE4; */
/* extern ? D_0004BEF0; */
/* extern ? D_0004BEFC; */
/* extern ? D_0004BF04; */
/* extern ? D_0004BF18; */
/* extern ? D_0004BF20; */
/* extern ? D_0004BF2C; */
/* extern ? D_0004BF38; */
/* extern ? D_0004BF44; */
/* extern ? D_0004BF50; */
/* extern ? D_0004BF60; */
/* extern ? D_0004BF78; */
/* extern ? D_0004BF90; */
/* extern ? D_0004BFA8; */
/* extern ? D_0004BFB8; */
/* extern ? D_00052040; */
/* extern ? D_00052868; */
/* extern ? D_000528BC; */
/* extern ? D_000536F8; */
/* extern ? D_00053720; */
/* extern ? D_00053728; */
/* extern ? D_00053730; */
/* extern ? D_0005377C; */
/* extern ? D_00053868; */
/* extern ? D_00053878; */
/* extern ? D_000538C4; */
/* extern ? D_00053A00; */
/* extern ? D_00053A10; */
/* extern ? D_00053A20; */
/* extern ? D_00053A30; */
/* extern ? D_00053A50; */
/* extern ? D_00054660; */
/* extern ? D_00054690; */
/* extern ? D_000546D8; */
/* extern ? D_00054840; */
/* extern ? D_0005487C; */
/* extern ? D_00054894; */
/* extern ? D_0005497C; */
/* extern ? D_0005498C; */
/* extern ? D_00054A08; */
/* extern ? D_00055088; */
/* extern ? D_0005F4D0; */
/* extern ? D_0005F630; */
/* extern ? D_0005F63C; */
/* extern ? D_0005F688; */
/* extern ? D_0005F790; */
/* extern ? D_0005F910; */
/* extern ? D_0005FA7C; */
/* extern ? D_0005FBE8; */
/* extern ? D_0005FC10; */
/* extern ? D_0005FC38; */
/* extern ? D_0005FC60; */
/* extern ? D_0005FDCC; */
/* extern ? D_0005FDF4; */
/* extern ? D_0005FE1C; */
/* extern ? D_0005FE20; */
/* extern ? D_0005FE60; */
/* extern ? D_B5FE60; */
/* extern ? D_B71070; */
/* extern ? D_B71E00; */
/* extern ? D_B74450; */
/* extern ? D_B74730; */
/* extern ? D_B74734; */
/* extern ? D_B74758; */
/* extern ? D_B74774; */
/* extern ? D_B747C0; */
/* extern ? D_B74858; */
/* extern ? D_B758E0; */
/* extern ? D_B75900; */
/* extern ? D_B75920; */
/* extern ? D_B7592C; */
/* extern ? D_B75940; */
/* extern ? D_B75948; */
/* extern ? D_B75994; */
/* extern ? D_B75A38; */
/* extern ? D_B75AAC; */
/* extern ? D_B75AB4; */
/* extern ? D_B75AC8; */
/* extern ? D_B75AE4; */
/* extern ? D_B75AF0; */
/* extern ? D_B7A6F4; */
/* extern ? D_B7AB00; */
/* extern ? D_B7AB2C; */
/* extern ? D_B7AB44; */
/* extern ? D_B7AD44; */
/* extern ? D_B7AF44; */
/* extern ? D_B7AF50; */
/* extern ? D_B7AF5C; */
/* extern ? D_B7AF6C; */
/* extern ? D_B7AFB8; */
/* extern ? D_B7B04C; */
/* extern ? D_B7B0B4; */
/* extern ? D_B7B17C; */
/* extern ? D_B7B188; */
/* extern ? D_B7B1D4; */
/* extern ? D_B7B250; */
/* extern ? D_B7B268; */
/* extern ? D_B7B29C; */
/* extern ? D_B7B2E8; */
/* extern ? D_B7B374; */
/* extern ? D_B7B38C; */
/* extern ? D_B7B3C0; */
/* extern ? D_B7B40C; */
/* extern ? func_00000038; */
/* extern ? func_00000138; */
/* extern ? func_00000388; */
/* extern ? func_00000390; */
/* extern ? func_00000EAC; */
/* extern ? func_00002990; */
/* extern ? func_00003DEC; */
/* extern ? func_000049B4; */
/* extern ? func_0000510C; */
/* extern ? func_00007028; */
/* extern ? func_00009D90; */
/* extern ? func_0000B06C; */
/* extern ? func_0000B2AC; */
/* extern ? func_0000B980; */
/* extern ? func_0000D0C8; */
/* extern ? func_0000D0E0; */
/* extern ? func_0000D650; */
/* extern ? func_0000D66C; */
/* extern ? func_0001165C; */
/* extern ? func_000116CC; */
/* extern ? func_000116DC; */
/* extern ? func_000116EC; */
/* extern ? func_00011A98; */
/* extern ? func_00011AB4; */
/* extern ? func_00013028; */
/* extern ? func_00013038; */
/* extern ? func_00014220; */
/* extern ? func_00014AE4; */
/* extern ? func_00014EF0; */
/* extern ? func_0001955C; */
/* extern ? func_00025EAC; */
/* extern ? func_00025EE4; */
/* extern ? func_00028208; */
/* extern ? func_0002AA98; */
/* extern ? func_0002EF58; */
/* extern ? func_0002FBC8; */
/* extern ? func_0002FC20; */
/* extern ? func_0002FD74; */
/* extern ? func_0002FDF4; */
/* extern ? func_0002FFE0; */
/* extern ? func_00030780; */
/* extern ? func_000307A0; */
/* extern ? func_00030968; */
/* extern ? func_00030AB4; */
/* extern ? func_00030BC4; */
/* extern ? func_00033DE4; */
/* extern ? jtbl_0003D154; */
/* extern ? jtbl_0003D170; */
/* extern ? jtbl_0003D190; */
/* extern ? jtbl_0003D1B0; */
/* extern ? jtbl_0003D1D0; */
/* extern ? jtbl_0003D1F4; */
/* extern ? jtbl_0003D308; */
/* extern ? jtbl_0003D350; */
/* extern ? jtbl_0003D368; */
/* extern ? jtbl_0003D4D8; */
/* extern ? jtbl_0003D86C; */
/* extern ? jtbl_0003D8FC; */
/* extern ? jtbl_0003D93C; */
/* extern ? jtbl_0003DA00; */
/* extern ? jtbl_0003DA28; */
/* extern ? jtbl_0003DA50; */

#endif /* GLOBALS_REL_FIELD_H */
