/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_DECKTUTORIAL_H
#define GLOBALS_REL_DECKTUTORIAL_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 192 globals with a type the binary determines */
extern s32 D_00026E4C;
extern s16 D_00026E50;
extern s16 D_00026E52;
extern s16 D_00026E54;
extern s16 D_00026E56;
extern s32 D_00026E58;
extern s32 D_00026E5C;
extern f32 D_00026E60;
extern u16 D_00027DEC;
extern u16 D_00027DEE;
extern u16 D_00027DF0;
extern f32 D_00027DF4;
extern s16 D_00027DF8;
extern u16 D_00027DFC;
extern u16 D_00027DFE;
extern u16 D_00027E00;
extern u16 D_00027E04;
extern u16 D_00027E06;
extern u16 D_00027E08;
extern f32 D_00027E0C;
extern s16 D_00027E10;
extern f32 D_00028170;
extern f32 D_00028188;
extern f32 D_0002818C;
extern f32 D_00028190;
extern f32 D_00028198;
extern f32 D_000281A0;
extern f32 D_000281A4;
extern u16 D_000284DC;
extern u16 D_000284DE;
extern u16 D_000284E0;
extern s16 D_00028568;
extern s16 D_0002856A;
extern s16 D_0002856C;
extern s16 D_0002856E;
extern s16 D_000286D8;
extern s16 D_000286DA;
extern s16 D_000286DC;
extern s16 D_00028C38;
extern s16 D_00028C3A;
extern s32 D_00028C40;
extern u16 D_00028C44;
extern u16 D_00028C46;
extern s32 D_00028C4C;
extern u16 D_00028C50;
extern u16 D_00028C52;
extern s32 D_00028C58;
extern u16 D_00028C5C;
extern u16 D_00028C5E;
extern s32 D_00028C64;
extern u16 D_00028C68;
extern u16 D_00028C6A;
extern s32 D_00028C70;
extern u16 D_00028C76;
extern s16 D_00028C8C;
extern s16 D_00028C8E;
extern u16 D_00028C94;
extern u16 D_00028C96;
extern u16 D_00028C98;
extern u16 D_00028C9A;
extern u16 D_00028CA0;
extern u16 D_00028CA2;
extern u16 D_00028CA4;
extern u16 D_00028CA6;
extern s16 D_00028CC4;
extern s16 D_00028CC6;
extern s16 D_00028CC8;
extern s16 D_00028CCC;
extern s16 D_00028CCE;
extern s16 D_00028CD0;
extern s16 D_00028CF0;
extern s16 D_00028CF2;
extern u8 D_00028D40;
extern s32 D_00028D44;
extern s32 D_00028D5C;
extern s32 D_00028D7C;
extern s32 D_00028D9C;
extern s32 D_00028DDC;
extern s32 D_00028DFC;
extern u16 D_00028E90;
extern u16 D_00028E92;
extern u8 D_00028E96;
extern u16 D_00028E98;
extern u16 D_00028E9A;
extern u16 D_00028E9E;
extern u16 D_00029370;
extern s32 D_000294CC;
extern s32 D_0002951C;
extern s32 D_00029520;
extern s32 D_00029524;
extern s32 D_00029530;
extern u8 D_00029541;
extern s32 D_00029544;
extern s32 D_00029548;
extern u8 D_0002954C;
extern u16 D_00029550;
extern u16 D_00029552;
extern u16 D_00029554;
extern s32 D_00029558;
extern s32 D_0002955C;
extern s32 D_00029564;
extern u8 D_0002957C;
extern s32 D_00029580;
extern u8 D_00029584;
extern u16 D_00029586;
extern u16 D_00029588;
extern u16 D_0002958A;
extern s16 D_0002958C;
extern s32 D_000295AC;
extern u8 D_000295B0;
extern u16 D_000295B2;
extern u16 D_000295B4;
extern u16 D_000295B6;
extern u16 D_00029CC0;
extern u16 D_00029CC2;
extern s32 D_00029CC4;
extern s32 D_00029CC8;
extern u8 D_00029CCC;
extern u8 D_00029CCD;
extern u16 D_00029CCE;
extern s32 D_00029CD0;
extern s32 D_00029CD4;
extern s32 D_00029CD8;
extern s32 D_00029CDC;
extern s32 D_00029CE0;
extern s32 D_00029CE4;
extern u16 D_00029D00;
extern u16 D_00029D02;
extern u16 D_00029D04;
extern u16 D_00029D06;
extern u16 D_00029D08;
extern s32 D_00029D0C;
extern u16 D_00029D10;
extern s32 D_00029D14;
extern s32 D_00029D18;
extern s32 D_00029D1C;
extern u16 D_00029D20;
extern u8 D_00029D22;
extern s16 D_00029D7C;
extern s16 D_00029D7E;
extern u8 D_00029E11;
extern u8 D_00029F34;
extern u8 D_00029F35;
extern u8 D_0002A059;
extern u8 D_0002A090;
extern u16 D_0002B7A8;
extern s32 D_0002B7AC;
extern s32 D_0002B7B0;
extern s32 D_0002B7B4;
extern u16 D_0002B7B8;
extern u16 D_0002B7BA;
extern u16 D_0002B7BC;
extern s32 D_0002B7C0;
extern s32 D_0002B7C4;
extern s32 D_0002B7C8;
extern s32 D_0002B7CC;
extern s32 D_0002B7D0;
extern u16 D_0002B7D4;
extern u16 D_0002B7D6;
extern u16 D_0002C0FC;
extern u8 D_0002C100;
extern s32 D_0002C104;
extern s32 D_0002C108;
extern s32 D_0002C10C;
extern u16 D_0002C16C;
extern u16 D_0002C16E;
extern u16 D_0002C180;
extern s32 D_0002C1DC;
extern s32 D_0002C1E0;
extern s32 D_0002C1E4;
extern s32 D_0002C1E8;
extern s32 D_0002C1EC;
extern s32 D_0002C1F0;
extern s32 D_0002C1F4;
extern s32 D_0002C1F8;
extern s32 D_0002C1FC;
extern s32 D_0002C200;
extern s32 D_0002C24C;
extern s32 D_0002C250;
extern s32 D_0002C254;
extern s32 D_0002C258;
extern s32 D_0002C25C;
extern s32 D_0002C260;
extern s32 D_0002C264;
extern s32 D_0002C268;
extern s32 D_0002C26C;
extern f32 D_0002C278;
extern f32 D_0002C27C;
extern f32 D_0002C280;
extern s32 D_0002C284;
extern f32 D_0002C288;
extern s32 D_0002C28C;

/* 4 accessed at more than one width — a union, or two
 * structs sharing a base. Decide these by hand before using them. */
/* extern ? D_00028E9C;   seen as u16, u8 */
/* extern ? D_00029494;   seen as s16, u16 */
/* extern ? D_00029540;   seen as u16, u8 */
/* extern ? D_00029D12;   seen as s16, u16 */

/* 140 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_00026BDC; */
/* extern ? D_00026D90; */
/* extern ? D_00026E44; */
/* extern ? D_00027A1C; */
/* extern ? D_00027A24; */
/* extern ? D_00027A2C; */
/* extern ? D_00027A34; */
/* extern ? D_00027ACC; */
/* extern ? D_00027D8C; */
/* extern ? D_00027EB0; */
/* extern ? D_00027F1C; */
/* extern ? D_00027F30; */
/* extern ? D_00027F34; */
/* extern ? D_00027FCC; */
/* extern ? D_00028010; */
/* extern ? D_000280C4; */
/* extern ? D_000280FC; */
/* extern ? D_0002811C; */
/* extern ? D_00028140; */
/* extern ? D_00028154; */
/* extern ? D_00028160; */
/* extern ? D_00028174; */
/* extern ? D_00028180; */
/* extern ? D_000281A8; */
/* extern ? D_00028270; */
/* extern ? D_000282DC; */
/* extern ? D_000282EC; */
/* extern ? D_0002832C; */
/* extern ? D_00028364; */
/* extern ? D_00028370; */
/* extern ? D_00028420; */
/* extern ? D_00028458; */
/* extern ? D_000284A0; */
/* extern ? D_000284AC; */
/* extern ? D_000284B8; */
/* extern ? D_000284E4; */
/* extern ? D_00028520; */
/* extern ? D_00028570; */
/* extern ? D_00028590; */
/* extern ? D_000285A0; */
/* extern ? D_000285C0; */
/* extern ? D_000285C8; */
/* extern ? D_000285DC; */
/* extern ? D_00028614; */
/* extern ? D_00028620; */
/* extern ? D_00028640; */
/* extern ? D_00028698; */
/* extern ? D_000286B4; */
/* extern ? D_000286E0; */
/* extern ? D_000286F8; */
/* extern ? D_00028704; */
/* extern ? D_00028718; */
/* extern ? D_000289C4; */
/* extern ? D_00028BB0; */
/* extern ? D_00028BC0; */
/* extern ? D_00028BC8; */
/* extern ? D_00028BD0; */
/* extern ? D_00028BD8; */
/* extern ? D_00028C1C; */
/* extern ? D_00028C28; */
/* extern ? D_00028C30; */
/* extern ? D_00028C78; */
/* extern ? D_00028CA8; */
/* extern ? D_00028CD4; */
/* extern ? D_00028CE0; */
/* extern ? D_00028CF4; */
/* extern ? D_00028D00; */
/* extern ? D_00028D0C; */
/* extern ? D_00028D50; */
/* extern ? D_00028D60; */
/* extern ? D_00028D70; */
/* extern ? D_00028D90; */
/* extern ? D_00028DB0; */
/* extern ? D_00028DD0; */
/* extern ? D_00028DF0; */
/* extern ? D_00028E10; */
/* extern ? D_00028EA0; */
/* extern ? D_00028EB0; */
/* extern ? D_00028F70; */
/* extern ? D_000293C2; */
/* extern ? D_000293CC; */
/* extern ? D_00029498; */
/* extern ? D_0002949C; */
/* extern ? D_000294D0; */
/* extern ? D_000295B8; */
/* extern ? D_000295D8; */
/* extern ? D_00029D24; */
/* extern ? D_00029E48; */
/* extern ? D_00029F6C; */
/* extern ? D_0002A094; */
/* extern ? D_0002B7D8; */
/* extern ? D_0002B824; */
/* extern ? D_0002B8FC; */
/* extern ? D_0002C114; */
/* extern ? D_0002C160; */
/* extern ? D_0002C204; */
/* extern ? func_000028B4; */
/* extern ? func_00002994; */
/* extern ? func_00002A74; */
/* extern ? func_00002C98; */
/* extern ? func_00002D6C; */
/* extern ? func_000034AC; */
/* extern ? func_0000353C; */
/* extern ? func_000065C4; */
/* extern ? func_00006948; */
/* extern ? func_00006AD4; */
/* extern ? func_00006B28; */
/* extern ? func_00006BB4; */
/* extern ? func_00007094; */
/* extern ? func_0000B220; */
/* extern ? func_0000B500; */
/* extern ? func_000165CC; */
/* extern ? func_00016A44; */
/* extern ? func_0001755C; */
/* extern ? func_0001758C; */
/* extern ? func_00017A0C; */
/* extern ? func_00017A94; */
/* extern ? func_00019088; */
/* extern ? func_00019138; */
/* extern ? func_00019328; */
/* extern ? func_000196A4; */
/* extern ? func_00019778; */
/* extern ? jtbl_00026BC0; */
/* extern ? jtbl_00026BE8; */
/* extern ? jtbl_00026C14; */
/* extern ? jtbl_00026C30; */
/* extern ? jtbl_00026C4C; */
/* extern ? jtbl_00026C64; */
/* extern ? jtbl_00026C90; */
/* extern ? jtbl_00026CAC; */
/* extern ? jtbl_00026CCC; */
/* extern ? jtbl_00026CF0; */
/* extern ? jtbl_00026D1C; */
/* extern ? jtbl_00026D34; */
/* extern ? jtbl_00026D4C; */
/* extern ? jtbl_00026D70; */
/* extern ? jtbl_00026D98; */
/* extern ? jtbl_00026DC8; */
/* extern ? jtbl_00026DEC; */
/* extern ? jtbl_00026E18; */

#endif /* GLOBALS_REL_DECKTUTORIAL_H */
