/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_RECIPEVIEWER_H
#define GLOBALS_REL_RECIPEVIEWER_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 40 globals with a type the binary determines */
extern f32 D_0000DDA4;
extern f32 D_0000DDA8;
extern s16 D_0000DE20;
extern s16 D_0000DE22;
extern s16 D_0000E364;
extern s16 D_0000E366;
extern u8 D_0000E385;
extern u16 D_0000E388;
extern u8 D_0000E38A;
extern u8 D_0000E5BC;
extern u8 D_0000E5BD;
extern u16 D_0000E5BE;
extern s32 D_0000E680;
extern s32 D_0000E688;
extern u16 D_0000E6A0;
extern s32 D_0000FB24;
extern s32 D_0000FB28;
extern s32 D_0001033C;
extern s32 D_00010340;
extern s32 D_00010344;
extern s32 D_00010348;
extern s32 D_0001034C;
extern s32 D_00010350;
extern s32 D_00010354;
extern s16 D_000103C6;
extern s32 D_00010420;
extern u8 D_00010424;
extern u8 D_0001042E;
extern u16 D_0001044E;
extern s32 D_0001047C;
extern s16 D_00010480;
extern s16 D_00010482;
extern u16 D_00010578;
extern s32 D_000105A8;
extern u8 D_000105B0;
extern s32 D_000105B4;
extern u8 D_000105B8;
extern s32 D_000105D8;
extern s32 D_00010764;
extern s32 D_00010768;

/* 2 accessed at more than one width — a union, or two
 * structs sharing a base. Decide these by hand before using them. */
/* extern ? D_0000E380;   seen as w1, w2 */
/* extern ? D_0000E384;   seen as w1, w2 */

/* 55 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_0000DD30; */
/* extern ? D_0000DD68; */
/* extern ? D_0000DD6C; */
/* extern ? D_0000DD78; */
/* extern ? D_0000DD90; */
/* extern ? D_0000DD9C; */
/* extern ? D_0000DDB0; */
/* extern ? D_0000DDC8; */
/* extern ? D_0000DE24; */
/* extern ? D_0000DE34; */
/* extern ? D_0000DE3C; */
/* extern ? D_0000DE6C; */
/* extern ? D_0000DE70; */
/* extern ? D_0000E124; */
/* extern ? D_0000E32C; */
/* extern ? D_0000E350; */
/* extern ? D_0000E358; */
/* extern ? D_0000E38E; */
/* extern ? D_0000E398; */
/* extern ? D_0000E39E; */
/* extern ? D_0000E5C0; */
/* extern ? D_0000E6A2; */
/* extern ? D_0000E6A4; */
/* extern ? D_0000E6A6; */
/* extern ? D_0000E6A7; */
/* extern ? D_0000E6A8; */
/* extern ? D_0000F357; */
/* extern ? D_0000F358; */
/* extern ? D_0000F992; */
/* extern ? D_0000FB31; */
/* extern ? D_0000FB32; */
/* extern ? D_0001032C; */
/* extern ? D_00010358; */
/* extern ? D_000103A4; */
/* extern ? D_00010484; */
/* extern ? D_000105BC; */
/* extern ? D_000105FC; */
/* extern ? D_00010630; */
/* extern ? D_00010662; */
/* extern ? func_00001BD8; */
/* extern ? func_000036B0; */
/* extern ? func_00003754; */
/* extern ? func_0000383C; */
/* extern ? func_00003940; */
/* extern ? func_000039E8; */
/* extern ? func_00003AD0; */
/* extern ? func_00003C10; */
/* extern ? func_00003CD4; */
/* extern ? func_00003E08; */
/* extern ? func_0000695C; */
/* extern ? func_00007074; */
/* extern ? jtbl_0000DCD4; */
/* extern ? jtbl_0000DCF4; */
/* extern ? jtbl_0000DD14; */
/* extern ? jtbl_0000DD38; */

#endif /* GLOBALS_REL_RECIPEVIEWER_H */
