/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_TUTORIALLIST_H
#define GLOBALS_REL_TUTORIALLIST_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 11 globals with a type the binary determines */
extern u8 D_00007C00;
extern s32 D_00007C04;
extern u16 D_00007C10;
extern u8 D_00007C14;
extern u16 D_00007C16;
extern u16 D_00007C20;
extern u16 D_00007C22;
extern u16 D_00007D08;
extern s32 D_00007D0C;
extern s32 D_00007D10;
extern s32 D_00007D14;

/* 11 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_00007B90; */
/* extern ? D_00007BC0; */
/* extern ? D_00007BDC; */
/* extern ? D_00007BE4; */
/* extern ? D_00007C18; */
/* extern ? D_00007C1C; */
/* extern ? D_00007C24; */
/* extern ? D_00007C26; */
/* extern ? D_00007CBC; */
/* extern ? func_000025A0; */
/* extern ? func_00002630; */

#endif /* GLOBALS_REL_TUTORIALLIST_H */
