/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_TITLE_H
#define GLOBALS_REL_TITLE_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 28 globals with a type the binary determines */
extern f32 D_00049DE8;
extern f32 D_0004AA04;
extern s32 D_0004B9F8;
extern s32 D_0004B9FC;
extern s32 D_0004BA00;
extern s16 D_0004EE50;
extern s16 D_0004EE52;
extern s16 D_0004EE54;
extern s16 D_0004EE56;
extern s16 D_0004EEE8;
extern s16 D_0004EEEA;
extern s16 D_0004EEEC;
extern s16 D_0004EEEE;
extern s32 D_000505E0;
extern s32 D_000505E4;
extern s32 D_000505E8;
extern s32 D_000505EC;
extern s32 D_000505F0;
extern s16 D_00050662;
extern s32 D_00050718;
extern s16 D_0005071C;
extern s16 D_0005071E;
extern s32 D_00050874;
extern u16 D_0005087C;
extern u8 D_0005169F;
extern s16 D_000516A4;
extern u8 D_00052B98;
extern s32 D_000543E4;

/* 267 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_0004AF50; */
/* extern ? D_0004AF6C; */
/* extern ? D_0004AF74; */
/* extern ? D_0004AF7C; */
/* extern ? D_0004AF88; */
/* extern ? D_0004AFB8; */
/* extern ? D_0004AFC8; */
/* extern ? D_0004AFE0; */
/* extern ? D_0004AFF8; */
/* extern ? D_0004B010; */
/* extern ? D_0004B36A; */
/* extern ? D_0004B656; */
/* extern ? D_0004B66C; */
/* extern ? D_0004B9C8; */
/* extern ? D_0004BA04; */
/* extern ? D_0004BAC4; */
/* extern ? D_0004BB84; */
/* extern ? D_0004BBEC; */
/* extern ? D_0004BC20; */
/* extern ? D_0004BCF0; */
/* extern ? D_0004BD28; */
/* extern ? D_0004BD90; */
/* extern ? D_0004BDF8; */
/* extern ? D_0004BE04; */
/* extern ? D_0004BE10; */
/* extern ? D_0004BE60; */
/* extern ? D_0004BEE0; */
/* extern ? D_0004BEF8; */
/* extern ? D_0004BF0C; */
/* extern ? D_0004BF24; */
/* extern ? D_0004BF7C; */
/* extern ? D_0004BF80; */
/* extern ? D_0004BF84; */
/* extern ? D_0004BF94; */
/* extern ? D_0004BF9C; */
/* extern ? D_0004C21C; */
/* extern ? D_0004C6DC; */
/* extern ? D_0004C91C; */
/* extern ? D_0004CC9C; */
/* extern ? D_0004D8FC; */
/* extern ? D_0004F028; */
/* extern ? D_0004F0BC; */
/* extern ? D_0004F0C8; */
/* extern ? D_0004F288; */
/* extern ? D_0004F290; */
/* extern ? D_0004F294; */
/* extern ? D_0004F29C; */
/* extern ? D_0004F2A0; */
/* extern ? D_0004F2B0; */
/* extern ? D_0004F2B8; */
/* extern ? D_0004F2C8; */
/* extern ? D_0004F2D0; */
/* extern ? D_0004F2D8; */
/* extern ? D_0004F2E8; */
/* extern ? D_0004F2F0; */
/* extern ? D_0004F300; */
/* extern ? D_0004F308; */
/* extern ? D_0004F328; */
/* extern ? D_0004F338; */
/* extern ? D_0004F348; */
/* extern ? D_0004F358; */
/* extern ? D_0004F360; */
/* extern ? D_0004F370; */
/* extern ? D_0004F378; */
/* extern ? D_0004F37C; */
/* extern ? D_0004F39C; */
/* extern ? D_0004F3A4; */
/* extern ? D_0004F3B0; */
/* extern ? D_0004F5B0; */
/* extern ? D_0004F7D8; */
/* extern ? D_0004FAD8; */
/* extern ? D_0004FADC; */
/* extern ? D_0004FC5C; */
/* extern ? D_0004FF1C; */
/* extern ? D_0005011C; */
/* extern ? D_00050184; */
/* extern ? D_000501CC; */
/* extern ? D_000501DC; */
/* extern ? D_000501EC; */
/* extern ? D_0005032C; */
/* extern ? D_000503C4; */
/* extern ? D_0005040C; */
/* extern ? D_00050418; */
/* extern ? D_00050448; */
/* extern ? D_00050458; */
/* extern ? D_00050478; */
/* extern ? D_00050480; */
/* extern ? D_000504C0; */
/* extern ? D_00050500; */
/* extern ? D_00050540; */
/* extern ? D_00050550; */
/* extern ? D_00050570; */
/* extern ? D_00050590; */
/* extern ? D_000505B0; */
/* extern ? D_000505C0; */
/* extern ? D_000505F4; */
/* extern ? D_00050720; */
/* extern ? D_00050844; */
/* extern ? D_00055030; */
/* extern ? D_C55030; */
/* extern ? D_C5503C; */
/* extern ? D_C55040; */
/* extern ? D_C55080; */
/* extern ? D_C550B4; */
/* extern ? D_C550E6; */
/* extern ? D_C551F0; */
/* extern ? D_C55244; */
/* extern ? D_C55380; */
/* extern ? func_0000241C; */
/* extern ? func_00008394; */
/* extern ? func_00008728; */
/* extern ? func_00008F58; */
/* extern ? func_00009138; */
/* extern ? func_0000D860; */
/* extern ? func_00011EA0; */
/* extern ? func_00012CA4; */
/* extern ? func_00012DC0; */
/* extern ? func_0001305C; */
/* extern ? func_00014BEC; */
/* extern ? func_00015224; */
/* extern ? func_00015F90; */
/* extern ? func_000177CC; */
/* extern ? func_0001B10C; */
/* extern ? func_0001B29C; */
/* extern ? func_0001B888; */
/* extern ? func_0001B97C; */
/* extern ? func_0001BB10; */
/* extern ? func_0001BCA8; */
/* extern ? func_0001BDA0; */
/* extern ? func_0001BF34; */
/* extern ? func_0001C6D8; */
/* extern ? func_0001D0F4; */
/* extern ? func_0001D46C; */
/* extern ? func_0001D5C8; */
/* extern ? func_0001D5E8; */
/* extern ? func_0001DEA8; */
/* extern ? func_0001E4B8; */
/* extern ? func_0001E87C; */
/* extern ? func_0001ED88; */
/* extern ? func_0001F398; */
/* extern ? func_0002A2C8; */
/* extern ? func_000387C8; */
/* extern ? func_00038AC0; */
/* extern ? func_00039F60; */
/* extern ? func_00041478; */
/* extern ? func_00041CE8; */
/* extern ? func_0004206C; */
/* extern ? func_00043204; */
/* extern ? func_000434DC; */
/* extern ? jtbl_00049A00; */
/* extern ? jtbl_00049AC0; */
/* extern ? jtbl_00049AD8; */
/* extern ? jtbl_00049B98; */
/* extern ? jtbl_00049BBC; */
/* extern ? jtbl_00049BE0; */
/* extern ? jtbl_00049BF8; */
/* extern ? jtbl_00049C10; */
/* extern ? jtbl_00049C30; */
/* extern ? jtbl_00049C70; */
/* extern ? jtbl_00049CA8; */
/* extern ? jtbl_00049CC4; */
/* extern ? jtbl_00049CDC; */
/* extern ? jtbl_00049D00; */
/* extern ? jtbl_00049D18; */
/* extern ? jtbl_00049D48; */
/* extern ? jtbl_00049D60; */
/* extern ? jtbl_00049D80; */
/* extern ? jtbl_00049DB4; */
/* extern ? jtbl_00049DEC; */
/* extern ? jtbl_00049E28; */
/* extern ? jtbl_00049E64; */
/* extern ? jtbl_00049E84; */
/* extern ? jtbl_00049EA4; */
/* extern ? jtbl_00049ECC; */
/* extern ? jtbl_00049EF4; */
/* extern ? jtbl_00049F14; */
/* extern ? jtbl_00049F58; */
/* extern ? jtbl_00049F78; */
/* extern ? jtbl_00049F98; */
/* extern ? jtbl_00049FB4; */
/* extern ? jtbl_00049FD0; */
/* extern ? jtbl_00049FEC; */
/* extern ? jtbl_0004A008; */
/* extern ? jtbl_0004A024; */
/* extern ? jtbl_0004A044; */
/* extern ? jtbl_0004A060; */
/* extern ? jtbl_0004A07C; */
/* extern ? jtbl_0004A09C; */
/* extern ? jtbl_0004A0BC; */
/* extern ? jtbl_0004A0DC; */
/* extern ? jtbl_0004A0FC; */
/* extern ? jtbl_0004A11C; */
/* extern ? jtbl_0004A140; */
/* extern ? jtbl_0004A180; */
/* extern ? jtbl_0004A1D0; */
/* extern ? jtbl_0004A220; */
/* extern ? jtbl_0004A250; */
/* extern ? jtbl_0004A26C; */
/* extern ? jtbl_0004A284; */
/* extern ? jtbl_0004A2AC; */
/* extern ? jtbl_0004A2E0; */
/* extern ? jtbl_0004A31C; */
/* extern ? jtbl_0004A334; */
/* extern ? jtbl_0004A350; */
/* extern ? jtbl_0004A36C; */
/* extern ? jtbl_0004A388; */
/* extern ? jtbl_0004A3A0; */
/* extern ? jtbl_0004A3CC; */
/* extern ? jtbl_0004A3F8; */
/* extern ? jtbl_0004A41C; */
/* extern ? jtbl_0004A448; */
/* extern ? jtbl_0004A460; */
/* extern ? jtbl_0004A4FC; */
/* extern ? jtbl_0004A520; */
/* extern ? jtbl_0004A538; */
/* extern ? jtbl_0004A558; */
/* extern ? jtbl_0004A57C; */
/* extern ? jtbl_0004A594; */
/* extern ? jtbl_0004A5B4; */
/* extern ? jtbl_0004A5D8; */
/* extern ? jtbl_0004A5F0; */
/* extern ? jtbl_0004A610; */
/* extern ? jtbl_0004A63C; */
/* extern ? jtbl_0004A654; */
/* extern ? jtbl_0004A674; */
/* extern ? jtbl_0004A710; */
/* extern ? jtbl_0004A73C; */
/* extern ? jtbl_0004A760; */
/* extern ? jtbl_0004A784; */
/* extern ? jtbl_0004A7A8; */
/* extern ? jtbl_0004A7CC; */
/* extern ? jtbl_0004A7E4; */
/* extern ? jtbl_0004A80C; */
/* extern ? jtbl_0004A898; */
/* extern ? jtbl_0004A920; */
/* extern ? jtbl_0004A93C; */
/* extern ? jtbl_0004A978; */
/* extern ? jtbl_0004AA08; */
/* extern ? jtbl_0004AA68; */
/* extern ? jtbl_0004AAF4; */
/* extern ? jtbl_0004AB44; */
/* extern ? jtbl_0004AB70; */
/* extern ? jtbl_0004AB9C; */
/* extern ? jtbl_0004ABC4; */
/* extern ? jtbl_0004ABEC; */
/* extern ? jtbl_0004AC14; */
/* extern ? jtbl_0004AC48; */
/* extern ? jtbl_0004AC60; */
/* extern ? jtbl_0004AC78; */
/* extern ? jtbl_0004AC90; */
/* extern ? jtbl_0004ACA8; */
/* extern ? jtbl_0004ACC0; */
/* extern ? jtbl_0004ACD8; */
/* extern ? jtbl_0004ACF0; */
/* extern ? jtbl_0004AD08; */
/* extern ? jtbl_0004AD20; */
/* extern ? jtbl_0004AD38; */
/* extern ? jtbl_0004AD5C; */
/* extern ? jtbl_0004AD74; */
/* extern ? jtbl_0004AD94; */
/* extern ? jtbl_0004ADB8; */
/* extern ? jtbl_0004ADF8; */
/* extern ? jtbl_0004AE1C; */
/* extern ? jtbl_0004AE48; */
/* extern ? jtbl_0004AE88; */
/* extern ? jtbl_0004AEC8; */
/* extern ? jtbl_0004AF34; */

#endif /* GLOBALS_REL_TITLE_H */
