/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_DUELRECORD_H
#define GLOBALS_REL_DUELRECORD_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 22 globals with a type the binary determines */
extern s16 D_00009BC8;
extern s16 D_00009BCA;
extern s16 D_00009BCC;
extern s16 D_00009BCE;
extern u8 D_0000A150;
extern u8 D_0000A152;
extern u8 D_0000A153;
extern u16 D_0000A154;
extern u16 D_0000A156;
extern u16 D_0000A158;
extern u16 D_0000A170;
extern u16 D_0000A172;
extern u16 D_0000A174;
extern s32 D_0000A178;
extern s32 D_0000A17C;
extern s32 D_0000A180;
extern s32 D_0000A184;
extern s32 D_0000A188;
extern s32 D_0000A18C;
extern s32 D_0000A190;
extern u8 D_0000A2F0;
extern s32 D_0000A2F4;

/* 8 accessed at more than one width — a union, or two
 * structs sharing a base. Decide these by hand before using them. */
/* extern ? D_0000A15E;   seen as s16, u16 */
/* extern ? D_0000A164;   seen as s16, u16 */
/* extern ? D_0000A166;   seen as s16, u16 */
/* extern ? D_0000A168;   seen as s16, u16 */
/* extern ? D_0000A16A;   seen as s16, u16 */
/* extern ? D_0000A16C;   seen as s16, u16 */
/* extern ? D_0000A16E;   seen as s16, u16 */
/* extern ? D_0000A176;   seen as s16, u16 */

/* 20 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_00009BC4; */
/* extern ? D_00009BD0; */
/* extern ? D_00009C18; */
/* extern ? D_00009C38; */
/* extern ? D_00009D10; */
/* extern ? D_00009D74; */
/* extern ? D_00009E00; */
/* extern ? D_00009F70; */
/* extern ? D_00009F94; */
/* extern ? D_00009FAC; */
/* extern ? D_00009FB4; */
/* extern ? D_0000A15A; */
/* extern ? D_0000A160; */
/* extern ? D_0000A198; */
/* extern ? func_00004634; */
/* extern ? func_00004694; */
/* extern ? jtbl_00009B34; */
/* extern ? jtbl_00009B58; */
/* extern ? jtbl_00009B7C; */
/* extern ? jtbl_00009BA0; */

#endif /* GLOBALS_REL_DUELRECORD_H */
