/* Generated by scripts/gen_types.py - do not edit.
 *
 * Each global's type is taken from the width EVERY instruction in the
 * module uses to access it, not guessed per function. Where the module
 * disagrees with itself the global is left commented out rather than
 * guessed, because a wrong width silently changes the load opcode and
 * breaks whichever function uses it.
 */
#ifndef GLOBALS_REL_SHOP_H
#define GLOBALS_REL_SHOP_H

typedef signed char s8;   typedef unsigned char u8;
typedef short s16;        typedef unsigned short u16;
typedef int s32;          typedef unsigned int u32;
typedef float f32;

/* 210 globals with a type the binary determines */
extern f32 D_0001ED98;
extern f32 D_0001ED9C;
extern f32 D_0001EDA0;
extern f32 D_0001EDA8;
extern f32 D_0001EDAC;
extern f32 D_0001EDB0;
extern f32 D_0001EDB4;
extern f32 D_0001EDD8;
extern f32 D_0001EDE0;
extern f32 D_0001EDE4;
extern f32 D_0001EDE8;
extern f32 D_0001EE30;
extern f32 D_0001EE38;
extern f32 D_0001EE40;
extern f32 D_0001EE48;
extern f32 D_0001EE50;
extern f32 D_0001EE58;
extern f32 D_0001EE5C;
extern f32 D_0001EE60;
extern f32 D_0001EE6C;
extern f32 D_0001EE70;
extern f32 D_0001EE78;
extern f32 D_0001EE7C;
extern f32 D_0001EF68;
extern f32 D_0001EF6C;
extern f32 D_0001EF70;
extern f32 D_0001EF78;
extern s16 D_0001EF88;
extern s16 D_0001EF8A;
extern s16 D_0001EF8C;
extern s16 D_0001EF8E;
extern s16 D_0001EF90;
extern s16 D_0001EF92;
extern s16 D_0001EF94;
extern s16 D_0001EF96;
extern f32 D_0001EFA0;
extern f32 D_0001EFA4;
extern f32 D_0001EFF8;
extern s32 D_0001F004;
extern s16 D_0001F008;
extern s16 D_0001F00A;
extern s16 D_0001F00C;
extern s16 D_0001F00E;
extern s32 D_0001F010;
extern s32 D_0001F014;
extern f32 D_0001F080;
extern f32 D_0001F088;
extern f32 D_0001F090;
extern f32 D_0001F098;
extern f32 D_0001F0A0;
extern f32 D_0001F0A8;
extern f32 D_0001F0B0;
extern f32 D_0001F0B8;
extern f32 D_0001F0C0;
extern f32 D_0001F0C8;
extern f32 D_0001F0D0;
extern f32 D_0001F0D8;
extern f32 D_0001F0E0;
extern f32 D_0001F0E8;
extern f32 D_0001F0F0;
extern f32 D_0001F0F8;
extern f32 D_0001F100;
extern f32 D_0001F108;
extern f32 D_0001F110;
extern f32 D_0001F118;
extern f32 D_0001F120;
extern f32 D_0001F128;
extern f32 D_0001F130;
extern f32 D_0001F138;
extern f32 D_0001F140;
extern f32 D_0001F148;
extern f32 D_0001F150;
extern f32 D_0001F158;
extern f32 D_0001F160;
extern f32 D_0001F168;
extern f32 D_0001F170;
extern f32 D_0001F178;
extern f32 D_0001F180;
extern f32 D_0001F188;
extern f32 D_0001F190;
extern f32 D_0001F198;
extern f32 D_0001F1A0;
extern f32 D_0001F1A8;
extern f32 D_0001F1B0;
extern f32 D_0001F1B8;
extern f32 D_0001F1D0;
extern f32 D_0001F1D8;
extern f32 D_0001F1DC;
extern f32 D_0001F1E0;
extern f32 D_0001F1E4;
extern f32 D_0001F1E8;
extern f32 D_0001F1F0;
extern f32 D_0001F1F4;
extern f32 D_0001F1F8;
extern f32 D_0001F200;
extern f32 D_0001F208;
extern f32 D_0001F210;
extern f32 D_0001F218;
extern s16 D_0001F234;
extern s16 D_0001F236;
extern f32 D_0001F240;
extern f32 D_0001F248;
extern f32 D_0001F250;
extern f32 D_0001F258;
extern f32 D_0001F260;
extern f32 D_0001F268;
extern f32 D_0001F270;
extern f32 D_0001F278;
extern f32 D_0001F280;
extern f32 D_0001F288;
extern f32 D_0001F290;
extern f32 D_0001F298;
extern f32 D_0001F2A0;
extern f32 D_0001F2A8;
extern f32 D_0001F2B0;
extern f32 D_0001F2B8;
extern f32 D_0001F2C0;
extern f32 D_0001F2C8;
extern f32 D_0001F2D0;
extern f32 D_0001F2D8;
extern f32 D_00023660;
extern f32 D_00023668;
extern s16 D_0002366C;
extern s16 D_0002366E;
extern s16 D_00023670;
extern s16 D_00023672;
extern f32 D_00023FC0;
extern f32 D_00023FC8;
extern s16 D_00023FD0;
extern s16 D_00023FD2;
extern s32 D_00023FD8;
extern u16 D_00023FDC;
extern u16 D_00023FDE;
extern s32 D_00023FE4;
extern u16 D_00023FE8;
extern u16 D_00023FEA;
extern s32 D_00023FF0;
extern u16 D_00023FF4;
extern u16 D_00023FF6;
extern s32 D_00023FFC;
extern u16 D_00024000;
extern u16 D_00024002;
extern s32 D_00024008;
extern u16 D_0002400E;
extern s16 D_00024024;
extern s16 D_00024026;
extern u16 D_0002402C;
extern u16 D_0002402E;
extern u16 D_00024030;
extern u16 D_00024032;
extern u16 D_00024038;
extern u16 D_0002403A;
extern u16 D_0002403C;
extern u16 D_0002403E;
extern s16 D_0002405C;
extern s16 D_0002405E;
extern s16 D_00024060;
extern s16 D_00024064;
extern s16 D_00024066;
extern s16 D_00024068;
extern s16 D_00024088;
extern s16 D_0002408A;
extern s32 D_000240A0;
extern s32 D_0002DF80;
extern u16 D_0002DF90;
extern u8 D_0002DF92;
extern u16 D_0002DF94;
extern s32 D_0002DF98;
extern u16 D_0002E014;
extern u8 D_0002E016;
extern u8 D_0002E017;
extern u16 D_0002E018;
extern u16 D_0002E01A;
extern u16 D_0002E01C;
extern f32 D_0002E030;
extern f32 D_0002E038;
extern u8 D_0002E03C;
extern u8 D_0002E03D;
extern u8 D_0002E0CC;
extern f32 D_0002E0D0;
extern f32 D_0002E0D8;
extern f32 D_0002E0E0;
extern f32 D_0002E0E8;
extern s32 D_0002E0EC;
extern f32 D_0002E0F0;
extern f32 D_0002E0F4;
extern f32 D_0002E0F8;
extern u8 D_0002EF40;
extern s32 D_0002EF44;
extern s32 D_0002EF48;
extern u16 D_0002EF4C;
extern u16 D_0002EF4E;
extern u16 D_0002EF50;
extern u16 D_0002EF52;
extern u16 D_0002EF54;
extern u16 D_0002EF56;
extern u16 D_0002EF58;
extern s32 D_0002F1A4;
extern s32 D_0002F1AC;
extern s32 D_0002F1C4;
extern s32 D_0002F1C8;
extern u16 D_0002F1CC;
extern u8 D_0002F1CE;
extern s32 D_0002F1D0;
extern u8 D_0002F1D4;
extern s32 D_0002F1D8;
extern s32 D_0002F1DC;
extern s32 D_0002F1E0;
extern s32 D_0002F1E4;
extern f32 jtbl_0001F018;

/* 94 only ever have their ADDRESS taken (arrays,
 * structs, string literals); the element type is not implied. */
/* extern ? D_0001EEE8; */
/* extern ? D_0001EF80; */
/* extern ? D_0001EF98; */
/* extern ? D_0001EFA8; */
/* extern ? D_0001F04C; */
/* extern ? D_0001F1C0; */
/* extern ? D_0001F220; */
/* extern ? D_0002305C; */
/* extern ? D_0002305D; */
/* extern ? D_00023060; */
/* extern ? D_00023062; */
/* extern ? D_00023064; */
/* extern ? D_00023338; */
/* extern ? D_00023480; */
/* extern ? D_00023484; */
/* extern ? D_00023694; */
/* extern ? D_00023800; */
/* extern ? D_000239A0; */
/* extern ? D_00023B0C; */
/* extern ? D_00023D14; */
/* extern ? D_00023E24; */
/* extern ? D_00023E28; */
/* extern ? D_00023E30; */
/* extern ? D_00023E38; */
/* extern ? D_00023E94; */
/* extern ? D_00023EA0; */
/* extern ? D_00023EA8; */
/* extern ? D_00023EB0; */
/* extern ? D_00023ECC; */
/* extern ? D_00023ED8; */
/* extern ? D_00023EFC; */
/* extern ? D_00023F1C; */
/* extern ? D_00023FCC; */
/* extern ? D_00024010; */
/* extern ? D_00024040; */
/* extern ? D_0002406C; */
/* extern ? D_00024078; */
/* extern ? D_000240A4; */
/* extern ? D_000240F0; */
/* extern ? D_000241D0; */
/* extern ? D_00024260; */
/* extern ? D_00024270; */
/* extern ? D_0002BD40; */
/* extern ? D_0002DF9C; */
/* extern ? D_0002E020; */
/* extern ? D_0002E040; */
/* extern ? D_0002E090; */
/* extern ? D_0002E100; */
/* extern ? D_0002E140; */
/* extern ? D_0002EF5C; */
/* extern ? D_0002F1F0; */
/* extern ? D_76F1F0; */
/* extern ? D_76F1FC; */
/* extern ? D_76F20C; */
/* extern ? D_76F240; */
/* extern ? D_76F260; */
/* extern ? D_8E7260; */
/* extern ? D_8E7264; */
/* extern ? D_8E7358; */
/* extern ? D_8E7378; */
/* extern ? D_8E7398; */
/* extern ? D_8E73A4; */
/* extern ? D_8E73B8; */
/* extern ? D_8E73C0; */
/* extern ? D_8E740C; */
/* extern ? D_8E74B0; */
/* extern ? D_8E7524; */
/* extern ? D_8E752C; */
/* extern ? func_000059A4; */
/* extern ? func_00009714; */
/* extern ? func_00009724; */
/* extern ? func_00009D50; */
/* extern ? func_0000A2A8; */
/* extern ? func_0000A36C; */
/* extern ? func_0000A3FC; */
/* extern ? func_0000A404; */
/* extern ? func_000101F8; */
/* extern ? func_00010C38; */
/* extern ? func_00010C64; */
/* extern ? func_00011094; */
/* extern ? func_0001111C; */
/* extern ? func_00013AE0; */
/* extern ? jtbl_0001ECF0; */
/* extern ? jtbl_0001ED44; */
/* extern ? jtbl_0001ED60; */
/* extern ? jtbl_0001ED7C; */
/* extern ? jtbl_0001EDB8; */
/* extern ? jtbl_0001EDF0; */
/* extern ? jtbl_0001EE0C; */
/* extern ? jtbl_0001EE80; */
/* extern ? jtbl_0001EEA8; */
/* extern ? jtbl_0001EECC; */
/* extern ? jtbl_0001EEF0; */
/* extern ? jtbl_0001EF2C; */

#endif /* GLOBALS_REL_SHOP_H */
