/* Engine (libehsys_rel) prototypes, generated by scripts/eboot_signatures.py
 * from the DISASSEMBLED BODIES in modehsys — not guessed from call sites.
 *
 * WHY THIS IS REFERENCE-ONLY, NOT AN INCLUDE FOR THE BUILD:
 * our sources declare engine imports K&R style, `extern int ehsys_X();`,
 * which accepts any argument list. Swapping in real prototypes changes
 * argument promotion and could silently regress matched functions, so this
 * header is documentation for drafting, not something to include blindly.
 * Use it to check a callee's arity BEFORE guessing one (the single biggest
 * cause of SIZE MISMATCH), then declare it however the module already does.
 *
 * argc is proven by register reads plus tail-call propagation; `reaches`
 * lists the SDK libraries the function eventually touches.
 */
#ifndef EHSYS_H
#define EHSYS_H

/* 1297x */
extern int ehsys_FDD168CA(int, int, int, int, int, int, int, int);
/* 1092x */
extern int ehsys_8EA6B1E7(int, int, int, int, int);
/* 1064x */
extern int ehsys_10F3BB61(int, int, int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 924x */
extern void ehsys_2AE3C0AD(int);
/* 632x */
extern int ehsys_CABEA834(int, int);
/* 622x */
extern int ehsys_E58C0FDC(int, int);
/* 570x */
extern void ehsys_9EA6989A(int, int);
/* 498x */
extern void ehsys_942B03D0(int, int);
/* 490x */
extern int ehsys_E5738C32(int);
/* 473x */
extern int ehsys_E6E4401F(int, int, int);
/* 458x */
extern int ehsys_F462EE6E(int, int);
/* 456x */
extern int ehsys_1EC5342B(int);
/* 447x */
extern int ehsys_DFCA450B(int, int);
/* 433x */
extern int ehsys_60B55A50(int);
/* 397x */
extern void ehsys_4F22C9AA(int);
/* 355x */
extern void ehsys_F2BD0694(void);
/* 339x */
extern int ehsys_4175E3DB(int, int);
/* 338x */
extern void ehsys_F8CDBCAB(void);
/* 336x */
extern int ehsys_B8AD96EA(int);
/* 335x */
extern int ehsys_A4AFF8E6(void);
/* 333x */
extern int ehsys_31454993(void);
/* 292x */
extern int ehsys_C6C15111(int, int, int);
/* 287x */
extern int ehsys_8171F765(int);
/* 267x */
extern int ehsys_D4DE5DD8(void);
/* 266x */
extern int ehsys_20E340D9(int);
/* 257x */
extern int ehsys_AB7592FF(int, int, int);
/* 253x */
extern void ehsys_9EFDC9B9(void);
/* 253x */
extern void ehsys_CF199BAE(void);
/* 240x */
extern void ehsys_A72D71BF(void);
/* 237x */
extern int ehsys_F5E3080C(void);
/* 228x */
extern int ehsys_B2B9FEFA(void);
/* 210x */
extern void ehsys_41AABF28(int, int);
/* 210x */
extern void ehsys_98E07D26(void);
/* 203x */
extern void ehsys_247C7989(int, int, int, int, int, int);
/* 203x */
extern void ehsys_48B2E54A(int, int);
/* reaches sceLibFont; 202x */
extern int ehsys_66F8E113(int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 188x */
extern int ehsys_39ADDA9F(int);
/* 186x */
extern int ehsys_23E69878(int, int);
/* 182x */
extern void ehsys_E62CCE79(void);
/* 180x */
extern int ehsys_A19EF6B5(int, int);
/* 178x */
extern void ehsys_747753B8(void);
/* reaches ThreadManForUser; 171x */
extern void ehsys_F1BC43DB(void);
/* 168x */
extern void ehsys_0089B865(int);
/* reaches Kernel_Library;sceGe_user; 166x */
extern int ehsys_13A4081A(int);
/* 164x */
extern int ehsys_FAA0B5CD(void);
/* 152x */
extern int ehsys_A38AA0E9(void);
/* 150x */
extern int ehsys_CC7A2A21(int);
/* 146x */
extern void ehsys_E1139F1A(int);
/* 145x */
extern int ehsys_025FE238(int, int);
/* 137x */
extern int ehsys_88B6C7F0(void);
/* 135x */
extern int ehsys_0D801700(void);
/* 131x */
extern int ehsys_09794DF0(int, int, int);
/* 130x */
extern int ehsys_5CBB9E43(int, int, int, int, int, int);
/* 123x */
extern int ehsys_EED9C836(void);
/* 117x */
extern int ehsys_295BF133(int);
/* 116x */
extern int ehsys_831C5769(int, int, int);
/* 114x */
extern int ehsys_133DA48C(void);
/* 111x */
extern int ehsys_7187E0F0(int, int, int);
/* reaches sceLibFont; 108x */
extern int ehsys_B89D38DC(int, int, int, int);
/* 105x */
extern void ehsys_C9D9E989(int);
/* 105x */
extern void ehsys_D853F15C(int);
/* reaches ThreadManForUser;sceAtrac3plus;sceLibFont;sceSas; 104x */
extern int ehsys_2012884C(int);
/* 102x */
extern void ehsys_C792FA38(int);
/* reaches Kernel_Library;SysMemUserForUser; 97x */
extern int ehsys_7661E728(int, int, int, int, int, int, int, int);
/* 96x */
extern void ehsys_B0F320E6(int);
/* reaches sceLibFont; 94x */
extern int ehsys_EF9B5D06(int, int);
/* 93x */
extern int ehsys_85F89FE8(int);
/* 93x */
extern int ehsys_67312719(void);
/* 91x */
extern int ehsys_89812D8A(int);
/* 91x */
extern int ehsys_6F2C8118(int, int);
/* 89x */
extern void ehsys_2EB1BD8B(int);
/* 88x */
extern void ehsys_D470D0B2(int, int, int);
/* 85x */
extern int ehsys_1738DF69(void);
/* 82x */
extern int ehsys_1460C6FD(void);
/* 80x */
extern void ehsys_5998BFD7(int, int, int);
/* 77x */
extern int ehsys_450CD6C5(void);
/* reaches Kernel_Library;sceGe_user;sceLibFont; 77x */
extern int ehsys_BC8E65D7(int, int, int, int, int);
/* 75x */
extern void ehsys_4BF558F1(int);
/* 73x */
extern int ehsys_1B00FB95(int, int, int, int);
/* 68x */
extern void ehsys_760919BF(void);
/* 66x */
extern int ehsys_20560342(int, int, int, int, int);
/* 64x */
extern int ehsys_D697947E(int, int, int);
/* 64x */
extern void ehsys_CE8B1945(int, int);
/* 64x */
extern int ehsys_4C4AB33C(void);
/* 63x */
extern int ehsys_13A603EB(int);
/* 60x */
extern int ehsys_82E739A4(int);
/* reaches Kernel_Library;SysMemUserForUser;sceLibFont; 59x */
extern int ehsys_C87BAB32(int, int, int, int, int, int, int, int);
/* 58x */
extern int ehsys_EC6F1CF2(int, int);
/* 57x */
extern int ehsys_399AC68A(int, int);
/* 57x */
extern int ehsys_42110BF9(int, int);
/* 57x */
extern int ehsys_ED7A3401(int, int);
/* 56x */
extern int ehsys_F1CE796C(int);
/* 56x */
extern int ehsys_E1359B02(int);
/* 55x */
extern int ehsys_885E0882(void);
/* 55x */
extern void ehsys_33ED567B(int);
/* 54x */
extern void ehsys_5739D1F8(int);
/* 54x */
extern int ehsys_7B1755CF(void);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 54x */
extern void ehsys_6367AE39(int);
/* reaches ThreadManForUser; 53x */
extern int ehsys_8288EEBC(int, int, int, int, int, int);
/* 53x */
extern int ehsys_1D98951B(int, int);
/* 53x */
extern int ehsys_E50B9594(int, int, int, int, int, int, int, int);
/* 52x */
extern int ehsys_21F9E97E(int, int);
/* 51x */
extern int ehsys_C62F9EAC(int, int);
/* 51x */
extern int ehsys_0D00F3B7(int);
/* 50x */
extern void ehsys_AD0E1E03(void);
/* 49x */
extern int ehsys_878EE1D3(int);
/* 49x */
extern int ehsys_2FD4863E(void);
/* 48x */
extern int ehsys_476FD94A(int);
/* 48x */
extern void ehsys_F59F3BD3(void);
/* 47x */
extern int ehsys_F293756B(int, int, int);
/* 47x */
extern void ehsys_249F5AD0(void);
/* 45x */
extern void ehsys_EF9740B0(int);
/* 45x */
extern int ehsys_ED818642(int);
/* reaches IoFileMgrForUser;Kernel_Library;SysMemUserForUse; 43x */
extern int ehsys_D2A768F4(int, int);
/* 42x */
extern int ehsys_558B2DCB(int);
/* 42x */
extern void ehsys_42C464D5(int);
/* 42x */
extern int ehsys_81857D14(int);
/* 41x */
extern void ehsys_4AA58320(int);
/* 41x */
extern void ehsys_AB962AE7(int);
/* 41x */
extern int ehsys_9D7372E0(int);
/* 40x */
extern int ehsys_4B0DABFA(int, int);
/* reaches sceRtc; 40x */
extern void ehsys_A200D82D(void);
/* 40x */
extern int ehsys_78191357(void);
/* 40x */
extern int ehsys_32ED1675(void);
/* 38x */
extern void ehsys_8634FBA0(void);
/* reaches ThreadManForUser; 38x */
extern void ehsys_C859D5FE(int);
/* reaches sceLibFont; 38x */
extern int ehsys_3BB2BAC6(int, int, int, int, int, int, int);
/* 38x */
extern int ehsys_D7AFA174(int);
/* 37x */
extern int ehsys_BA5DC138(int, int);
/* 37x */
extern void ehsys_F203CF01(void);
/* 37x */
extern void ehsys_BA0DA4DE(void);
/* 37x */
extern void ehsys_CEA78CA6(int);
/* 36x */
extern int ehsys_7AB35214(int, int, int);
/* 36x */
extern int ehsys_CD8623A1(int, int);
/* 36x */
extern int ehsys_FDAFCF3A(int, int);
/* 36x */
extern int ehsys_B4F2178B(void);
/* 36x */
extern int ehsys_7448DF81(void);
/* 34x */
extern void ehsys_FFA11C10(int, int);
/* 34x */
extern int ehsys_BB859AB5(int);
/* 33x */
extern int ehsys_28F7224B(void);
/* 33x */
extern void ehsys_FE91A2EC(int);
/* 32x */
extern int ehsys_C0AB8932(int, int);
/* 32x */
extern void ehsys_56D1651D(int, int);
/* 32x */
extern void ehsys_0941BAC6(int);
/* 32x */
extern void ehsys_D907D31A(int, int);
/* 32x */
extern int ehsys_630446E3(int);
/* 31x */
extern int ehsys_572A577B(int, int, int, int, int);
/* 31x */
extern int ehsys_5DF04F49(int);
/* 31x */
extern int ehsys_8477BA04(int, int);
/* 31x */
extern int ehsys_7B47DFE9(int);
/* 30x */
extern int ehsys_006C8EE8(int, int, int);
/* 30x */
extern void ehsys_B08EC132(void);
/* 30x */
extern void ehsys_30FECAEF(int, int);
/* 30x */
extern void ehsys_71B237CA(int);
/* 30x */
extern int ehsys_80896C1D(void);
/* 29x */
extern int ehsys_3DE5C8DC(int, int, int, int, int, int);
/* reaches sceLibFont; 29x */
extern int ehsys_50B8DF28(int, int);
/* 29x */
extern int ehsys_3C1C1F65(void);
/* 29x */
extern int ehsys_B27BC15D(int);
/* 29x */
extern void ehsys_93517477(int);
/* 28x */
extern int ehsys_D3890ECB(int, int, int);
/* reaches Kernel_Library;SysMemUserForUser; 28x */
extern int ehsys_1856E536(int, int);
/* 28x */
extern int ehsys_B401BB25(int);
/* 27x */
extern int ehsys_CFC58802(int, int);
/* 27x */
extern void ehsys_A3B7A6E9(void);
/* 27x */
extern int ehsys_97DD82F2(int, int, int, int, int, int);
/* 27x */
extern int ehsys_93EACD81(void);
/* 27x */
extern void ehsys_AA9913C7(int);
/* 27x */
extern int ehsys_68D242C5(int);
/* 26x */
extern int ehsys_89EE81BB(int, int, int);
/* 26x */
extern int ehsys_91EFFDC1(int, int);
/* 26x */
extern int ehsys_DCFC7586(int, int);
/* 26x */
extern int ehsys_0939B6BE(int, int, int, int, int);
/* 26x */
extern int ehsys_C3542E68(int);
/* 26x */
extern int ehsys_3A7E4F65(int, int, int);
/* 25x */
extern int ehsys_3E24ACE1(void);
/* reaches Kernel_Library;sceGe_user; 25x */
extern int ehsys_BB22B13B(int, int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 25x */
extern void ehsys_BE3756D0(int);
/* 25x */
extern void ehsys_960D020F(int, int);
/* 25x */
extern int ehsys_D934BB27(void);
/* 25x */
extern int ehsys_A677A57C(int);
/* re-export of sceGe_user:sceGeEdramGetAddr(); 25x */
extern void ehsys_E47E40E4(void);
/* 24x */
extern int ehsys_3EB35691(int, int);
/* 24x */
extern int ehsys_29D1B9D5(int);
/* 24x */
extern int ehsys_6786E0EF(int, int, int);
/* 24x */
extern int ehsys_C2E59A21(int, int, int);
/* 24x */
extern void ehsys_8CA1052F(void);
/* 24x */
extern int ehsys_9F25AE2F(int, int);
/* reaches sceLibFont; 24x */
extern int ehsys_14BFFB01(int, int);
/* 24x */
extern void ehsys_82249188(int);
/* 24x */
extern void ehsys_914562B0(int);
/* 23x */
extern int ehsys_F17C5C28(int, int, int);
/* 23x */
extern void ehsys_FCB00A02(int);
/* 23x */
extern int ehsys_40D6B29D(int, int, int, int, int, int);
/* 23x */
extern void ehsys_AB18E04A(int, int, int, int, int, int, int, int);
/* 23x */
extern int ehsys_1CBB2C1C(int, int);
/* 23x */
extern int ehsys_C1E38FF7(int, int, int);
/* 23x */
extern void ehsys_4D9EA10E(int);
/* 22x */
extern int ehsys_B693AF8E(int, int);
/* 22x */
extern int ehsys_4E8B47D4(void);
/* 22x */
extern int ehsys_D8A0DB10(void);
/* 22x */
extern void ehsys_7B8EF3EC(int, int);
/* 22x */
extern void ehsys_D9E13A6A(int, int);
/* 22x */
extern int ehsys_A4B2A31B(void);
/* 22x */
extern void ehsys_8CFD5EC1(int);
/* re-export of ThreadManForUser:sceKernelChangeCurrentThreadAttr(); 22x */
extern void ehsys_EA748E31(void);
/* 21x */
extern int ehsys_C8DF61CD(int, int, int, int);
/* 21x */
extern void ehsys_5DBE93DB(int);
/* 21x */
extern void ehsys_06A1D1D8(void);
/* 21x */
extern int ehsys_B2389187(int, int);
/* 21x */
extern int ehsys_B2584E43(int);
/* 21x */
extern void ehsys_735EA15C(int);
/* 20x */
extern void ehsys_B8A55300(int);
/* 20x */
extern int ehsys_81D0D1F7(int, int, int);
/* 20x */
extern int ehsys_767DE7AB(int, int);
/* 20x */
extern void ehsys_8F7249A7(int);
/* 20x */
extern int ehsys_2717C28C(int);
/* 20x */
extern int ehsys_101103B3(int);
/* 20x */
extern int ehsys_94A4EC34(int);
/* reaches sceLibFont; 20x */
extern int ehsys_5F00A362(int, int);
/* 20x */
extern void ehsys_A43AE5C3(void);
/* 20x */
extern void ehsys_97F24E9A(int, int);
/* 20x */
extern void ehsys_C4FA973E(int, int);
/* 20x */
extern void ehsys_481242AF(int, int, int);
/* reaches Kernel_Library;SysMemUserForUser; 20x */
extern int ehsys_8CBC1795(int);
/* 20x */
extern int ehsys_0A67ED6C(void);
/* 20x */
extern int ehsys_B92CF901(void);
/* 20x */
extern int ehsys_F05B1732(int);
/* 19x */
extern int ehsys_8B0A8B96(int, int);
/* reaches ModuleMgrForUser;sceUtility; 19x */
extern int ehsys_D767C29F(void);
/* 19x */
extern int ehsys_3765ED01(int, int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 19x */
extern void ehsys_D5D33185(int);
/* 19x */
extern int ehsys_96AEAC25(int);
/* 19x */
extern void ehsys_E9550159(int);
/* 19x */
extern int ehsys_9090346C(int, int, int);
/* 18x */
extern int ehsys_1FE543F1(int, int);
/* reaches ThreadManForUser;sceUtility; 18x */
extern void ehsys_96BC2DC8(int);
/* reaches sceLibFont; 18x */
extern int ehsys_8AC7E9E7(int);
/* 18x */
extern void ehsys_6B9DF7E8(int, int, int, int, int, int);
/* reaches sceNetAdhoc;sceNetAdhocMatching; 18x */
extern void ehsys_67953A3E(int);
/* 18x */
extern int ehsys_639AE71F(int);
/* 18x */
extern int ehsys_CFD504DA(void);
/* 17x */
extern int ehsys_348F1A33(int, int);
/* reaches IoFileMgrForUser;Kernel_Library;SysMemUserForUse; 17x */
extern int ehsys_6FFA2A28(int, int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 17x */
extern void ehsys_6E42DDCD(void);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 17x */
extern void ehsys_65DA0419(int);
/* 17x */
extern void ehsys_CA477B34(int, int);
/* 17x */
extern int ehsys_7EBDB800(void);
/* 17x */
extern int ehsys_B2FABBDD(int);
/* reaches Kernel_Library;SysMemUserForUser; 17x */
extern void ehsys_7F9073E5(int, int);
/* 17x */
extern int ehsys_B6B6E902(int);
/* 17x */
extern void ehsys_49C27DA2(int);
/* 16x */
extern void ehsys_711AC797(void);
/* reaches Kernel_Library;sceGe_user; 16x */
extern int ehsys_5DE4869F(int, int, int, int, int, int);
/* reaches Kernel_Library;sceGe_user; 16x */
extern int ehsys_B9064026(int);
/* 16x */
extern int ehsys_E2A5CE8D(int, int, int);
/* 16x */
extern void ehsys_5471DB90(void);
/* 16x */
extern int ehsys_D9951D8F(void);
/* reaches ThreadManForUser;sceLibFont; 16x */
extern int ehsys_FD84C4D3(int, int, int, int);
/* reaches ThreadManForUser; 16x */
extern int ehsys_291D6262(int, int, int);
/* reaches Kernel_Library;SysMemUserForUser;ThreadManForUse; 16x */
extern int ehsys_778817A2(void);
/* 16x */
extern void ehsys_82B715FD(int);
/* 16x */
extern void ehsys_06380DFA(int);
/* 16x */
extern int ehsys_0D961646(void);
/* 16x */
extern int ehsys_90281239(void);
/* 16x */
extern int ehsys_E9F3212D(int);
/* 16x */
extern int ehsys_16D9A578(int);
/* 16x */
extern int ehsys_6A96E306(int);
/* 16x */
extern int ehsys_327E7DA1(int);
/* 16x */
extern void ehsys_CC222EE8(int);
/* 15x */
extern void ehsys_317716E5(void);
/* 15x */
extern void ehsys_30CEF747(int, int);
/* 15x */
extern int ehsys_1CC5878C(int);
/* 15x */
extern int ehsys_F60A4259(int);
/* 15x */
extern int ehsys_BF4D5B0C(void);
/* 15x */
extern int ehsys_7A41135B(int);
/* 15x */
extern int ehsys_50266C2E(void);
/* 15x */
extern void ehsys_79487C92(int);
/* 15x */
extern void ehsys_41CA0A1C(int);
/* 14x */
extern int ehsys_F16047DB(int, int, int);
/* 14x */
extern void ehsys_0A0CC3A4(void);
/* 14x */
extern int ehsys_B4471B5E(int, int, int);
/* 14x */
extern int ehsys_D97274B6(void);
/* 14x */
extern int ehsys_0B962FD4(int);
/* 14x */
extern int ehsys_D1C6F209(void);
/* 14x */
extern int ehsys_C5D3B70C(int, int, int);
/* reaches ThreadManForUser;sceAtrac3plus;sceGe_user;sceLib; 14x */
extern int ehsys_C5BDA06E(void);
/* 14x */
extern void ehsys_ED17CBAC(void);
/* reaches sceLibFont; 14x */
extern int ehsys_97BB99A5(int, int, int, int);
/* 14x */
extern int ehsys_EA018EFE(int);
/* 14x */
extern int ehsys_442C88C6(void);
/* 14x */
extern int ehsys_916286F3(void);
/* 14x */
extern void ehsys_4DB996F6(int);
/* 14x */
extern void ehsys_3C9CB549(int);
/* re-export of ThreadManForUser:sceKernelCreateFpl(); 14x */
extern void ehsys_C07BB470(void);
/* re-export of ThreadManForUser:sceKernelDeleteFpl(); 14x */
extern void ehsys_ED1410E0(void);
/* re-export of ThreadManForUser:sceKernelAllocateFpl(); 14x */
extern void ehsys_D979E9BF(void);
/* 13x */
extern int ehsys_52DF196C(int);
/* 13x */
extern int ehsys_310DE5C7(int, int, int);
/* 13x */
extern int ehsys_45D54BCF(int, int);
/* 13x */
extern int ehsys_28633E5D(int);
/* reaches Kernel_Library;SysMemUserForUser; 13x */
extern int ehsys_1078C73B(int);
/* 13x */
extern int ehsys_A36635DA(int, int);
/* 13x */
extern void ehsys_EBD1986B(int, int);
/* 13x */
extern int ehsys_60BA0722(int);
/* 13x */
extern int ehsys_9490E557(int, int, int);
/* 13x */
extern int ehsys_4E722BBD(void);
/* 13x */
extern void ehsys_04E1CB0F(void);
/* 13x */
extern int ehsys_FA53F08C(int);
/* 13x */
extern int ehsys_31D0BD26(int, int);
/* 13x */
extern int ehsys_C8AF3744(int, int);
/* 13x */
extern int ehsys_5E149703(int, int);
/* 13x */
extern int ehsys_99FF9D51(void);
/* 12x */
extern int ehsys_411B4582(int);
/* 12x */
extern int ehsys_73918516(int, int);
/* 12x */
extern int ehsys_B56890DA(int, int, int);
/* 12x */
extern int ehsys_5C1AEE8E(int, int);
/* 12x */
extern void ehsys_CB6030CF(int);
/* 12x */
extern void ehsys_4510ECA2(int, int);
/* 12x */
extern void ehsys_BFFBA174(void);
/* 12x */
extern void ehsys_08813E19(int, int);
/* reaches Kernel_Library;ThreadManForUser;sceGe_user;sceLi; 12x */
extern int ehsys_C1F72EF5(void);
/* 12x */
extern void ehsys_2A501391(int, int);
/* 12x */
extern int ehsys_C57FD721(void);
/* 12x */
extern void ehsys_62FD685F(int, int);
/* 12x */
extern int ehsys_EA7396F6(void);
/* 12x */
extern int ehsys_B63981BD(int);
/* 12x */
extern int ehsys_5D9E6261(int);
/* 12x */
extern int ehsys_DA1BEA24(int, int);
/* 12x */
extern int ehsys_65B71542(int);
/* 12x */
extern void ehsys_58223517(int);
/* 12x */
extern void ehsys_AB8CF7CC(int);
/* 12x */
extern void ehsys_FE08B1FC(int);
/* 12x */
extern int ehsys_D83FB4E8(int, int);
/* re-export of ThreadManForUser:sceKernelFreeFpl(); 12x */
extern void ehsys_F6414A71(void);
/* 11x */
extern int ehsys_A025F5D0(int, int);
/* 11x */
extern int ehsys_B0BADD91(int, int);
/* 11x */
extern int ehsys_8C23C415(int, int, int);
/* 11x */
extern void ehsys_7812BD99(int);
/* 11x */
extern int ehsys_578BC0A3(int, int, int, int);
/* 11x */
extern int ehsys_F566A6A1(int, int, int, int);
/* 11x */
extern int ehsys_834A6E13(int);
/* 11x */
extern void ehsys_C721E899(void);
/* reaches sceLibFont; 11x */
extern int ehsys_50D6F57B(int, int, int);
/* reaches ThreadManForUser;sceAtrac3plus;sceLibFont;sceSas; 11x */
extern int ehsys_B779C0DF(void);
/* reaches Kernel_Library;SysMemUserForUser; 11x */
extern int ehsys_D1A604C7(int);
/* 11x */
extern int ehsys_C1BE453D(void);
/* 11x */
extern int ehsys_A69042CD(int);
/* 11x */
extern int ehsys_BDD2252D(void);
/* 11x */
extern void ehsys_C7137112(int);
/* 10x */
extern int ehsys_60054052(void);
/* 10x */
extern int ehsys_15BE7861(int, int, int);
/* 10x */
extern void ehsys_7D880441(void);
/* 10x */
extern int ehsys_42144DB8(int, int);
/* 10x */
extern int ehsys_312D660D(void);
/* 10x */
extern int ehsys_917CC4D5(int, int);
/* 10x */
extern int ehsys_53636C1D(void);
/* 10x */
extern int ehsys_D71FA940(int);
/* 10x */
extern int ehsys_A22C8F51(int, int);
/* 10x */
extern int ehsys_D6E0AA6A(int, int);
/* 10x */
extern void ehsys_465BB899(void);
/* reaches sceLibFont; 10x */
extern int ehsys_B7DFD65E(int, int, int, int, int, int);
/* 10x */
extern void ehsys_F6905EFA(int, int);
/* 10x */
extern int ehsys_A940A7F6(int, int);
/* 10x */
extern int ehsys_D46615D9(void);
/* 10x */
extern int ehsys_32CB2B73(int);
/* 10x */
extern int ehsys_0184D16D(int);
/* 10x */
extern int ehsys_2F061354(int);
/* 10x */
extern void ehsys_0E47B027(int);
/* 9x */
extern int ehsys_E71B4A22(int, int, int);
/* 9x */
extern int ehsys_8E537509(int, int);
/* 9x */
extern int ehsys_1673F2B1(int, int, int);
/* 9x */
extern int ehsys_758DE09D(int, int, int);
/* 9x */
extern void ehsys_723A097D(void);
/* reaches Kernel_Library;ThreadManForUser;sceGe_user;sceLi; 9x */
extern int ehsys_680BA5D6(int, int);
/* 9x */
extern int ehsys_551A8EF2(int, int, int);
/* 9x */
extern int ehsys_60ABAEE7(int);
/* 9x */
extern int ehsys_D7155BDE(int);
/* 9x */
extern void ehsys_D60CF578(int);
/* 9x */
extern void ehsys_51007C70(void);
/* 9x */
extern int ehsys_7002278E(void);
/* 9x */
extern void ehsys_45FA60B1(int);
/* 9x */
extern int ehsys_9753FA81(void);
/* 9x */
extern int ehsys_E027B544(void);
/* 9x */
extern int ehsys_53D7C1EE(int, int);
/* 9x */
extern int ehsys_34A7E8C2(int);
/* 9x */
extern int ehsys_07CAB9E4(int);
/* 9x */
extern void ehsys_E7BEDD6E(int);
/* 8x */
extern void ehsys_AF8E6886(void);
/* 8x */
extern void ehsys_8637BCB2(void);
/* 8x */
extern void ehsys_B8770B92(int, int, int);
/* 8x */
extern int ehsys_C0AB60EF(int, int);
/* 8x */
extern int ehsys_459B889D(int);
/* 8x */
extern int ehsys_1C2A8EDD(int, int, int);
/* reaches IoFileMgrForUser;Kernel_Library;SysMemUserForUse; 8x */
extern int ehsys_5836AFF1(void);
/* reaches ThreadManForUser; 8x */
extern int ehsys_8C5B148E(int, int, int);
/* reaches ThreadManForUser; 8x */
extern int ehsys_F96953BE(int, int, int, int, int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 8x */
extern void ehsys_0D3E2FA6(int, int);
/* 8x */
extern void ehsys_8798050C(void);
/* 8x */
extern int ehsys_8867335A(int);
/* 8x */
extern int ehsys_B3B5D3CF(void);
/* 8x */
extern void ehsys_5A023ABD(int, int);
/* 8x */
extern void ehsys_0D3E34B5(void);
/* 8x */
extern void ehsys_9EB9A3A6(int, int, int);
/* 8x */
extern void ehsys_906A916B(void);
/* 8x */
extern void ehsys_5A6B0741(int);
/* 8x */
extern int ehsys_687F1A2C(int);
/* 8x */
extern void ehsys_1D76FBF3(int, int);
/* 8x */
extern void ehsys_B6C65705(int, int, int);
/* 8x */
extern int ehsys_C4D9C911(int, int, int);
/* 8x */
extern int ehsys_BAB403B8(int, int);
/* 8x */
extern int ehsys_EF06FE41(int, int, int, int);
/* 8x */
extern int ehsys_7DFFA500(int, int);
/* 8x */
extern int ehsys_F711002C(void);
/* 8x */
extern int ehsys_9AFBEBC2(int);
/* 8x */
extern void ehsys_E618B6BA(int);
/* 8x */
extern void ehsys_D2361003(int);
/* reaches sceGe_user; 7x */
extern int ehsys_E8D57DC6(int, int);
/* 7x */
extern int ehsys_C774A9D5(int, int, int);
/* 7x */
extern int ehsys_54F69CFE(int, int, int);
/* 7x */
extern int ehsys_02C26DF1(int);
/* 7x */
extern int ehsys_4E3BEA66(void);
/* 7x */
extern void ehsys_E60D8E10(void);
/* reaches Kernel_Library;SysMemUserForUser; 7x */
extern int ehsys_F11F0D9A(int);
/* 7x */
extern int ehsys_6595A5B3(int);
/* 7x */
extern int ehsys_B8DDA661(int, int, int);
/* reaches ThreadManForUser; 7x */
extern void ehsys_088F768A(void);
/* 7x */
extern void ehsys_BF62545B(int, int, int);
/* 7x */
extern int ehsys_28BE130B(int);
/* reaches sceNet;sceNetAdhocctl; 7x */
extern void ehsys_C644C679(int);
/* 7x */
extern int ehsys_6A91E8E8(int);
/* 7x */
extern void ehsys_AE84266D(int);
/* 7x */
extern void ehsys_2EE943AC(int);
/* 7x */
extern int ehsys_DD4DAED2(int);
/* 7x */
extern void ehsys_3532DEB2(int);
/* 7x */
extern void ehsys_C1FD7BFC(int);
/* 7x */
extern void ehsys_C78C87F4(int, int);
/* 7x */
extern int ehsys_0836FA55(int);
/* 7x */
extern int ehsys_7754CFD2(int);
/* 7x */
extern int ehsys_9854B469(int);
/* 7x */
extern void ehsys_BB4F3954(int);
/* 7x */
extern void ehsys_1672C0A7(int);
/* 7x */
extern void ehsys_BD86E5F9(int);
/* 7x */
extern void ehsys_50EA4D71(int, int);
/* re-export of sceUtility:sceUtilityOskGetStatus(); 7x */
extern int ehsys_F3F76017(void);
/* 6x */
extern int ehsys_CE32B68D(int);
/* 6x */
extern int ehsys_56DA956A(int, int);
/* 6x */
extern int ehsys_A2C4E735(int, int);
/* 6x */
extern int ehsys_66B4DCA8(int, int, int);
/* 6x */
extern int ehsys_C217BED0(int, int, int, int);
/* 6x */
extern int ehsys_1C99A7A5(int);
/* 6x */
extern int ehsys_9074B94E(int, int, int);
/* 6x */
extern void ehsys_4786AAF9(int);
/* 6x */
extern int ehsys_91E5BB91(int, int, int, int);
/* 6x */
extern void ehsys_9FC4E656(int, int);
/* 6x */
extern int ehsys_31B68FCB(int);
/* 6x */
extern void ehsys_595083E7(int);
/* 6x */
extern int ehsys_0977A12F(int);
/* 6x */
extern int ehsys_5B08FB0D(void);
/* reaches sceLibFont; 6x */
extern int ehsys_826AE59C(void);
/* reaches ThreadManForUser;sceAtrac3plus;sceLibFont;sceSas; 6x */
extern int ehsys_F843E20A(int);
/* 6x */
extern int ehsys_6D6C9B94(void);
/* 6x */
extern void ehsys_6919FD3F(void);
/* reaches Kernel_Library;SysMemUserForUser; 6x */
extern int ehsys_9455886E(int);
/* 6x */
extern void ehsys_A6D7B8CF(int);
/* 6x */
extern int ehsys_D79EAEBD(void);
/* 6x */
extern void ehsys_2213CC45(int, int);
/* 6x */
extern void ehsys_DA66B694(int, int, int);
/* 6x */
extern void ehsys_C78D825A(int, int, int, int);
/* 6x */
extern int ehsys_83D08468(int);
/* 6x */
extern int ehsys_A263D2AF(int);
/* 6x */
extern int ehsys_6817B19B(int);
/* 6x */
extern int ehsys_46F3C6A2(void);
/* 6x */
extern int ehsys_5E3D649B(int);
/* 6x */
extern void ehsys_7B0C0E23(int);
/* re-export of sceUtility:sceUtilityOskInitStart(x); 6x */
extern int ehsys_F6269B82(int);
/* re-export of sceUtility:sceUtilityOskShutdownStart(); 6x */
extern int ehsys_3DFAEBA9(void);
/* re-export of sceUtility:sceUtilityOskUpdate(i); 6x */
extern int ehsys_4B85C861(int);
/* 5x */
extern int ehsys_E821E845(int, int, int, int, int);
/* 5x */
extern int ehsys_B49A7697(int, int, int);
/* 5x */
extern int ehsys_C87E4924(int, int);
/* reaches IoFileMgrForUser;Kernel_Library;SysMemUserForUse; 5x */
extern void ehsys_BF3E9066(int, int, int, int);
/* reaches IoFileMgrForUser;Kernel_Library;SysMemUserForUse; 5x */
extern void ehsys_68728B41(int, int, int);
/* 5x */
extern int ehsys_E6977584(int, int, int, int, int, int);
/* 5x */
extern void ehsys_63CD43C1(void);
/* 5x */
extern void ehsys_CA9DD7B6(int);
/* 5x */
extern int ehsys_11EBE80C(int, int, int, int, int);
/* 5x */
extern int ehsys_F0243623(int, int);
/* 5x */
extern int ehsys_60F2ECE8(int, int, int, int, int, int, int, int);
/* 5x */
extern int ehsys_D0E95BD8(int, int);
/* 5x */
extern void ehsys_03E45FFF(void);
/* 5x */
extern void ehsys_53C23B57(int);
/* 5x */
extern void ehsys_8060707A(void);
/* reaches Kernel_Library;SysMemUserForUser;ThreadManForUse; 5x */
extern int ehsys_B48A11FB(int, int);
/* 5x */
extern int ehsys_07BBF7DB(void);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 5x */
extern void ehsys_74CA1190(void);
/* reaches sceLibFont; 5x */
extern int ehsys_87A64CC6(int, int, int);
/* reaches ThreadManForUser;sceAtrac3plus;sceLibFont;sceSas; 5x */
extern int ehsys_530BB327(int);
/* reaches IoFileMgrForUser; 5x */
extern int ehsys_A93273D2(int, int);
/* reaches IoFileMgrForUser;ThreadManForUser;sceAtrac3plus;; 5x */
extern int ehsys_486EBAC0(int);
/* reaches InterruptManager;SysMemUserForUser;ThreadManForU; 5x */
extern void ehsys_A94DF30B(void);
/* reaches sceNetAdhoc;sceNetAdhocMatching; 5x */
extern void ehsys_8852C022(void);
/* 5x */
extern int ehsys_57345021(int, int);
/* 5x */
extern int ehsys_3FD815F4(void);
/* 5x */
extern int ehsys_62A243C4(void);
/* 5x */
extern int ehsys_5ABF64AE(void);
/* 5x */
extern int ehsys_D4771E47(void);
/* 5x */
extern void ehsys_E6E2606B(int, int);
/* 5x */
extern void ehsys_8AA48382(int, int);
/* 5x */
extern void ehsys_0E0216E1(int, int);
/* 5x */
extern void ehsys_83E48CCF(int, int);
/* 5x */
extern int ehsys_020C6314(void);
/* 5x */
extern void ehsys_1F435989(int, int);
/* 5x */
extern void ehsys_E8EB3756(int);
/* 5x */
extern int ehsys_BE54B40C(void);
/* 5x */
extern void ehsys_78ED2B0F(int);
/* 5x */
extern int ehsys_55981772(void);
/* 5x */
extern void ehsys_783340AE(int, int);
/* 5x */
extern void ehsys_AC3EDD06(int, int);
/* 5x */
extern int ehsys_9D9E0568(int);
/* 5x */
extern int ehsys_95E50EFA(int);
/* 5x */
extern void ehsys_E3C8F657(int);
/* 5x */
extern void ehsys_375A7F03(int);
/* 5x */
extern void ehsys_A8CD2FB9(int);
/* 5x */
extern void ehsys_51B8DDE5(int);
/* 5x */
extern void ehsys_74C5FE46(int);
/* reaches ThreadManForUser;sceUtility; 5x */
extern int ehsys_70CB33BE(void);
/* 5x */
extern void ehsys_DCA0DCE1(void);
/* reaches ModuleMgrForUser;sceUtility; 5x */
extern int ehsys_245526EE(void);
/* re-export of ThreadManForUser:sceKernelSetEventFlag(); 5x */
extern void ehsys_1FB15A32(void);
/* re-export of ThreadManForUser:sceKernelWaitEventFlagCB(); 5x */
extern void ehsys_328C546A(void);
/* 4x */
extern int ehsys_6DBCF897(int, int, int, int);
/* 4x */
extern int ehsys_1B5B82BC(int);
/* 4x */
extern int ehsys_BC1D779C(int, int, int);
/* 4x */
extern int ehsys_3325AA47(int, int);
/* 4x */
extern int ehsys_660F96F4(int, int, int);
/* 4x */
extern int ehsys_7B552C34(int);
/* 4x */
extern int ehsys_2630B590(void);
/* 4x */
extern int ehsys_912118BD(int);
/* 4x */
extern void ehsys_1507D27D(int, int, int, int);
/* 4x */
extern void ehsys_8EA5CCE1(void);
/* 4x */
extern void ehsys_B46025DF(int, int, int);
/* 4x */
extern void ehsys_552AC0DF(int, int);
/* 4x */
extern int ehsys_B4136BBB(int, int);
/* 4x */
extern int ehsys_942E589C(int, int);
/* 4x */
extern void ehsys_CB9CCF0B(int, int);
/* 4x */
extern int ehsys_A3FF902D(int);
/* 4x */
extern int ehsys_94982653(int, int);
/* 4x */
extern void ehsys_AB8BD7CA(int);
/* 4x */
extern void ehsys_4357F16E(int, int);
/* 4x */
extern int ehsys_AD222020(int, int, int);
/* 4x */
extern int ehsys_15AF4C89(int);
/* reaches ThreadManForUser; 4x */
extern int ehsys_47719795(int, int, int);
/* 4x */
extern int ehsys_BA168C37(int, int);
/* 4x */
extern void ehsys_ED2013FB(int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 4x */
extern void ehsys_6DD74ECC(void);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 4x */
extern void ehsys_D7D8674A(void);
/* 4x */
extern void ehsys_3EC38F85(int);
/* 4x */
extern void ehsys_E4867425(int);
/* reaches Kernel_Library;SysMemUserForUser; 4x */
extern int ehsys_5CEDF44D(int);
/* 4x */
extern void ehsys_6A55182E(void);
/* 4x */
extern int ehsys_6FE21799(void);
/* 4x */
extern int ehsys_983DA324(int);
/* 4x */
extern void ehsys_EB6FAACF(int, int);
/* 4x */
extern int ehsys_FEFCBA3E(void);
/* 4x */
extern int ehsys_0A1BFD9A(void);
/* 4x */
extern void ehsys_B6D80F09(int);
/* reaches sceImpose; 4x */
extern void ehsys_1F710553(int);
/* 4x */
extern int ehsys_1D9BF787(void);
/* 4x */
extern void ehsys_F1CE9623(int, int);
/* 4x */
extern int ehsys_339B98FC(int);
/* 4x */
extern void ehsys_2D976EA8(int, int);
/* 4x */
extern void ehsys_E7FAA144(int, int);
/* 4x */
extern void ehsys_9F4359AB(int, int);
/* 4x */
extern void ehsys_0EB054A9(int, int);
/* 4x */
extern int ehsys_F3DEE95F(int, int);
/* 4x */
extern int ehsys_E9F96A3F(int);
/* 4x */
extern int ehsys_64D352A1(int, int, int);
/* 4x */
extern int ehsys_7DAC692D(int, int, int);
/* 4x */
extern int ehsys_E4F368A9(int);
/* 4x */
extern int ehsys_2DE9CA69(int);
/* 4x */
extern int ehsys_88D0D5B7(int);
/* 4x */
extern int ehsys_7F43E1A8(int);
/* 4x */
extern int ehsys_9E42D8A7(int);
/* 4x */
extern int ehsys_05AD6FCE(int);
/* 4x */
extern int ehsys_9E26B410(int);
/* 4x */
extern int ehsys_1DA3918E(void);
/* 4x */
extern void ehsys_C2235BFA(int);
/* 4x */
extern int ehsys_7F981A88(int);
/* 4x */
extern void ehsys_A5D0CCD2(int);
/* 4x */
extern int ehsys_224CD64E(int, int);
/* re-export of ThreadManForUser:sceKernelSignalSema(); 4x */
extern void ehsys_3F53E640(void);
/* re-export of ThreadManForUser:sceKernelClearEventFlag(); 4x */
extern void ehsys_812346E4(void);
/* 3x */
extern int ehsys_E13B6DAE(void);
/* 3x */
extern int ehsys_4C0E0274(int, int);
/* 3x */
extern void ehsys_DA34FB1A(void);
/* 3x */
extern int ehsys_37548694(int, int, int);
/* 3x */
extern int ehsys_64CE5F24(int, int, int);
/* 3x */
extern int ehsys_ACCDB524(int, int, int);
/* 3x */
extern int ehsys_D63C9E95(int, int);
/* 3x */
extern int ehsys_37562668(int, int, int);
/* 3x */
extern int ehsys_27511CE0(int, int);
/* 3x */
extern void ehsys_8D0CE141(void);
/* 3x */
extern void ehsys_C204E9F8(void);
/* 3x */
extern int ehsys_7CBFBEC2(int, int);
/* reaches IoFileMgrForUser; 3x */
extern int ehsys_CB1D1CCC(void);
/* 3x */
extern int ehsys_55F589D0(int);
/* 3x */
extern int ehsys_BAB43E61(int, int);
/* 3x */
extern int ehsys_5B05F797(int);
/* reaches ThreadManForUser;sceUtility; 3x */
extern int ehsys_597CDADD(int, int, int, int, int);
/* 3x */
extern void ehsys_21C4F2FA(void);
/* 3x */
extern int ehsys_68B20872(void);
/* 3x */
extern int ehsys_717593A3(int, int, int);
/* 3x */
extern int ehsys_00F1E005(int, int);
/* 3x */
extern int ehsys_0A3651EF(int, int, int, int);
/* 3x */
extern int ehsys_8FB8C0A6(int, int, int);
/* 3x */
extern void ehsys_FF360587(int, int);
/* 3x */
extern int ehsys_E36AFCA5(void);
/* 3x */
extern int ehsys_E11E4575(int);
/* 3x */
extern void ehsys_4CB2E2AD(void);
/* 3x */
extern void ehsys_25710975(void);
/* 3x */
extern int ehsys_4E4F1811(int);
/* 3x */
extern int ehsys_99F81E55(int);
/* 3x */
extern int ehsys_E167E1C0(int, int, int, int);
/* 3x */
extern int ehsys_5777192D(void);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 3x */
extern void ehsys_8884088B(int, int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 3x */
extern void ehsys_DF5CB459(int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 3x */
extern void ehsys_8A309EAF(void);
/* 3x */
extern void ehsys_38DDEDD1(int, int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 3x */
extern int ehsys_B445B257(int, int);
/* reaches InterruptManager;ThreadManForUser;sceNet;sceNetA; 3x */
extern void ehsys_FC53D253(void);
/* reaches sceNetAdhoc;sceNetAdhocMatching; 3x */
extern void ehsys_D49B6BDD(int);
/* 3x */
extern void ehsys_93578062(int);
/* 3x */
extern void ehsys_3F68D487(int, int, int);
/* 3x */
extern void ehsys_E1ECBDFB(void);
/* reaches Kernel_Library;SysMemUserForUser;sceImpose;sceOp; 3x */
extern int ehsys_6EEF2E59(void);
/* 3x */
extern void ehsys_C2295CF3(int);
/* 3x */
extern void ehsys_BCCFD219(int, int);
/* 3x */
extern void ehsys_1E3B22BA(int);
/* 3x */
extern void ehsys_B1D174DA(int);
/* 3x */
extern void ehsys_A4375D58(int);
/* 3x */
extern void ehsys_2D86F442(int);
/* 3x */
extern void ehsys_6DF8A193(void);
/* 3x */
extern void ehsys_B0DA6DA3(int, int);
/* 3x */
extern int ehsys_184C52C0(int);
/* 3x */
extern int ehsys_31B1A6F0(void);
/* 3x */
extern int ehsys_293220C2(int, int);
/* 3x */
extern void ehsys_585DF0FF(int, int, int);
/* 3x */
extern void ehsys_CAB9DF55(int, int, int, int);
/* 3x */
extern void ehsys_8BD528F0(void);
/* 3x */
extern void ehsys_CC728840(int, int);
/* 3x */
extern void ehsys_58E54272(int);
/* 3x */
extern void ehsys_F1CABFAC(int);
/* 3x */
extern int ehsys_1FD5A78C(int);
/* 3x */
extern void ehsys_11369E88(int, int);
/* 3x */
extern void ehsys_5A5244E3(int);
/* 3x */
extern void ehsys_923D4D46(int);
/* 3x */
extern void ehsys_8517B8C4(int, int);
/* 3x */
extern int ehsys_02D6D189(int);
/* 3x */
extern void ehsys_92675210(int, int);
/* 3x */
extern void ehsys_B75B23D0(int, int);
/* 3x */
extern void ehsys_F358A88E(int, int);
/* 3x */
extern void ehsys_1C3A6111(int, int);
/* 3x */
extern void ehsys_F078D8CF(int);
/* 3x */
extern void ehsys_DDAAA4FF(int, int);
/* 3x */
extern int ehsys_51A71BD2(int);
/* 3x */
extern int ehsys_EAB73341(int, int, int);
/* 3x */
extern int ehsys_DF62D899(int);
/* 3x */
extern void ehsys_9E72EF23(int, int, int);
/* 3x */
extern int ehsys_A864B21B(int, int, int);
/* 3x */
extern int ehsys_81771688(int);
/* 3x */
extern int ehsys_534B5F77(int);
/* 3x */
extern int ehsys_41C38588(int);
/* 3x */
extern void ehsys_6EAF1121(int);
/* 3x */
extern int ehsys_83458494(int);
/* 3x */
extern void ehsys_556194E7(int);
/* 3x */
extern void ehsys_287B3382(int);
/* 3x */
extern void ehsys_A046924B(int);
/* 3x */
extern void ehsys_18E75398(int);
/* 3x */
extern void ehsys_86A5D733(int);
/* re-export of ThreadManForUser:sceKernelGetThreadCurrentPriority(); 3x */
extern void ehsys_94AA61EE(void);
/* reaches Kernel_Library;sceGe_user; 2x */
extern int ehsys_5F01916F(int, int, int);
/* reaches Kernel_Library;sceGe_user; 2x */
extern void ehsys_BA8CF6B9(void);
/* 2x */
extern void ehsys_D9F56690(void);
/* 2x */
extern void ehsys_8F2316E1(int);
/* 2x */
extern void ehsys_A0547747(int);
/* 2x */
extern void ehsys_388D8736(int);
/* reaches sceGe_user; 2x */
extern int ehsys_420E7DB5(int, int, int, int);
/* 2x */
extern int ehsys_0D188658(int, int);
/* 2x */
extern void ehsys_307DF57A(void);
/* 2x */
extern int ehsys_803FC64B(int, int);
/* 2x */
extern int ehsys_ED06F118(int, int);
/* 2x */
extern int ehsys_8BFD0B7B(int, int);
/* 2x */
extern void ehsys_0C27DC4A(int, int);
/* 2x */
extern void ehsys_C2CD822B(int, int);
/* 2x */
extern int ehsys_BE792119(int);
/* 2x */
extern void ehsys_5C4E84AA(void);
/* 2x */
extern void ehsys_424598D9(void);
/* 2x */
extern int ehsys_94F364BA(int, int);
/* reaches Kernel_Library;UtilsForUser;sceCtrl;sceDisplay;s; 2x */
extern int ehsys_8174A2CB(void);
/* reaches ThreadManForUser; 2x */
extern int ehsys_2BACAD04(int, int, int, int);
/* reaches ThreadManForUser; 2x */
extern int ehsys_58F84DA0(void);
/* reaches ThreadManForUser; 2x */
extern int ehsys_20A40A75(void);
/* 2x */
extern int ehsys_FAAC7D51(int);
/* 2x */
extern void ehsys_F292E199(void);
/* 2x */
extern int ehsys_2074DED0(int, int, int);
/* 2x */
extern int ehsys_130C21DC(int);
/* 2x */
extern int ehsys_E62EDAB3(int, int, int);
/* 2x */
extern int ehsys_4258FC8D(int, int, int);
/* 2x */
extern int ehsys_7ABC8184(void);
/* 2x */
extern void ehsys_01AA3558(void);
/* 2x */
extern int ehsys_826BD884(void);
/* 2x */
extern void ehsys_4DFEDFFA(int);
/* 2x */
extern int ehsys_6F0D36D3(void);
/* 2x */
extern int ehsys_F48E70FB(int, int, int);
/* 2x */
extern int ehsys_890D2BD0(void);
/* 2x */
extern int ehsys_D5E5A748(int, int);
/* 2x */
extern void ehsys_D7F13632(int);
/* 2x */
extern int ehsys_56E6D6D6(void);
/* 2x */
extern int ehsys_ABFD44C4(int, int, int, int);
/* 2x */
extern int ehsys_79E8E06C(int, int, int, int, int, int);
/* reaches ThreadManForUser; 2x */
extern int ehsys_D80C7D36(int, int);
/* 2x */
extern int ehsys_C01F381E(int);
/* 2x */
extern void ehsys_BF1A3037(int);
/* 2x */
extern int ehsys_B0D6F4FF(void);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 2x */
extern void ehsys_A84EDF3B(int);
/* 2x */
extern int ehsys_D319DD3A(int, int, int);
/* 2x */
extern int ehsys_805DBDF3(int, int, int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 2x */
extern void ehsys_82DEC529(int);
/* 2x */
extern int ehsys_D3448D59(void);
/* 2x */
extern int ehsys_3E4FC8A6(void);
/* 2x */
extern void ehsys_BCEB40ED(int);
/* reaches sceNetAdhoc;sceNetAdhocMatching; 2x */
extern void ehsys_FF141CC8(int, int);
/* 2x */
extern void ehsys_C978255D(int);
/* 2x */
extern void ehsys_EF9EFF0F(int);
/* 2x */
extern void ehsys_173C81DF(void);
/* 2x */
extern void ehsys_892F5B43(int, int, int);
/* 2x */
extern void ehsys_70563675(void);
/* reaches sceNetAdhoc;sceNetAdhocMatching; 2x */
extern void ehsys_6DBE26D9(void);
/* 2x */
extern int ehsys_ED529D26(int);
/* 2x */
extern void ehsys_7140069D(int);
/* 2x */
extern int ehsys_B61A765E(int);
/* 2x */
extern void ehsys_8CE72107(int, int);
/* 2x */
extern void ehsys_D98EA579(int, int, int);
/* 2x */
extern void ehsys_5F673552(void);
/* 2x */
extern int ehsys_CDECA77A(void);
/* 2x */
extern int ehsys_E11505A9(void);
/* 2x */
extern int ehsys_F2BA729B(void);
/* 2x */
extern void ehsys_8171A371(int);
/* 2x */
extern void ehsys_79B05ABC(int);
/* 2x */
extern void ehsys_EFADAB40(int, int);
/* 2x */
extern void ehsys_A845D5F0(int, int);
/* 2x */
extern void ehsys_98CFEF3D(int, int);
/* 2x */
extern void ehsys_93051754(int, int);
/* 2x */
extern int ehsys_F334B3F9(int, int);
/* 2x */
extern int ehsys_3ADC4161(int);
/* 2x */
extern int ehsys_F1D5B644(int, int);
/* 2x */
extern void ehsys_665C6D67(int);
/* 2x */
extern void ehsys_DDDE1D55(int);
/* 2x */
extern void ehsys_9C7833AA(int);
/* 2x */
extern int ehsys_9A381A51(int);
/* 2x */
extern int ehsys_E87491C1(void);
/* 2x */
extern void ehsys_3BB4C309(int);
/* 2x */
extern int ehsys_415BCECC(void);
/* 2x */
extern int ehsys_850B903B(int);
/* 2x */
extern int ehsys_69BC0E71(int);
/* 2x */
extern int ehsys_A4585C47(int);
/* 2x */
extern int ehsys_D859D27D(int);
/* 2x */
extern void ehsys_EC23C07C(int);
/* 2x */
extern int ehsys_DC3F7D07(void);
/* 2x */
extern void ehsys_64320906(int, int);
/* 2x */
extern void ehsys_074A3951(int, int);
/* 2x */
extern int ehsys_F562B0AE(void);
/* 2x */
extern void ehsys_1020AABA(int, int);
/* 2x */
extern int ehsys_35CD6059(void);
/* 2x */
extern int ehsys_3EF8731C(int, int);
/* 2x */
extern int ehsys_BAF2096A(int, int, int);
/* 2x */
extern int ehsys_B059F726(void);
/* 2x */
extern void ehsys_1CCB5DD4(int, int, int);
/* 2x */
extern void ehsys_0D957433(int, int);
/* 2x */
extern int ehsys_C42E1A5A(int, int);
/* 2x */
extern int ehsys_89EB3BA4(int);
/* 2x */
extern int ehsys_3748A4B1(void);
/* 2x */
extern int ehsys_357FB288(int);
/* 2x */
extern int ehsys_FC940D59(int);
/* 2x */
extern int ehsys_DCCE7AAA(int);
/* 2x */
extern void ehsys_86A6704D(int);
/* 2x */
extern void ehsys_40D26DEC(int);
/* 2x */
extern void ehsys_69B00027(int);
/* 2x */
extern void ehsys_3C238AF0(int);
/* 2x */
extern void ehsys_5C8EF0DE(int);
/* 2x */
extern void ehsys_F8425C44(int);
/* 2x */
extern void ehsys_CEAFCA0A(int);
/* re-export of ModuleMgrForUser:sceKernelStartModule(); 2x */
extern void ehsys_50F0C1EC(void);
/* re-export of ModuleMgrForUser:sceKernelStopModule(); 2x */
extern void ehsys_D1FF982A(void);
/* re-export of ModuleMgrForUser:sceKernelUnloadModule(); 2x */
extern void ehsys_2E0911AA(void);
/* re-export of ThreadManForUser:sceKernelWaitSemaCB(); 2x */
extern void ehsys_6D212BAC(void);
/* re-export of ThreadManForUser:sceKernelPollSema(); 2x */
extern void ehsys_58B1F937(void);
/* re-export of ThreadManForUser:sceKernelGetSystemTimeWide(); 2x */
extern void ehsys_82BC5777(void);
/* re-export of IoFileMgrForUser:sceIoDopen(s); 2x */
extern int ehsys_B29DDF9C(int);
/* re-export of IoFileMgrForUser:sceIoDclose(i); 2x */
extern int ehsys_EB092469(int);
/* re-export of IoFileMgrForUser:sceIoDread(ix); 2x */
extern int ehsys_E3EB004C(int, int);
/* 1x */
extern int ehsys_EB6D20A5(void);
/* 1x */
extern int ehsys_7E66D731(void);
/* reaches Kernel_Library;SysMemUserForUser; 1x */
extern void ehsys_481C9ADA(int);
/* reaches Kernel_Library;SysMemUserForUser; 1x */
extern void ehsys_AD8AF84F(int);
/* 1x */
extern int ehsys_A48D2592(int, int, int);
/* 1x */
extern int ehsys_8B52B60D(int, int, int);
/* 1x */
extern int ehsys_F5477BCF(int, int);
/* 1x */
extern void ehsys_BB54BCFE(int, int);
/* 1x */
extern int ehsys_6F0F019C(int, int, int);
/* 1x */
extern void ehsys_12DA0DE2(int, int);
/* 1x */
extern int ehsys_FE3B7EB5(int);
/* 1x */
extern int ehsys_7BCB8905(int, int, int);
/* 1x */
extern int ehsys_500B1756(int);
/* 1x */
extern int ehsys_FAB49CC1(int, int, int);
/* 1x */
extern int ehsys_158364F1(int, int);
/* 1x */
extern int ehsys_7C331AE4(int, int, int);
/* 1x */
extern int ehsys_059281D4(int, int);
/* 1x */
extern void ehsys_DA790D12(void);
/* 1x */
extern void ehsys_26F05781(void);
/* 1x */
extern void ehsys_38401656(int);
/* 1x */
extern int ehsys_E758A14F(int, int, int);
/* 1x */
extern int ehsys_44653809(int, int, int, int);
/* 1x */
extern int ehsys_B442C776(int);
/* reaches ThreadManForUser; 1x */
extern int ehsys_46FDDA71(int, int, int, int, int, int, int);
/* 1x */
extern int ehsys_614C6885(void);
/* reaches IoFileMgrForUser;Kernel_Library;UtilsForUser;sce; 1x */
extern int ehsys_AB7BB274(void);
/* reaches ThreadManForUser; 1x */
extern int ehsys_2058A08F(void);
/* 1x */
extern int ehsys_D2EE9973(int);
/* 1x */
extern int ehsys_316D8C28(int);
/* 1x */
extern int ehsys_F20A12CE(void);
/* 1x */
extern int ehsys_FFBC9F88(int, int, int);
/* 1x */
extern int ehsys_ACAC5C40(int);
/* 1x */
extern int ehsys_35D67398(int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 1x */
extern void ehsys_5B4DADF5(int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 1x */
extern void ehsys_0190A327(int);
/* 1x */
extern int ehsys_EB263A38(void);
/* 1x */
extern int ehsys_12B0F55D(int);
/* 1x */
extern int ehsys_17333DB7(void);
/* 1x */
extern void ehsys_D6885B1A(int);
/* 1x */
extern int ehsys_A045CACE(void);
/* 1x */
extern int ehsys_5CACF78D(int);
/* reaches Kernel_Library;SysMemUserForUser; 1x */
extern int ehsys_85906D69(int);
/* 1x */
extern int ehsys_65FA8E18(void);
/* 1x */
extern int ehsys_83B39FA9(int);
/* 1x */
extern int ehsys_D0FBFC51(int);
/* 1x */
extern void ehsys_1E4B7ED5(int);
/* reaches Kernel_Library;ThreadManForUser;sceGe_user;sceLi; 1x */
extern int ehsys_0441C9EF(int, int, int, int);
/* reaches Kernel_Library;ThreadManForUser;sceGe_user;sceLi; 1x */
extern int ehsys_D62744B5(int, int, int, int, int);
/* 1x */
extern int ehsys_574E5B18(int, int, int, int, int);
/* 1x */
extern int ehsys_52A444CF(int, int, int, int, int, int);
/* reaches Kernel_Library;sceGe_user;sceLibFont; 1x */
extern int ehsys_72E1BD70(int, int, int, int, int, int);
/* 1x */
extern int ehsys_19C5BDE2(int, int, int);
/* 1x */
extern void ehsys_57018B7C(int);
/* reaches sceUtility; 1x */
extern int ehsys_F5FE661C(void);
/* reaches sceGe_user;sceUtility; 1x */
extern int ehsys_054A8ACD(void);
/* reaches sceUtility; 1x */
extern int ehsys_2A1C18E9(void);
/* reaches sceGe_user;sceUtility; 1x */
extern int ehsys_D5CEC905(void);
/* reaches sceUtility; 1x */
extern int ehsys_B10A7131(void);
/* reaches sceGe_user;sceUtility; 1x */
extern int ehsys_F90CC1D7(void);
/* reaches sceUtility; 1x */
extern int ehsys_B6C6EB69(void);
/* reaches sceGe_user;sceUtility; 1x */
extern int ehsys_4A31C963(void);
/* reaches sceUtility; 1x */
extern int ehsys_A6669074(void);
/* reaches sceGe_user;sceUtility; 1x */
extern int ehsys_B8010A25(void);
/* reaches sceUtility; 1x */
extern int ehsys_B8B856F6(void);
/* reaches sceGe_user;sceUtility; 1x */
extern int ehsys_84BE0718(void);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 1x */
extern void ehsys_F5D788E4(int);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 1x */
extern void ehsys_7EE06EF8(void);
/* 1x */
extern int ehsys_2E783F70(void);
/* reaches ThreadManForUser;sceAtrac3plus;sceSasCore; 1x */
extern void ehsys_80E7F36C(int);
/* 1x */
extern void ehsys_57724B02(void);
/* 1x */
extern void ehsys_592F970A(void);
/* 1x */
extern int ehsys_1B4AF0F5(int, int, int, int, int);
/* 1x */
extern void ehsys_8EC4A14F(int, int, int);
/* 1x */
extern int ehsys_4878E980(int);
/* 1x */
extern void ehsys_BBB5D950(int, int);
/* 1x */
extern int ehsys_DD69EDFB(void);
/* 1x */
extern int ehsys_F96D270D(void);
/* 1x */
extern int ehsys_2F510B80(void);
/* 1x */
extern int ehsys_1D821C84(void);
/* 1x */
extern int ehsys_379BEA78(void);
/* reaches ThreadManForUser; 1x */
extern int ehsys_74E51EA4(int, int, int);
/* 1x */
extern void ehsys_D14D875D(void);
/* 1x */
extern void ehsys_D66F81DF(int);
/* 1x */
extern void ehsys_D7221D20(void);
/* 1x */
extern void ehsys_FF4748F0(int);
/* reaches sceNetAdhoc;sceNetAdhocMatching; 1x */
extern void ehsys_057BAF6A(int, int);
/* 1x */
extern void ehsys_0CEF10F0(int, int);
/* 1x */
extern void ehsys_6AE55E91(int);
/* reaches sceNetAdhoc; 1x */
extern void ehsys_B722881B(int);
/* 1x */
extern void ehsys_958F298F(void);
/* 1x */
extern void ehsys_D2B87B2C(int, int);
/* reaches sceNetAdhoc; 1x */
extern void ehsys_027B9796(int, int);
/* 1x */
extern void ehsys_6368BABC(int);
/* 1x */
extern void ehsys_2F21139D(int);
/* 1x */
extern int ehsys_19AC3ED4(int, int);
/* 1x */
extern void ehsys_E43434AC(int);
/* reaches sceRtc; 1x */
extern int ehsys_CC32BE69(int);
/* 1x */
extern void ehsys_008B4553(void);
/* 1x */
extern void ehsys_D9E726DC(void);
/* 1x */
extern int ehsys_4D1B2279(void);
/* 1x */
extern void ehsys_49199F3F(int, int, int);
/* 1x */
extern void ehsys_569E5E02(int, int, int);
/* 1x */
extern void ehsys_9559D88B(void);
/* 1x */
extern int ehsys_26BDF70F(void);
/* 1x */
extern int ehsys_46EACB7C(void);
/* 1x */
extern void ehsys_74CB7D02(void);
/* 1x */
extern void ehsys_5ED6B8AE(void);
/* 1x */
extern void ehsys_7A8E41CA(void);
/* 1x */
extern void ehsys_C15BF702(void);
/* 1x */
extern void ehsys_6E04A2B5(void);
/* 1x */
extern void ehsys_3134F230(void);
/* 1x */
extern void ehsys_05FD3047(int);
/* 1x */
extern void ehsys_97D7BF5F(void);
/* 1x */
extern int ehsys_251128FD(int);
/* 1x */
extern void ehsys_0ED40BD9(int);
/* 1x */
extern int ehsys_6533F67D(void);
/* 1x */
extern void ehsys_99E9314A(int);
/* 1x */
extern int ehsys_F352F222(void);
/* 1x */
extern void ehsys_3191B26A(int);
/* 1x */
extern int ehsys_71B597B9(int);
/* 1x */
extern int ehsys_3BC985D1(int);
/* 1x */
extern void ehsys_5EB01D69(int, int);
/* 1x */
extern void ehsys_C23B8C57(int, int);
/* 1x */
extern void ehsys_AEA7AA02(int);
/* 1x */
extern int ehsys_E738DE20(int);
/* 1x */
extern void ehsys_7E155A3E(int);
/* 1x */
extern void ehsys_5096D1B3(void);
/* 1x */
extern void ehsys_432B2436(int, int);
/* 1x */
extern void ehsys_218CCFB3(void);
/* 1x */
extern void ehsys_93A6F5A4(void);
/* 1x */
extern void ehsys_4B6108E5(void);
/* 1x */
extern void ehsys_B9661F20(int);
/* 1x */
extern void ehsys_D84432B6(void);
/* 1x */
extern void ehsys_78749045(int, int);
/* 1x */
extern int ehsys_9831163C(void);
/* 1x */
extern int ehsys_F7D9BEF6(void);
/* 1x */
extern void ehsys_845D409B(int, int, int);
/* 1x */
extern void ehsys_F6845BB5(void);
/* 1x */
extern int ehsys_DF190399(int);
/* 1x */
extern void ehsys_2157B640(int, int);
/* 1x */
extern int ehsys_CCDAED90(void);
/* 1x */
extern void ehsys_6CD914D3(int);
/* 1x */
extern void ehsys_11C6BBA1(int);
/* 1x */
extern void ehsys_99C49A5D(int, int);
/* 1x */
extern int ehsys_635BB4EE(int);
/* 1x */
extern int ehsys_756D3370(int);
/* 1x */
extern int ehsys_159AFF02(void);
/* 1x */
extern void ehsys_E0EB5D1B(int);
/* 1x */
extern int ehsys_788CFA4B(int, int);
/* 1x */
extern void ehsys_5305D550(int);
/* 1x */
extern int ehsys_8B3C2942(int, int);
/* 1x */
extern int ehsys_BABCE790(int, int, int);
/* 1x */
extern int ehsys_BB977070(int, int, int);
/* 1x */
extern int ehsys_AC7C7A6A(int, int, int);
/* 1x */
extern int ehsys_994CF8F8(int, int, int);
/* 1x */
extern int ehsys_44E1C5AD(int, int, int);
/* 1x */
extern int ehsys_E4BD1C8F(int, int, int);
/* 1x */
extern int ehsys_C5F0D6F8(int, int, int);
/* 1x */
extern int ehsys_0A60B08B(void);
/* 1x */
extern void ehsys_8F688257(int, int, int);
/* 1x */
extern int ehsys_EB6AD488(int, int);
/* 1x */
extern void ehsys_34F0F2A2(int);
/* 1x */
extern int ehsys_B2ECA684(void);
/* 1x */
extern int ehsys_B2C3FF7E(int);
/* 1x */
extern int ehsys_19CDE964(int);
/* 1x */
extern void ehsys_84F43A88(int);
/* 1x */
extern void ehsys_B86A0894(int);
/* 1x */
extern void ehsys_E65115B6(int);
/* 1x */
extern void ehsys_FA8128D9(int);
/* 1x */
extern void ehsys_57E56FD3(int);
/* 1x */
extern void ehsys_B1BA3637(int);
/* 1x */
extern void ehsys_50F5EBDB(int);
/* 1x */
extern int ehsys_985F3AE0(int);
/* 1x */
extern void ehsys_BBC7AF01(int, int);
/* re-export of ThreadManForUser:sceKernelCreateThread(); 1x */
extern void ehsys_446D8DE6(void);
/* re-export of ThreadManForUser:sceKernelStartThread(); 1x */
extern void ehsys_F475845D(void);
/* re-export of ThreadManForUser:sceKernelTerminateDeleteThread(); 1x */
extern void ehsys_383F7BCC(void);
/* re-export of ThreadManForUser:sceKernelCreateSema(); 1x */
extern void ehsys_D6DA4BA1(void);
/* re-export of ThreadManForUser:sceKernelDeleteSema(); 1x */
extern void ehsys_28B6489C(void);
/* re-export of ThreadManForUser:sceKernelCreateEventFlag(); 1x */
extern void ehsys_55C20A00(void);
/* re-export of ThreadManForUser:sceKernelDeleteEventFlag(); 1x */
extern void ehsys_EF9E4C70(void);
/* re-export of ThreadManForUser:sceKernelCreateVTimer(); 1x */
extern void ehsys_20FFF560(void);
/* re-export of ThreadManForUser:sceKernelDeleteVTimer(); 1x */
extern void ehsys_328F9E52(void);

#endif /* EHSYS_H */
